Repository highcharts/highcharts, pull requests merged in 2018-08, with the labels that each got.

#8799 bugfix/treemap-missing-parent-breaks
  js/modules/treemap.src.js
  samples/unit-tests/series-treemap/members/demo.js
Labels: Regression

#8837 Fixed yAxis.reversed defaulting to false in Highmaps API docs.
  js/parts/Axis.js
Labels: Bug, Docs

#8835 Added support for AMD module loading.
  package.json
  readme.md
Labels: Enhancement
