Repository highcharts/highcharts, pull requests merged in 2018-10, with the labels that each got.

#9086 Tools: Add tsd and tsd-lint for TypeScript declarations.
  gulpfile.js
  package.json
  test/typescript/highcharts.ts
  test/typescript/modules/accessibility.ts
  test/typescript/modules/export-data.ts
  test/typescript/modules/exporting.ts
  test/typescript/modules/offline-exporting.ts
  test/typescript/modules/series-label.ts
  test/typescript/modules/vector.ts
  tsconfig.json
  tslint.json
Labels: Review

#9093 bugfix/9049-lines-to-culled-points-boost
  js/modules/boost.src.js
Labels: Review

#9095 Tools: Improve handling of mixed option doclets.
  tools/jsdoc/plugins/highcharts.namespace.js
Labels: Review

#9107 bugfix/9075-addpoint-navigator-sticktomin
  js/parts/Navigator.js
  samples/unit-tests/navigator/navigator/demo.js
Labels: Review

#9127 Enhancement/multiple-lines-mixin
  js/indicators/bollinger-bands.src.js
  js/indicators/stochastic.src.js
  js/mixins/multipe-lines.js
Labels: Review

#9126 bugfix/9119-overlapping-datalabels-stacklabels
  js/modules/overlapping-datalabels.src.js
  samples/unit-tests/datalabels/overlapping/demo.js
Labels: Review

#9115 bugfix/9020-columnrange-datagrouping-datalabels
  js/parts-more/AreaRangeSeries.js
  samples/unit-tests/series-arearange/datagrouping/demo.js
Labels: Review

#9154 hs7/aroon
  js/indicators/aroon-oscillator.src.js
  js/indicators/aroon.src.js
  js/masters/indicators/aroon-oscillator.src.js
  js/masters/indicators/aroon.src.js
  samples/stock/indicators/aroon-oscillator/demo.details
  samples/stock/indicators/aroon-oscillator/demo.html
  samples/stock/indicators/aroon-oscillator/demo.js
  samples/stock/indicators/aroon/demo.details
  samples/stock/indicators/aroon/demo.html
  samples/stock/indicators/aroon/demo.js
  samples/unit-tests/indicator-aroon-oscillator/recalculations/demo.details
  samples/unit-tests/indicator-aroon-oscillator/recalculations/demo.html
  samples/unit-tests/indicator-aroon-oscillator/recalculations/demo.js
  samples/unit-tests/indicator-aroon/recalculations/demo.details
  samples/unit-tests/indicator-aroon/recalculations/demo.html
  samples/unit-tests/indicator-aroon/recalculations/demo.js
  test/karma-files.json
Labels: Review

#9172 hs7/stock-tools-keltner-channels
  js/indicators/keltner-channels.src.js
  js/masters/indicators/keltner-channels.src.js
  samples/stock/indicators/keltner-channels/demo.details
  samples/stock/indicators/keltner-channels/demo.html
  samples/stock/indicators/keltner-channels/demo.js
  samples/unit-tests/indicator-keltner-channels/recalculations/demo.details
  samples/unit-tests/indicator-keltner-channels/recalculations/demo.html
  samples/unit-tests/indicator-keltner-channels/recalculations/demo.js
  test/karma-files.json
Labels: Review

#9199 Modified copy-release.js to include gantt.
  copy-release.js
Labels: Highcharts Gantt, Review

#9103 Highstock: Fixed #9102, hardcoded stochastic series name.
  js/indicators/stochastic.src.js
Labels: Review

#9110 doc/fix-types-series
  js/parts/Point.js
Labels: Review

#9168 doc/fix-plugin-options
  tools/jsdoc/plugins/highcharts.jsdoc.js
Labels: Review

#9180 bugfix/9150-heatmap-boost-canvas
  js/modules/boost-canvas.src.js
  samples/highcharts/boost/bubble/demo.html
Labels: Review

#9182 bugfix/9160-overscroll-datalabels-formatting
  js/parts/OrdinalAxis.js
  samples/unit-tests/axis/overscroll/demo.js
Labels: Review

#9189 doc/types-modules-a11y-i18n
  js/modules/a11y-i18n.src.js
Labels: Review

#9190 doc/types-modules-keyboard-navigation
  js/modules/keyboard-navigation.src.js
Labels: Review

#9191 doc/types-modules-screen-reader
  js/modules/screen-reader.src.js
Labels: Review

#9192 doc/types-modules-export-data
  js/modules/export-data.src.js
Labels: Review

#9193 doc/types-modules-series-label
  js/modules/series-label.src.js
Labels: Review

#9195 doc/types-modules-exporting
  js/modules/exporting.src.js
Labels: Review

#9201 Minor updates to Gantt demos.
  samples/gantt/demo/index.htm
  samples/gantt/demo/interactive-gantt/demo.css
  samples/gantt/demo/interactive-gantt/demo.html
  samples/gantt/demo/progress-indicator/demo.css
Labels: Docs, Review

#9205 bugfix/5293-loading-order-more-brokenaxis
  js/parts-more/ColumnRangeSeries.js
Labels: Review

#9208 Fixed 9206, draggable points did not work with dynamic series.
  js/modules/draggable-points.src.js
  samples/unit-tests/dragdrop/dynamic/demo.css
  samples/unit-tests/dragdrop/dynamic/demo.details
  samples/unit-tests/dragdrop/dynamic/demo.html
  samples/unit-tests/dragdrop/dynamic/demo.js
Labels: Bug, Fix suggested, Review

#9137 hc7/test-labelposition-failed
  samples/unit-tests/series-pie/datalabel/demo.js
Labels: Review

#9220 Fixed issue with inverted heat indicators in logistics demo.
  samples/gantt/demo/logistics/demo.js
Labels: Bug, Docs, Highcharts Gantt, Review

#9219 StockTools: Absolute Price Oscillator.
  js/indicators/apo.src.js
  js/masters/indicators/apo.src.js
  samples/stock/indicators/apo/demo.details
  samples/stock/indicators/apo/demo.html
  samples/stock/indicators/apo/demo.js
  samples/unit-tests/indicator-apo/recalculations/demo.details
  samples/unit-tests/indicator-apo/recalculations/demo.html
  samples/unit-tests/indicator-apo/recalculations/demo.js
  test/karma-files.json
Labels: Review

#9254 bugfix/9211-heatmap-inverted-boost-canvas
  js/modules/boost-canvas.src.js
Labels: Review

#9253 docs/annotations-id
  js/modules/annotations.src.js
Labels: Review

#9227 doc/fix-series
  js/parts/Series.js
Labels: Review

#9221 Fixed #9214, distribute themes Sass files.
  gulpfile.js
Labels: Enhancement, Review

#9241 hc7/3d cylinder
  js/masters/modules/cylinder.src.js
  js/modules/cylinder.src.js
  js/parts-3d/Column.js
  js/parts-3d/SVGRenderer.js
  js/parts-3d/VMLRenderer.js
  js/parts/ColumnSeries.js
  samples/highcharts/demo/cylinder/demo.css
  samples/highcharts/demo/cylinder/demo.details
  samples/highcharts/demo/cylinder/demo.html
  samples/highcharts/demo/cylinder/demo.js
  samples/highcharts/demo/cylinder/readme.md
Labels: Review

#9259 Gantt: Added missing API options.
  gulpfile.js
  js/parts-gantt/GanttChart.js
  js/parts/Axis.js
  js/parts/Series.js
Labels: Bug, Docs, Highcharts Gantt, Review

#9261 Fixed issue with a11y module sometimes throwing exception on init.
  js/modules/keyboard-navigation.src.js
Labels: Bug, Review

#9271 Fixed #9156, export data download failed on iOS.
  js/mixins/download-url.js
  js/modules/export-data.src.js
  js/modules/offline-exporting.src.js
Labels: Bug, Review

#9273 Added tracking to default credit link.
  js/parts/Options.js
Labels: Enhancement, Review

#9194 doc/types-modules-offline-exporting
  js/modules/exporting.src.js
  js/modules/offline-exporting.src.js
Labels: Review
