Repository highcharts/highcharts, pull requests merged in 2019-03, with the labels that each got.

#10227 bugfix/10160-stacking-null-points
  js/parts/Series.js
  samples/unit-tests/series/stacking/demo.js
Labels: Review

#10234 tools/fix-cache-broken
  gulpfile.js
Labels: Bug, Priority:High, Review

#10229 hc71/10083-get-member-private
  js/parts/Chart.js
  js/parts/Series.js
Labels: Bug, Docs, Review, TypeScript

#10230 bugfix/10225-histogram-produced-unnecessary-bin
  js/modules/histogram.src.js
  samples/unit-tests/series-histogram/histogram/demo.js
Labels: Review

#10072 feature/networkgraph-link-labels
  js/modules/networkgraph/networkgraph.src.js
  js/parts/DataLabels.js
  js/parts/PieSeries.js
  js/parts/Series.js
  js/parts/SvgRenderer.js
  samples/highcharts/members/renderer-textpath/demo.css
  samples/highcharts/members/renderer-textpath/demo.details
  samples/highcharts/members/renderer-textpath/demo.html
  samples/highcharts/members/renderer-textpath/demo.js
  samples/highcharts/series-bubble/textpath-datalabels/demo.css
  samples/highcharts/series-bubble/textpath-datalabels/demo.details
  samples/highcharts/series-bubble/textpath-datalabels/demo.html
  samples/highcharts/series-bubble/textpath-datalabels/demo.js
  samples/highcharts/series-networkgraph/link-datalabels/demo.css
  samples/highcharts/series-networkgraph/link-datalabels/demo.details
  samples/highcharts/series-networkgraph/link-datalabels/demo.html
  samples/highcharts/series-networkgraph/link-datalabels/demo.js
  samples/highcharts/series-networkgraph/textpath-datalabels/demo.css
  samples/highcharts/series-networkgraph/textpath-datalabels/demo.details
  samples/highcharts/series-networkgraph/textpath-datalabels/demo.html
  samples/highcharts/series-networkgraph/textpath-datalabels/demo.js
  samples/unit-tests/datalabels/members/demo.js
  samples/unit-tests/styled-mode/series-types/demo.html
  samples/unit-tests/styled-mode/series-types/demo.js
Labels: Review

#10140 docs/10058-symboldictionary-customs
  js/parts/SvgRenderer.js
Labels: Review, TypeScript

#10182 hc71/documentation-generators
  gulpfile.js
  package.json
  readme.md
  tools/jsdoc/readme.md
  tools/jsdoc/tmpl/readme.md
Labels: Docs, Enhancement, Review

#10256 Feature/series update keeps points
  js/indicators/indicators.src.js
  js/mixins/derived-series.js
  js/modules/timeline.src.js
  js/parts/AreaSeries.js
  js/parts/ColumnSeries.js
  js/parts/Dynamics.js
  js/parts/Legend.js
  js/parts/Point.js
  js/parts/Series.js
  samples/unit-tests/series-sunburst/datalabels/demo.js
  samples/unit-tests/series/update/demo.html
  samples/unit-tests/series/update/demo.js
Labels: Review

#10153 docs/10149-series-legend-click
  js/parts/Legend.js
  js/parts/PieSeries.js
  js/parts/Series.js
Labels: Bug, Review, TypeScript

#10254 10246-boost-zoom-culling
  js/modules/boost/wgl-renderer.js
Labels: Review

#10244 test/move_issues_tests_hs4.0.3
  copy-release.js
  samples/highcharts/accessibility/art-grants/demo.js
  samples/highcharts/annotations/draggable/demo.js
  samples/highcharts/blog/scatter-regression/demo.js
  samples/highcharts/plotoptions/pie-datalabels-connectorshape-string/demo.js
  samples/highcharts/plotoptions/sankey-inverted/demo.js
  samples/highcharts/sonification/instrument/demo.js
  samples/highcharts/studies/bellcurve-standard-deviation/demo.js
  samples/issues/highcharts-4.0.3/3202-tickinterval-categories/demo.details
  samples/issues/highcharts-4.0.3/3202-tickinterval-categories/demo.html
  samples/issues/highcharts-4.0.3/3202-tickinterval-categories/demo.js
  samples/issues/highcharts-4.0.3/3353-update-to-log-axis/demo.details
  samples/issues/highcharts-4.0.3/3353-update-to-log-axis/demo.html
  samples/issues/highcharts-4.0.3/3353-update-to-log-axis/demo.js
  samples/issues/highcharts-4.0.3/3353-update-to-log-axis/test.js
  samples/issues/highcharts-4.0.3/3359-negative-timezoneoffset-higher-ranks/demo.details
  samples/issues/highcharts-4.0.3/3359-negative-timezoneoffset-higher-ranks/demo.html
  samples/issues/highcharts-4.0.3/3359-negative-timezoneoffset-higher-ranks/demo.js
  samples/issues/highcharts-4.0.3/3363-decimals-in-years/demo.details
  samples/issues/highcharts-4.0.3/3363-decimals-in-years/demo.html
  samples/issues/highcharts-4.0.3/3363-decimals-in-years/demo.js
  samples/issues/highcharts-4.0.3/424-panes-column-tooltip/demo.details
  samples/issues/highcharts-4.0.3/424-panes-column-tooltip/demo.html
  samples/issues/highcharts-4.0.3/424-panes-column-tooltip/demo.js
  samples/issues/highcharts-4.0.3/424-panes-column-tooltip/test.js
  samples/issues/highcharts-4.2.1/4645-shared-tooltip-wrong-points/demo.js
  samples/maps/plotoptions/heatmap-pointplacement/demo.js
  samples/stock/stocktools/advanced-stock-chart/demo.js
  samples/unit-tests/axis/labels/demo.js
  samples/unit-tests/axis/ticks/demo.js
  samples/unit-tests/axis/type-logarithmic/demo.js
  samples/unit-tests/data/csv/demo.js
  samples/unit-tests/gantt/current-date-indicator/demo.js
  samples/unit-tests/gantt/pathfinder/demo.js
  samples/unit-tests/global/timezone/demo.js
  samples/unit-tests/indicator-tema/recalculations/demo.js
  samples/unit-tests/indicator-trix/recalculations/demo.js
  samples/unit-tests/navigator/navigator/demo.js
  samples/unit-tests/series-treemap/options/demo.js
  samples/unit-tests/series-wordcloud/members/demo.js
  samples/unit-tests/tooltip/options-order/demo.js
  samples/unit-tests/tooltip/position/demo.js
  test/karma-conf.js
  test/karma-setup.js
  test/test-controller.js
  test/test-template.js
  tools/compile.js
  tools/eslint-plugin-highcharts/lib/rules/no-newline-in-doclet-link.js
  tools/filesystem.js
  tools/upload.js
  tools/validate-commit-msg.js
Labels: Enhancement, Review

#10223 bugfix/10214-stocktools-class-bindings
  js/annotations/navigationBindings.js
  js/modules/stock-tools-gui.js
Labels: Review

#10008 bugfix/9988-stocktools-popup-scroll
  css/annotations/popup.scss
Labels: Review

#10270 bugfix/10055-annotations-replaced-9e9
  js/annotations/controllable/ControllableLabel.js
  samples/unit-tests/annotations/annotations-cropthreshold/demo.js
Labels: Review

#10205 Fixed #10176, scrollbar error when collapsed treegrid
  js/modules/broken-axis.src.js
Labels: Bug, Highcharts Gantt, Highstock, Review

#10271 tools/tsdoc
  .gitignore
  gulpfile.js
  package.json
  tools/gulptasks/lib/log.js
  tools/gulptasks/lib/time.js
  tools/gulptasks/tsdoc-watch.js
  tools/gulptasks/tsdoc.js
  ts/masters-not-in-use-yet/tsconfig-bullet.json
  ts/modules/bullet.src.ts
  ts/parts/Globals.ts
  ts/parts/Utilities.tsoff
Labels: Review

#10272 bugfix/10232-solidgauge-legend-item
  js/modules/solid-gauge.src.js
  samples/unit-tests/series-solidgauge/solidgauge/demo.js
Labels: Review

#10280 bugfix/10193-wrong-navigator-series-indexes
  js/parts/Dynamics.js
  js/parts/Navigator.js
  samples/unit-tests/navigator/navigator/demo.js
  samples/unit-tests/stock-tools/bindings/demo.js
Labels: Review

#10300 hc71/fix-language
  samples/highcharts/demo/network-graph/demo.js
Labels: Review

#10307 Fixed #10282, overlap larger than smallest circle
  js/mixins/geometry-circles.js
  js/modules/venn.src.js
  samples/unit-tests/series-venn/members/demo.js
Labels: Bug, Highcharts

#10306 hc71/gulp-tasks
  gulpfile.js
  gulpfile.old.js
  js/modules/networkgraph/QuadTree.js
  js/modules/networkgraph/layouts.js
  js/modules/networkgraph/networkgraph.src.js
  js/parts/DataLabels.js
  js/parts/RangeSelector.js
  js/parts/Series.js
  package.json
  readme.md
  test/typescript/modules/item-series.ts
  test/typescript/modules/networkgraph.ts
  test/typescript/tsconfig.json
  tools/gulptasks/common-browserify.js
  tools/gulptasks/common-webpack.js
  tools/gulptasks/common.js
  tools/gulptasks/default.js
  tools/gulptasks/dist-ant.js
  tools/gulptasks/dist-clean.js
  tools/gulptasks/dist-copy.js
  tools/gulptasks/dist-examples.js
  tools/gulptasks/dist-productsjs.js
  tools/gulptasks/dist.js
  tools/gulptasks/jsdoc-classes.js
  tools/gulptasks/jsdoc-clean.js
  tools/gulptasks/jsdoc-dts.js
  tools/gulptasks/jsdoc-namespace.js
  tools/gulptasks/jsdoc-options.js
  tools/gulptasks/jsdoc-server.js
  tools/gulptasks/jsdoc-watch.js
  tools/gulptasks/jsdoc.js
  tools/gulptasks/lib/fs.js
  tools/gulptasks/lib/log.js
  tools/gulptasks/lib/process.js
  tools/gulptasks/lib/string.js
  tools/gulptasks/lint-dts.js
  tools/gulptasks/lint-js.js
  tools/gulptasks/lint-samples.js
  tools/gulptasks/lint-ts.js
  tools/gulptasks/lint.js
  tools/gulptasks/scripts-clean.js
  tools/gulptasks/scripts-compile.js
  tools/gulptasks/scripts-css.js
  tools/gulptasks/scripts-js.js
  tools/gulptasks/scripts-ts.js
  tools/gulptasks/scripts-vendor.js
  tools/gulptasks/scripts-watch.js
  tools/gulptasks/scripts.js
  tools/gulptasks/test.js
  tools/gulptasks/tsdoc-watch.js
  tools/gulptasks/tsdoc.js
  tools/gulptasks/tslint.js
  tools/gulptasks/unsorted/build-modules.js
  tools/gulptasks/unsorted/compare-filesize.js
  tools/gulptasks/unsorted/filesize.js
  tools/gulptasks/unsorted/get-filesizes.js
  tools/gulptasks/unsorted/nightly.js
  tools/gulptasks/unsorted/update-vendor.js
  tools/gulptasks/unsorted/upload-api.js
  tools/gulptasks/update.js
Labels: Enhancement, Priority:High, Review

#10308 Update highcharts-assembler to v1.3.2
  package.json
Labels: Bug, Highcharts, Pre-release, Review

#10310 hc71/bugfix-declarations
  js/parts/Navigator.js
  js/parts/RangeSelector.js
  js/parts/SvgRenderer.js
  js/parts/Utilities.js
Labels: Bug, Docs, Enhancement, Review, TypeScript

#10311 bugfix/10081-update-chart-with-parallelCoordinates
  js/modules/parallel-coordinates.src.js
  samples/unit-tests/chart/parallel-coordinates-updates/demo.js
Labels: Review

#10315 hc71/bugfix-timeline-discrepancy-after-merge
  js/modules/timeline.src.js
Labels: Priority:High, Review

#10317 docs/10305-default-tooltip-followPointer
  js/parts/Options.js
Labels: Review

#10328 hc71/build-tasks
  tools/build.js
  tools/gulptasks/default.js
  tools/gulptasks/scripts-js.js
  tools/gulptasks/scripts-watch.js
Labels: Enhancement, Review

#10331 hc71/restore-old-default-task
  gulpfile.js
  tools/gulptasks/default.js
  tools/gulptasks/unsorted/default.js
Labels: Review

#10335 hc71/restore-old-build-tool
  tools/build.js
Labels: Review

#10337 samples/networkgraph-forces
  samples/highcharts/series-networkgraph/cloth/demo.js
  samples/highcharts/series-networkgraph/cuboids/demo.js
Labels: Review

#10353 bugfix/9992-stocktools-plotLeft-redraw
  js/modules/stock-tools-gui.js
Labels: Review

#10357 bugfix/annotations-bindings-ie
  js/annotations/navigationBindings.js
Labels: Review

#10355 hc71/karma-transpile
  js/parts/Chart.js
  package.json
  samples/unit-tests/axis/datetime-ticks/demo.js
  samples/unit-tests/axis/ticks/demo.js
  samples/unit-tests/chart/container-size/demo.js
  samples/unit-tests/chart/getselectedseries/demo.js
  samples/unit-tests/chart/reflow/demo.js
  samples/unit-tests/chart/renderto/demo.js
  samples/unit-tests/legend/checkbox/demo.js
  samples/unit-tests/legend/legend-hover-dim/demo.js
  samples/unit-tests/series-networkgraph/networkgraph/demo.js
  samples/unit-tests/utils/distribute/demo.js
  test/.eslintrc
  test/karma-conf.js
  test/karma-setup.js
  test/test-template.js
  tools/gulptasks/test.js
  vendor/babel-polyfill-7.2.5.js
Labels: Bug, Enhancement, Review

#10354 bugfix/networkgraph-ie
  js/modules/networkgraph/integrations.js
Labels: Review

#10369 hc71/test-speaking
  package.json
  tools/gulptasks/lib/log.js
  tools/gulptasks/test.js
  tools/speak.vbs
Labels: Enhancement

#10368 hc71/package-updates
  package.json
Labels: Enhancement, Review

#10366 bugfix/10360-button-missing-usehtml
  js/parts/SvgRenderer.js
Labels: Review

#10370 hc71/10344-getsvg-optional-param
  js/modules/exporting.src.js
Labels: Bug, Review, TypeScript

#10371 feature/packedbubble-dataLabels
  js/modules/networkgraph/integrations.js
  js/parts-more/PackedBubbleSeries.js
  samples/highcharts/series-packedbubble/packed-dashboard/demo.js
Labels: Review

#10372 features/annotation-events
  js/annotations/ControlPoint.js
  js/annotations/annotations.src.js
  js/annotations/eventEmitterMixin.js
  js/modules/annotations-legacy.src.js
  samples/unit-tests/annotations/annotations-events/demo.details
  samples/unit-tests/annotations/annotations-events/demo.html
  samples/unit-tests/annotations/annotations-events/demo.js
Labels: Review

#10376 hc71/fix-test-speaking
  tools/gulptasks/lib/log.js
Labels: Review

#10377 feature/9938-navigation-annotation-options
  js/annotations/navigationBindings.js
  js/modules/stock-tools-bindings.js
  samples/stock/stocktools/navigation-annotationOptions/demo.details
  samples/stock/stocktools/navigation-annotationOptions/demo.html
  samples/stock/stocktools/navigation-annotationOptions/demo.js
Labels: Review

#10379 bugfix/10351-ichimoku-destroy-element
  js/indicators/ichimoku-kinko-hyo.src.js
Labels: Review

#10298 feature/inactive-state
  gulpfile.old.js
  js/mixins/nodes.js
  js/modules/dependency-wheel.src.js
  js/modules/item-series.src.js
  js/modules/networkgraph/networkgraph.src.js
  js/modules/sankey.src.js
  js/parts-3d/SVGRenderer.js
  js/parts/ColumnSeries.js
  js/parts/Interaction.js
  js/parts/PieSeries.js
  js/parts/Pointer.js
  js/parts/Series.js
  js/parts/Tooltip.js
  samples/highcharts/series-networkgraph/integration-comparison/demo.js
  samples/unit-tests/point/point/demo.html
  samples/unit-tests/point/point/demo.js
  tools/gulptasks/unsorted/upload-api.js
Labels: Review

#10381 bugfix/10187-setData-old-null-values
  js/parts/Series.js
  samples/unit-tests/series/setdata/demo.js
Labels: Review

#10378 bugfix/8864-connectorcolor-for-individual-point
  js/parts/DataLabels.js
  samples/unit-tests/series-pie/datalabel/demo.js
Labels: Review

#10394 bugfix/10387-stocktools-verticalCounter
  js/modules/stock-tools-bindings.js
Labels: Priority:Blocker, Review

#10388 hc71/fix-annotations-doclets
  js/annotations/annotations.src.js
  js/annotations/navigationBindings.js
Labels: Bug, Review

#10389 hc71/fix-boost-doclets
  js/modules/boost/boost-attach.js
  js/modules/boost/boost-init.js
  js/modules/boost/boost-options.js
  js/modules/boost/boost-overrides.js
  js/modules/boost/boost-utils.js
  js/modules/boost/boost.js
  js/modules/boost/boostable-map.js
  js/modules/boost/boostables.js
  js/modules/boost/named-colors.js
  js/modules/boost/wgl-renderer.js
  js/modules/boost/wgl-shader.js
  js/modules/boost/wgl-vbuffer.js
Labels: Review

#10397 bugfix/10323-timeline-zooming-and-connectors
  js/modules/timeline.src.js
  js/parts/Axis.js
  js/parts/Series.js
  samples/unit-tests/axis/extremes/demo.js
Labels: Pre-release, Review

#10396 bugfix/10392-annotations-each-msie
  js/annotations/popup.js
Labels: Review

#10398 bugfix/10332-HighstockGUI-issue-chart-selected
  js/annotations/eventEmitterMixin.js
Labels: Review

#10399 hc71/readme
  readme.md
Labels: Review

#10384 hc71/fix-networkgraph-doclets
  js/modules/funnel3d.src.js
  js/modules/networkgraph/QuadTree.js
  js/modules/networkgraph/draggable-nodes.js
  js/modules/networkgraph/integrations.js
  js/modules/networkgraph/layouts.js
  js/modules/networkgraph/networkgraph.src.js
  js/modules/pyramid3d.src.js
  tools/gulptasks/jsdoc-namespace.js
Labels: Bug, Docs, Review

#10420 Fix dependencies in build watch
  tools/build.js
Labels: Bug, Review

#10421 sunburst/default-opacity
  js/modules/sunburst.src.js
Labels: Review

#10418 networkgraph/euler-integration
  js/modules/networkgraph/networkgraph.src.js
  samples/unit-tests/point/point/demo.js
Labels: Review

#10419 bugfix/packed-bubble-exporting
  js/parts-more/PackedBubbleSeries.js
Labels: Review

#10422 Fixed #10161, corrected regression in #10185
  js/parts/Axis.js
  samples/unit-tests/axis/members/demo.js
Labels: Bug, Highcharts, Priority:High, Review

#10427 Add showEmpty to defaultOptions in Axis
  js/parts/Axis.js
  samples/unit-tests/series/showempty/demo.js
Labels: Highcharts, Regression, Review

#10424 feature/inactive-series-group
  js/modules/networkgraph/networkgraph.src.js
  js/modules/sankey.src.js
  js/parts/Interaction.js
  js/parts/Series.js
  samples/unit-tests/point/point/demo.js
Labels: Review

#10430 bugfix/10417-exporting-disabled-simulation
  js/modules/networkgraph/layouts.js
  js/parts-more/PackedBubbleSeries.js
Labels: Status:Review

#10431 Minor correction
  docs/dependency-wheel.md
Labels: Status:Review

#10433 A11y: Fixed doclet issues, renamed KeyboardNavigationModule.
  js/modules/accessibility/AccessibilityComponent.js
  js/modules/accessibility/KeyboardNavigation.js
  js/modules/accessibility/KeyboardNavigationHandler.js
  js/modules/accessibility/accessibility.js
  js/modules/accessibility/components/ContainerComponent.js
  js/modules/accessibility/components/InfoRegionComponent.js
  js/modules/accessibility/components/LegendComponent.js
  js/modules/accessibility/components/MenuComponent.js
  js/modules/accessibility/components/RangeSelectorComponent.js
  js/modules/accessibility/components/SeriesComponent.js
  js/modules/accessibility/components/ZoomComponent.js
  samples/highcharts/accessibility/custom-component/demo.js
Labels: Status:Review

#10434 Apply pointPlacement to correct axis
  js/parts/Axis.js
Labels: Product:Highcharts, Regression, Status:Review

#10435 A11y: Fixed warnings from unit test.
  js/modules/accessibility/accessibility.js
  js/parts/Utilities.js
  samples/unit-tests/accessibility/deprecated-options/demo.js
Labels: Status:Review

#10436 networkgraph/stickyTracking
  js/modules/networkgraph/networkgraph.src.js
Labels: Status:Review

#10437 bugfix/inactive-3d
  js/parts/Interaction.js
Labels: Status:Review

#10438 docs/fix-layout-type-conflict
  js/modules/organization.src.js
Labels: Status:Review

#10441 feature/inactive-navigator-series
  js/parts/Navigator.js
Labels: Status:Pending review

#10442 samples/inactive-demo
  js/parts/Series.js
Labels: Status:Pending review

#10445 bugfix/treemap-disabled-inactive
  js/modules/networkgraph/networkgraph.src.js
  js/modules/sankey.src.js
  js/modules/treemap.src.js
  js/parts/PieSeries.js
Labels: Status:Pending review

#10443 regression/networkgraph-inactive-datalabels
  js/parts/Interaction.js
Labels: Status:Pending review

#10446 bugfix/3d-grouping-column-inactive
  js/parts-3d/Column.js
  js/parts-3d/SVGRenderer.js
Labels: Status:Pending review

#10449 Destroy graphic of invisible point in treemap
  js/modules/treemap.src.js
Labels: Priority:Blocker, Product:Highcharts, Status:Pending review, Type:Regression

#10452 bugfix/textpath-safari-firefox
  js/parts/SvgRenderer.js
Labels: Status: Pending review
