Repository highcharts/highcharts, pull requests merged in 2019-01, with the labels that each got.

#9765 bugfix/9693-datagrouping-grouppixelwidth-defaults
  js/parts/DataGrouping.js
  samples/unit-tests/series/datagrouping/demo.js
Labels: Review

#9777 bugfix/9767-annotations-exporting
  js/annotations/annotations.src.js
  js/annotations/controllable/ControllableCircle.js
  js/annotations/controllable/ControllableImage.js
  js/annotations/controllable/ControllableLabel.js
  js/annotations/controllable/ControllablePath.js
  js/annotations/controllable/ControllableRect.js
  js/annotations/controllable/controllableMixin.js
  js/annotations/eventEmitterMixin.js
  js/annotations/navigationBindings.js
  js/annotations/types/CrookedLine.js
  js/annotations/types/Measure.js
Labels: Review

#9781 Fixed wrong path in buildESModules utility script.
  gulpfile.js
Labels: Bug, Review

#9783 bugfix/9235-liveredraw-scrollbar
  js/parts/Scrollbar.js
  samples/unit-tests/scrollbar/events/demo.js
Labels: Review

#9661 feature/new-waterfall-stacking
  js/parts-more/WaterfallSeries.js
  js/parts/Series.js
  samples/highcharts/plotoptions/series-waterfall-with-normal-stacking/demo.details
  samples/highcharts/plotoptions/series-waterfall-with-normal-stacking/demo.html
  samples/highcharts/plotoptions/series-waterfall-with-normal-stacking/demo.js
  samples/highcharts/plotoptions/series-waterfall-with-overlap-stacking/demo.details
  samples/highcharts/plotoptions/series-waterfall-with-overlap-stacking/demo.html
  samples/highcharts/plotoptions/series-waterfall-with-overlap-stacking/demo.js
Labels: Review

#9796 Fixed #9709, missing values when exporting xls in venn.
  js/modules/venn.src.js
Labels: Bug, Review

#9808 bugfix/waterfall-not-linted
  js/parts-more/WaterfallSeries.js
Labels: Review

#9811 Fixed incorrect calculations in getOverlapBetweenCircles
  js/mixins/geometry-circles.js
  samples/unit-tests/series-venn/members/demo.js
Labels: Bug, Review

#9813 bugfix/9758-no-data-module-ignored-boost-points.
  js/modules/no-data-to-display.src.js
  samples/unit-tests/boost/no-data/demo.details
  samples/unit-tests/boost/no-data/demo.html
  samples/unit-tests/boost/no-data/demo.js
Labels: Review

#9825 docs/9116-color-options
  js/indicators/volume-by-price.src.js
  js/modules/annotations-legacy.src.js
  js/modules/bullet.src.js
  js/modules/draggable-points.src.js
  js/modules/exporting.src.js
  js/modules/funnel.src.js
  js/modules/keyboard-navigation.src.js
  js/modules/sankey.src.js
  js/modules/sunburst.src.js
  js/modules/tilemap.src.js
  js/modules/treemap.src.js
  js/modules/xrange.src.js
  js/parts-3d/Chart.js
  js/parts-gantt/Pathfinder.js
  js/parts-map/ColorAxis.js
  js/parts-map/HeatmapSeries.js
  js/parts-map/MapBubbleSeries.js
  js/parts-map/MapLineSeries.js
  js/parts-map/MapSeries.js
  js/parts-more/BoxPlotSeries.js
  js/parts-more/BubbleLegend.js
  js/parts-more/BubbleSeries.js
  js/parts-more/ErrorBarSeries.js
  js/parts-more/GaugeSeries.js
  js/parts-more/WaterfallSeries.js
  js/parts/AreaSeries.js
  js/parts/CandlestickSeries.js
  js/parts/ColumnSeries.js
  js/parts/FlagsSeries.js
  js/parts/Navigator.js
  js/parts/OHLCSeries.js
  js/parts/PieSeries.js
  js/parts/ScatterSeries.js
  js/parts/Scrollbar.js
  js/parts/Series.js
  js/parts/SvgRenderer.js
Labels: Docs, Review

#9833 docs/9832-chart-showloading
  js/parts/Dynamics.js
Labels: Docs, Review

#9834 docs/9741-point
  js/parts/Point.js
Labels: Docs, Review

#9837 docs/9828-position-object
  js/modules/annotations-legacy.src.js
  js/modules/drilldown.src.js
  js/modules/exporting.src.js
  js/modules/no-data-to-display.src.js
  js/parts-gantt/Pathfinder.js
  js/parts-map/Map.js
  js/parts-more/AreaRangeSeries.js
  js/parts/Axis.js
  js/parts/ColumnSeries.js
  js/parts/Options.js
  js/parts/PlotLineOrBand.js
  js/parts/RangeSelector.js
  js/parts/Series.js
  js/parts/SvgRenderer.js
  js/parts/Utilities.js
Labels: Docs, Review

#9831 docs/9176-boost
  js/modules/boost.src.js
Labels: Docs, Review

#9846 Updated highcharts-assembler to v1.1.0.
  package.json
Labels: Enhancement, Review

#9844 Replace binary search with bisect in getDistanceBetweenCirclesByOverlap
  js/modules/venn.src.js
  samples/unit-tests/series-venn/members/demo.js
Labels: Bug, Review

#9853 tools/gulp-scripts-and-update
  gulpfile.js
Labels: Enhancement, Review

#9845 docs/9826-callback-functions
  js/modules/draggable-points.src.js
  js/modules/exporting.src.js
  js/parts-gantt/GanttChart.js
  js/parts-map/Map.js
  js/parts/Chart.js
  js/parts/Options.js
  js/parts/Series.js
  js/parts/StockChart.js
  js/parts/Utilities.js
Labels: Docs, Review

#9857 bugfix/9847-stocktools-gui-and-popup-did-not-support-touch-events.
  js/annotations/popup.js
  js/modules/stock-tools-gui.js
  samples/unit-tests/stock-tools/popup/demo.css
  samples/unit-tests/stock-tools/popup/demo.details
  samples/unit-tests/stock-tools/popup/demo.html
  samples/unit-tests/stock-tools/popup/demo.js
Labels: Review

#9858 tools/package-update
  package.json
Labels: Review

#9859 docs/9852-tooltip-positioner
  js/parts/Options.js
  js/parts/Tooltip.js
Labels: Docs, Review

#9860 bugfix/8544/turbothreshold-keys-datagrouping
  js/parts/Series.js
  samples/unit-tests/series/datagrouping/demo.js
Labels: Review

#9865 bugfix/9770/datagrouping-and-datalabels
  js/parts/Series.js
  samples/unit-tests/series/datagrouping/demo.js
Labels: Review

#9879 bugfix/9869-9727-xrange-tooltip-position
  js/modules/xrange.src.js
Labels: Review

#9873 tools/improve-update-tasks
  gulpfile.js
  package.json
Labels: Enhancement, Review

#9872 bugfix/9841-tickamount-cropped-extremes
  js/parts/Axis.js
Labels: Review

#9885 tools/dependencies-update
  package.json
Labels: Review

#9890 docs/typescript-series-type
  js/parts/Options.js
  js/parts/Series.js
  tools/jsdoc/plugins/highcharts.jsdoc.js
Labels: Docs, Review

#9924 Updated html-classes for new plugin
  changelog/generate-changelog-html.js
Labels: Enhancement, Priority:Blocker, Review

#9926 tools/gulp-v4
  gulpfile.js
  package.json
Labels: Enhancement, Priority:Blocker, Review

#9919 tsc
  gulpfile.js
  index.d.ts
  js/.eslintrc
  js/modules/bullet.src.js
  js/modules/timeline.src.js
  js/parts/Globals.js
  js/parts/Options.js
  package.json
  test/typescript/index.d.ts
  test/typescript/indicators/mfi.ts
  test/typescript/tsconfig.json
  test/typescript/tslint.json
  tools/gulptasks/lib/process.js
  tools/gulptasks/lib/string.js
  tools/gulptasks/tsc.js
  tools/gulptasks/tslint.js
  ts/masters-not-in-use-yet/tsconfig-bullet.json
  ts/masters-not-in-use-yet/tsconfig.json
  ts/modules/bullet.src.ts
  ts/parts/Globals.ts
  ts/tsconfig.json
  tsconfig.json
Labels: Enhancement, Review, TypeScript

#9923 bugfix/9898-indicators-update-line-series
  js/modules/stock-tools-bindings.js
Labels: Review

#9918 bugfix/9913-useOhlcData-datagrouping
  js/indicators/indicators.src.js
  samples/unit-tests/indicators/use-ohlc-data/demo.details
  samples/unit-tests/indicators/use-ohlc-data/demo.html
  samples/unit-tests/indicators/use-ohlc-data/demo.js
Labels: Review

#9937 tools/fix-gulp-watch
  gulpfile.js
Labels: Priority:High, Review

#9939 Fixed issue with indicators in logistics demo
  samples/highcharts/studies/logistics/demo.js
Labels: Bug, Review

#9954 Fixed Windows path compatibility in scripts task
  gulpfile.js
Labels: Bug, Review

#9942 bugfix/9915-price-indicator-error-when-no-points
  js/modules/price-indicator.src.js
  samples/unit-tests/indicator-price-indicator/recalculations/demo.details
  samples/unit-tests/indicator-price-indicator/recalculations/demo.html
  samples/unit-tests/indicator-price-indicator/recalculations/demo.js
Labels: Review

#9952 docs/chart-type-option
  js/parts/Options.js
Labels: Docs, Review

#9951 docs/dateformats-type
  js/parts/Time.js
Labels: Review, TypeScript

#9959 Addition ff40197, accidental rename of parameter
  gulpfile.js
Labels: Bug, Review

#9953 Fixed draggable points capturing click events
  js/modules/draggable-points.src.js
Labels: Bug, Review

#9965 bugfix/9823-point-drop-event
  js/modules/draggable-points.src.js
Labels: Review

#9979 docs/9961-doubled-shape-param
  js/parts/SvgRenderer.js
Labels: Review

#9981 bugfix/9928-mislabeled-xaxis
  js/parts/DataGrouping.js
  samples/unit-tests/series/datagrouping/demo.js
Labels: Review

#9982 bugfix/8430-navigator-data-reset
  js/parts/Navigator.js
  samples/unit-tests/navigator/navigator/demo.js
Labels: Review

#9983 bugfix/9493-indicators-update-with-data-cropped
  js/indicators/indicators.src.js
  js/parts/Series.js
  samples/unit-tests/indicator-sma/recalculations/demo.html
  samples/unit-tests/indicator-sma/recalculations/demo.js
Labels: Review

#9987 Bugfix/venn position first
  js/modules/venn.src.js
  samples/unit-tests/series-venn/members/demo.js
Labels: Bug, Review

#9989 Fixed #9978, horizontal scrollbar on RTL charts with a11y module.
  js/modules/keyboard-navigation.src.js
  js/modules/screen-reader.src.js
Labels: Bug, Review

#9993 bugfix/8623-demo-donut-remove-yaxis
  samples/highcharts/demo/pie-donut/demo.js
Labels: Review

#9995 bugfix/8660-drag-panes-resize-overlap
  js/modules/drag-panes.src.js
  samples/unit-tests/drag-panes/pointer-interactions/demo.js
Labels: Review

#10011 Feature/networkgraph barnes hut approx
  js/modules/networkgraph/QuadTree.js
  js/modules/networkgraph/integrations.js
  js/modules/networkgraph/layouts.js
  js/modules/networkgraph/networkgraph.src.js
  samples/highcharts/series-networkgraph/cloth/demo.js
  samples/highcharts/series-networkgraph/cuboids/demo.js
  samples/highcharts/series-networkgraph/ragdoll/demo.js
Labels: Review
