Repository highcharts/highcharts, pull requests merged in 2019-08, with the labels that each got.

#11539 Remove duplicate theme files
  js/masters/themes/avocado.js
  js/masters/themes/sunset.js
Labels: Product: Highcharts

#11531 Bugfix/11493 split tooltip
  js/parts/Pointer.js
  samples/unit-tests/pointer/members/demo.js
  ts/parts/Pointer.ts
Labels: Changelog: Bugfix, Product: Highcharts

#11613 Fixed #11513, arearange failed when started with NaN
  js/parts-more/AreaRangeSeries.js
  js/parts/Series.js
  samples/unit-tests/series-arearange/arearange/demo.js
  ts/parts-more/AreaRangeSeries.ts
  ts/parts/Series.ts
Labels: Changelog: Bugfix

#11619 docs/11555-axis-options
  js/parts/Axis.js
  ts/parts/Axis.ts
Labels: Status: In progress

#11623 ts/modules-bellcurve
  .eslintignore
  js/modules/bellcurve.src.js
  ts/modules/bellcurve.src.ts
Labels: Status: Inbox

#11640 bugfix/11632-networkgraph-node-marker-cut
  js/modules/networkgraph/layouts.js
  js/modules/networkgraph/networkgraph.src.js
  samples/unit-tests/series-networkgraph/networkgraph/demo.js
  ts/modules/networkgraph/layouts.ts
  ts/modules/networkgraph/networkgraph.src.ts
Labels: Changelog: Bugfix

#11683 tools/ci-revert-launcher
  package.json
Labels: Priority: Blocker

#11685 Added high contrast themes.
  js/masters/themes/high-contrast-dark.src.js
  js/masters/themes/high-contrast-light.src.js
  js/themes/high-contrast-dark.js
  js/themes/high-contrast-light.js
  samples/highcharts/accessibility/high-contrast-theme-dark/demo.css
  samples/highcharts/accessibility/high-contrast-theme-dark/demo.details
  samples/highcharts/accessibility/high-contrast-theme-dark/demo.html
  samples/highcharts/accessibility/high-contrast-theme-dark/demo.js
  samples/highcharts/accessibility/high-contrast-theme-light/demo.css
  samples/highcharts/accessibility/high-contrast-theme-light/demo.details
  samples/highcharts/accessibility/high-contrast-theme-light/demo.html
  samples/highcharts/accessibility/high-contrast-theme-light/demo.js
Labels: Changelog: Feature, Product: Highcharts

#11707 ts/modules-export-data
  .eslintignore
  js/modules/data.src.js
  js/modules/export-data.src.js
  js/modules/oldie-polyfills.src.js
  js/parts-gantt/TreeGrid.js
  js/parts-map/GeoJSON.js
  js/parts-more/WaterfallSeries.js
  js/parts/Utilities.js
  ts/modules/data.src.ts
  ts/modules/export-data.src.ts
  ts/modules/oldie-polyfills.src.ts
  ts/parts-gantt/TreeGrid.ts
  ts/parts-map/GeoJSON.ts
  ts/parts-more/WaterfallSeries.ts
  ts/parts/Globals.ts
  ts/parts/Utilities.ts
Labels: Status: Inbox

#11730 docs/11715-fix-point-options
  js/parts/Interaction.js
  js/parts/Point.js
  js/parts/Series.js
  ts/parts/Interaction.ts
  ts/parts/Point.ts
  ts/parts/Series.ts
Labels: Status: Inbox

#11719 bugfix/11609-reflow-destroy
  js/parts/Chart.js
  ts/parts/Chart.ts
Labels: Changelog: Bugfix

#11720 bugfix/11717-layout-es6-module
  js/modules/networkgraph/layouts.js
  ts/modules/networkgraph/layouts.ts
Labels: Changelog: Bugfix

#11741 docs/11497-dateformats-demo
  samples/highcharts/global/dateformats/demo.js
Labels: Changelog: Bugfix

#11743 bugfix/10962-misaligned-stack-labels
  js/modules/variwide.src.js
  js/parts/Series.js
  js/parts/Stacking.js
  samples/highcharts/yaxis/stacklabels-enabled-variwide/demo.details
  samples/highcharts/yaxis/stacklabels-enabled-variwide/demo.html
  samples/highcharts/yaxis/stacklabels-enabled-variwide/demo.js
  samples/unit-tests/axis/variwide-stacklabels/demo.details
  samples/unit-tests/axis/variwide-stacklabels/demo.html
  samples/unit-tests/axis/variwide-stacklabels/demo.js
  ts/parts/Series.ts
  ts/parts/Stacking.ts
Labels: Changelog: Bugfix

#11735 Fixed #11702, error in organization chart with certain relations
  js/modules/organization.src.js
  js/modules/sankey.src.js
  samples/unit-tests/series-organization/organization/demo.details
  samples/unit-tests/series-organization/organization/demo.html
  samples/unit-tests/series-organization/organization/demo.js
  ts/modules/sankey.src.ts
Labels: Changelog: Bugfix

#11765 bugfix/es6-globals
  js/parts/Globals.js
  ts/parts/Globals.ts
Labels: Status: Inbox

#11766 docs/fix-legacy-redirect
  package.json
  tools/eslint-plugin-highcharts/node_modules/requireindex/package.json
Labels: Status: Inbox

#11777 docs/fix-axis-events-context
  js/parts/Axis.js
  ts/parts/Axis.ts
Labels: Status: Inbox

#11780 docs/fix-pointoptionsobject-repeat
  js/modules/accessibility/accessibility.js
  js/modules/draggable-points.src.js
  js/modules/xrange.src.js
  js/parts-map/HeatmapSeries.js
  js/parts-more/AreaRangeSeries.js
  js/parts/ColumnSeries.js
  js/parts/DataLabels.js
  js/parts/Legend.js
  js/parts/PieSeries.js
  ts/modules/draggable-points.src.ts
  ts/modules/xrange.src.ts
  ts/parts-map/HeatmapSeries.ts
  ts/parts-more/AreaRangeSeries.ts
  ts/parts/ColumnSeries.ts
  ts/parts/DataLabels.ts
  ts/parts/Legend.ts
  ts/parts/PieSeries.ts
Labels: Status: Inbox

#11784 docs/fix-series-typescript-comment
  js/parts/Series.js
  ts/parts/Series.ts
Labels: Status: Inbox

#11790 docs/seriesoptionstype
  js/parts/Series.js
  package.json
  ts/parts/Series.ts
Labels: Status: Inbox

#11791 bugfix/11448-bubble-legend-gridlines
  js/parts-more/BubbleLegend.js
  samples/unit-tests/bubble-legend/layout/demo.html
  samples/unit-tests/bubble-legend/layout/demo.js
  ts/parts-more/BubbleLegend.ts
Labels: Changelog: Bugfix, Product: Highmaps

#11789 Fixed #11783, issue with `tooltip.outside` and `chart.styledMode`
  js/parts/Html.js
  js/parts/Tooltip.js
  samples/unit-tests/tooltip/outside/demo.details
  samples/unit-tests/tooltip/outside/demo.html
  samples/unit-tests/tooltip/outside/demo.js
  ts/parts/Html.ts
  ts/parts/Tooltip.ts
Labels: Changelog: Bugfix

#10757 enhancement/5526-pie-zero-data-refactored
  js/parts/PieSeries.js
  js/parts/SvgRenderer.js
  samples/highcharts/plotoptions/pie-emptyseries/demo.details
  samples/highcharts/plotoptions/pie-emptyseries/demo.html
  samples/highcharts/plotoptions/pie-emptyseries/demo.js
  samples/unit-tests/axis/crosshairs/demo.js
  samples/unit-tests/axis/ticks/demo.js
  samples/unit-tests/series-bubble/marker/demo.js
  samples/unit-tests/series-pie/pie/demo.js
  samples/unit-tests/series/stacking/demo.js
  tools/build.js
  ts/parts/PieSeries.ts
  ts/parts/Series.ts
  ts/parts/SvgRenderer.ts
Labels: Changelog: Feature, Status: Inbox

#11798 ts/modules-histogram
  .eslintignore
  js/modules/histogram.src.js
  ts/modules/histogram.src.ts
Labels: Status: Inbox

#11813 ts/ts36
  js/parts/Globals.js
  package.json
  ts/.eslintrc
  ts/README.md
  ts/modules/funnel3d.src.ts
  ts/parts/Globals.ts
  ts/typedoc.json
Labels: Status: Inbox

#11806 ts/modules-item-series
  .eslintignore
  js/modules/item-series.src.js
  ts/modules/item-series.src.ts
Labels: Status: Inbox
