Repository highcharts/highcharts, pull requests merged in 2019-02, with the labels that each got.

#10017 bugix/10001-stocktools-missing-tooltip
  js/modules/stock-tools-gui.js
Labels: Review

#10028 Fixed #10006, wrong intersection position in venn
  js/modules/venn.src.js
  samples/unit-tests/series-venn/members/demo.js
Labels: Bug, Highcharts, Review

#10023 docs/9177-boost-blending
  js/modules/boost.src.js
Labels: Review

#10022 dosc/bugfix
  package.json
Labels: Docs, Review

#10045 Fixed #10043, corrected setRootNode doclets
  js/modules/treemap.src.js
Labels: Docs, Review

#10051 bugfix/3417/plotLine-label-wrong-textAnchor
  js/parts/SvgRenderer.js
  samples/unit-tests/svgrenderer/label/demo.js
Labels: Review

#10053 bugfix/7773-compare-settings
  js/indicators/indicators.src.js
  samples/stock/plotoptions/series-comparetomain/demo.details
  samples/stock/plotoptions/series-comparetomain/demo.html
  samples/stock/plotoptions/series-comparetomain/demo.js
  samples/unit-tests/series/compare/demo.html
  samples/unit-tests/series/compare/demo.js
Labels: Review

#10080 bugfix/7067/enable-navigator-by-update
  js/parts/Dynamics.js
  js/parts/Navigator.js
  samples/unit-tests/navigator/navigator/demo.js
Labels: Review

#10086 bugfix/7773-docs-demo-addition
  js/indicators/indicators.src.js
  samples/stock/plotoptions/series-comparetomain/demo.js
Labels: Review

#10085 docs/9836-literal-type-names
  js/annotations/types/Measure.js
  js/indicators/supertrend.src.js
  js/modules/annotations-legacy.src.js
  js/modules/drilldown.src.js
  js/modules/exporting.src.js
  js/modules/no-data-to-display.src.js
  js/parts-gantt/Pathfinder.js
  js/parts-map/Map.js
  js/parts-more/AreaRangeSeries.js
  js/parts-more/BoxPlotSeries.js
  js/parts-more/WaterfallSeries.js
  js/parts/Axis.js
  js/parts/ColumnSeries.js
  js/parts/Options.js
  js/parts/PlotLineOrBand.js
  js/parts/RangeSelector.js
  js/parts/Series.js
  js/parts/SvgRenderer.js
  js/parts/Utilities.js
Labels: Docs, Review, TypeScript

#10091 bugfix/9962-boost-outside-extremes-points
  js/modules/boost.src.js
Labels: Review

#10098 docs/9763-theme-declarations
  js/themes/avocado.js
  js/themes/dark-blue.js
  js/themes/dark-green.js
  js/themes/dark-unica.js
  js/themes/gray.js
  js/themes/grid-light.js
  js/themes/grid.js
  js/themes/sand-signika.js
  js/themes/skies.js
  js/themes/sunset.js
  test/typescript/themes/avocado.ts
  test/typescript/themes/dark-blue.ts
  test/typescript/themes/dark-green.ts
  test/typescript/themes/dark-unica.ts
  test/typescript/themes/gray.ts
  test/typescript/themes/grid-light.ts
  test/typescript/themes/grid.ts
  test/typescript/themes/sand-signika.ts
  test/typescript/themes/skies.ts
  test/typescript/themes/sunset.ts
  test/typescript/tsconfig.json
Labels: Review

#10103 Include navigator in gantt
  js/masters/modules/gantt.src.js
  js/parts/Navigator.js
  js/parts/OrdinalAxis.js
  js/parts/RangeSelector.js
  js/parts/Scrollbar.js
  js/parts/StockChart.js
  samples/gantt/demo/index.htm
  samples/gantt/demo/with-navigation/demo.css
  samples/gantt/demo/with-navigation/demo.details
  samples/gantt/demo/with-navigation/demo.html
  samples/gantt/demo/with-navigation/demo.js
Labels: Feature Request, Highcharts Gantt, Priority:High, Review

#10094 docs/9829-data-labels-interface
  gulpfile.js
  js/modules/sankey.src.js
  js/modules/xrange.src.js
  js/parts-map/HeatmapSeries.js
  js/parts-more/AreaRangeSeries.js
  js/parts/BarSeries.js
  js/parts/ColumnSeries.js
  js/parts/DataLabels.js
  js/parts/PieSeries.js
  js/parts/Series.js
  js/parts/Utilities.js
Labels: Review, TypeScript

#10100 bugfix/9994/navigator-wrong-min-with-ordinal
  js/parts/Navigator.js
  samples/unit-tests/navigator/navigator/demo.js
Labels: Review

#10108 bugfix/10101-bubblelegend-with-map-module
  js/parts-more/BubbleLegend.js
  samples/unit-tests/bubble-legend/layout/demo.html
  samples/unit-tests/bubble-legend/layout/demo.js
Labels: Review

#10116 docs/10077-formatter-callback-context
  js/modules/sankey.src.js
  js/modules/timeline.src.js
  js/parts/Axis.js
  js/parts/Stacking.js
Labels: Docs, Review, TypeScript

#10122 docs/sankey-node-links
  js/modules/sankey.src.js
Labels: Docs, Review, TypeScript

#10121 docs/10079-lang-accessibility-options
  js/modules/a11y-i18n.src.js
Labels: Bug, Docs, Review, TypeScript

#10119 docs/more-datalabels-fixes
  js/indicators/pivot-points.src.js
  js/indicators/volume-by-price.src.js
  js/modules/funnel.src.js
  js/modules/networkgraph/networkgraph.src.js
  js/modules/sunburst.src.js
  js/modules/treemap.src.js
  js/modules/venn.src.js
  js/parts-gantt/GanttSeries.js
  js/parts-map/MapPointSeries.js
  js/parts-map/MapSeries.js
  js/parts-more/BubbleSeries.js
  js/parts-more/GaugeSeries.js
  js/parts-more/WaterfallSeries.js
  js/parts/Navigator.js
Labels: Docs, Review, TypeScript

#10130 tools/gulp-lint-fix
  gulpfile.js
Labels: Review

#10124 docs/10076-series-states
  js/parts-map/MapSeries.js
  js/parts/Series.js
Labels: Bug, Docs, Review, TypeScript

#10126 docs/10078-resetZoomButton-theme
  js/parts/Options.js
Labels: Docs, Review, TypeScript

#10142 Fixed #10031, Pie - dataLabels with useHTML: true, were generated with negative width.
  js/parts/DataLabels.js
  samples/unit-tests/series-pie/datalabel/demo.js
Labels: Review

#10148 docs/fix-interface-implements
  js/modules/draggable-points.src.js
  js/parts/Series.js
  tools/jsdoc/plugins/highcharts.namespace.js
Labels: Bug, Docs, Review, TypeScript

#10156 docs/10150-navigator-series-data
  js/parts/Navigator.js
  test/typescript/highstock.ts
Labels: Bug, Docs, Review, TypeScript

#10155 docs/10147-tooltip-formatter-context
  js/parts/Options.js
Labels: Bug, Review, TypeScript

#10158 Setup for writing Highcharts documentation
  docs/Readme.md
Labels: Review

#10157 bugfix/10137-data-labels-justifying
  js/parts/DataLabels.js
  samples/unit-tests/datalabels/justifying/demo.details
  samples/unit-tests/datalabels/justifying/demo.html
  samples/unit-tests/datalabels/justifying/demo.js
Labels: Review

#10143 bugfix/1289/multiple-panes-zoom
  js/parts/Interaction.js
  samples/unit-tests/chart/zoomtype/demo.js
Labels: Review

#10164 docs/10125-chart-properties
  js/parts/Chart.js
  js/parts/Interaction.js
  js/parts/Pointer.js
Labels: Docs, Review

#10170 bugfix/10144-stocktools-remove-flags
  js/modules/stock-tools-bindings.js
  samples/unit-tests/stock-tools/bindings/demo.js
Labels: Review

#10165 docs/api-docs-update
  package.json
Labels: Docs, Review

#10186 boost/refactoring
  js/masters/modules/boost.src.js
  js/modules/boost.src.js
  js/modules/boost/boost-attach.js
  js/modules/boost/boost-init.js
  js/modules/boost/boost-options.js
  js/modules/boost/boost-overrides.js
  js/modules/boost/boost-utils.js
  js/modules/boost/boost.js
  js/modules/boost/boostable-map.js
  js/modules/boost/boostables.js
  js/modules/boost/named-colors.js
  js/modules/boost/wgl-renderer.js
  js/modules/boost/wgl-shader.js
  js/modules/boost/wgl-vbuffer.js
Labels: Review

#10198 bugfix/10192-sma-volume-pane
  js/modules/stock-tools-bindings.js
Labels: Review

#10203 bugfix/10201-stocktools-stochastic-pane
  js/modules/stock-tools-bindings.js
Labels: Review

#10204 bugfix/10196-stocktools-default-indicators-params
  js/annotations/popup.js
Labels: Review

#10219 tools/jsdoc-watch
  gulpfile.js
Labels: Bug, Review

#10209 bugfix/10183-stocktools-elliot-missing-line
  js/modules/stock-tools-bindings.js
Labels: Review

#10224 docs/10189-axis-autorotation-type
  js/parts/Axis.js
Labels: Review, TypeScript

#10215 bugfix/10071-series-hover-dim
  js/parts/Interaction.js
  samples/unit-tests/legend/legend-hover-dim/demo.css
  samples/unit-tests/legend/legend-hover-dim/demo.details
  samples/unit-tests/legend/legend-hover-dim/demo.html
  samples/unit-tests/legend/legend-hover-dim/demo.js
Labels: Review

#10217 bugfix/9917-pane-update
  js/parts-more/Pane.js
  samples/unit-tests/pane/pane-update/demo.js
Labels: Review
