Repository highcharts/highcharts, pull requests merged in 2019-12, with the labels that each got.

#12470 bugfix/12445-solid-gauge-update-border
  js/modules/solid-gauge.src.js
  samples/unit-tests/series-solidgauge/solidgauge/demo.js
  ts/modules/solid-gauge.src.ts
Labels: Changelog: Bugfix

#12560 Fixed #12438, reset zoom not working with a11y module on mobile.
  js/modules/accessibility/AccessibilityComponent.js
  ts/modules/accessibility/AccessibilityComponent.ts
Labels: Changelog: Bugfix

#12564 Fixed #12549, disabling keyboard nav still adds container tabindex.
  js/modules/accessibility/KeyboardNavigation.js
  samples/unit-tests/accessibility/accessibility-options/demo.js
  ts/modules/accessibility/KeyboardNavigation.ts
Labels: Changelog: Bugfix

#12541 Added 1 as a default value to zIndex, in no data to display
  js/modules/no-data-to-display.src.js
  samples/unit-tests/no-data/members/demo.details
  samples/unit-tests/no-data/members/demo.html
  samples/unit-tests/no-data/members/demo.js
  ts/modules/no-data-to-display.src.ts
Labels: Changelog: Bugfix, Product: Highcharts

#12567 bugfix/12543-bubble-wrong-extremes
  js/parts-more/BubbleSeries.js
  samples/unit-tests/series-bubble/minmaxsize/demo.html
  samples/unit-tests/series-bubble/minmaxsize/demo.js
  ts/parts-more/BubbleSeries.ts
Labels: Changelog: Bugfix

#12552 Fixed #12462, replacing slash in filename
  js/modules/exporting.src.js
  samples/unit-tests/exporting/filename/demo.js
  ts/modules/exporting.src.ts
Labels: Changelog: Bugfix

#12570 bugfix/7255-print-cancel-safari
  js/modules/exporting.src.js
  ts/modules/exporting.src.ts
Labels: Changelog: Bugfix

#12568 Fix zoom issues in treemap
  js/modules/treemap.src.js
  ts/modules/treemap.src.ts
Labels: Changelog: Bugfix, Product: Highcharts

#12563 Fixed missing drag markers when loading highcharts-3d module.
  js/modules/draggable-points.src.js
  ts/modules/draggable-points.src.ts
Labels: Changelog: Bugfix, Product: Highcharts

#12600 Fixed a typo in the docs for bubble-legend.
  docs/chart-concepts/bubble-legend.md
Labels: Product: Docs, Status: Pending review

#12632 bugfix/12573-navigator-jumps
  js/parts/Navigator.js
  samples/unit-tests/navigator/navigator/demo.js
  ts/parts/Navigator.ts
Labels: Changelog: Bugfix, Product: Highstock

#12652 Fixed #12648, datetime axis ticks wrong in Indian time
  js/parts/Time.js
  samples/unit-tests/time/timeticks/demo.js
  ts/parts/Time.ts
Labels: Changelog: Bugfix

#12643 bugfix/12627-overlapping-legend-drilldown
  js/parts/Point.js
  samples/unit-tests/drilldown/pie/demo.js
  ts/parts/Point.ts
Labels: Changelog: Bugfix
