Repository highcharts/highcharts, pull requests merged in 2019-10, with the labels that each got.

#12104 bugfix/11716-annotations-basic-popup
  js/annotations/annotations.src.js
  samples/unit-tests/annotations/annotations-events/demo.js
Labels: Changelog: Bugfix, Product: Highstock

#12115 Fixed #7559, error when updating a waterfall with first value as sum
  js/parts-more/WaterfallSeries.js
  samples/unit-tests/series-waterfall/issum/demo.js
  ts/parts-more/WaterfallSeries.ts
Labels: Changelog: Bugfix

#12121 ts/readme-readonly-parameter
  ts/README.md
Labels: Status: Inbox

#12095 Feature/a11y heading config
  js/modules/accessibility/AccessibilityComponent.js
  js/modules/accessibility/KeyboardNavigation.js
  js/modules/accessibility/a11y-i18n.js
  js/modules/accessibility/accessibility.js
  js/modules/accessibility/components/ContainerComponent.js
  js/modules/accessibility/components/InfoRegionComponent.js
  js/modules/accessibility/components/InfoRegionsComponent.js
  js/modules/accessibility/components/LegendComponent.js
  js/modules/accessibility/components/MenuComponent.js
  js/modules/accessibility/components/RangeSelectorComponent.js
  js/modules/accessibility/components/SeriesComponent.js
  js/modules/accessibility/components/ZoomComponent.js
  js/modules/accessibility/deprecatedOptions.js
  js/modules/accessibility/langOptions.js
  js/modules/accessibility/options.js
  js/modules/accessibility/utilities.js
  samples/unit-tests/accessibility/accessibility-options/demo.js
  samples/unit-tests/accessibility/accessible-highmaps/demo.js
  samples/unit-tests/accessibility/accessible-highstock/demo.js
  samples/unit-tests/accessibility/datetime/demo.js
  samples/unit-tests/accessibility/deprecated-options/demo.js
  samples/unit-tests/accessibility/descriptions-added/demo.js
  samples/unit-tests/accessibility/forced-markers/demo.js
  samples/unit-tests/accessibility/i18n/demo.js
  samples/unit-tests/series-timeline/datetime-axis/demo.js
  samples/unit-tests/svgrenderer/styled-mode/demo.js
Labels: Changelog: Feature, Type: Pre-release

#12093 ts/indicators-williamsr
  .eslintignore
  js/indicators/williams-r.src.js
  js/mixins/reduce-array.js
  ts/indicators/williams-r.src.ts
  ts/mixins/reduce-array.ts
Labels: Status: Inbox

#12138 Fixed #12090, a11y module breaks legend navigation.
  js/modules/accessibility/components/LegendComponent.js
  js/parts/Legend.js
  ts/parts/Legend.ts
Labels: Changelog: Bugfix, Type: Pre-release

#12144 bugfix/12099-panning-datagrouping
  js/parts/DataGrouping.js
  samples/unit-tests/series/datagrouping/demo.js
  ts/parts/DataGrouping.ts
Labels: Changelog: Bugfix, Product: Highstock

#12153 ts/indicator-price-envelopes
  .eslintignore
  js/indicators/price-envelopes.src.js
  ts/indicators/price-envelopes.src.ts
Labels: Status: Inbox

#12143 ts/indicators-momentum
  .eslintignore
  js/indicators/momentum.src.js
  ts/indicators/momentum.src.ts
Labels: Status: Inbox

#12150 bugfix/11650-highcharts-tooltip-header-class
  docs/chart-design-and-style/style-by-css.md
  js/parts/Tooltip.js
  ts/parts/Tooltip.ts
Labels: Changelog: Bugfix

#12199 bugfix/11738-treemap-update
  js/modules/treemap.src.js
  samples/unit-tests/series-treemap/update/demo.details
  samples/unit-tests/series-treemap/update/demo.html
  samples/unit-tests/series-treemap/update/demo.js
  ts/modules/treemap.src.ts
Labels: Changelog: Bugfix

#12200 bugfix/11426-datagrouping-arearange
  js/parts/DataGrouping.js
  ts/parts/DataGrouping.ts
Labels: Changelog: Bugfix, Product: Highstock

#12201 bugfix/11644-tilemap-coloraxis-extremes
  js/modules/tilemap.src.js
  samples/unit-tests/series-tilemap/coloraxis/demo.details
  samples/unit-tests/series-tilemap/coloraxis/demo.html
  samples/unit-tests/series-tilemap/coloraxis/demo.js
  ts/modules/tilemap.src.ts
Labels: Changelog: Bugfix

#12220 bugfix/12215-vwap-stocktools
  js/modules/stock-tools-bindings.js
Labels: Changelog: Bugfix, Product: Highstock

#12243 Fixed issue with fill property on pattern fills
  js/modules/pattern-fill.src.js
  samples/unit-tests/color/pattern-fill/demo.js
  ts/modules/pattern-fill.src.ts
Labels: Changelog: Bugfix

#12246 Fixed #12161, legend textDecoration not working on IE11 with a11y.
  js/modules/accessibility/AccessibilityComponent.js
Labels: Changelog: Bugfix

#12252 Fixed menu navigation compatibility issues.
  js/modules/accessibility/components/MenuComponent.js
  js/modules/exporting.src.js
  ts/modules/exporting.src.ts
Labels: Changelog: Bugfix

#12255 bugfix/12231-coloraxis-highcharts-not-defined
  js/parts-map/ColorAxis.js
  ts/parts-map/ColorAxis.ts
Labels: Changelog: Bugfix, Product: Highmaps

#12253 docs/error-17
  js/parts/Chart.js
  js/parts/Dynamics.js
  js/parts/Utilities.js
  ts/parts/Chart.ts
  ts/parts/Dynamics.ts
  ts/parts/Utilities.ts
Labels: Status: Inbox

#12270 bugfix/12266-zones-with-no-data
  js/indicators/macd.src.js
  samples/unit-tests/indicator-macd/recalculations/demo.js
  ts/indicators/macd.src.ts
Labels: Changelog: Bugfix, Product: Highstock, Status: Pending reply

#12281 Fixed #12222, empty pie series showing `lineWidth` after hover
  js/parts/PieSeries.js
  ts/parts/PieSeries.ts
Labels: Changelog: Bugfix
