Repository highcharts/highcharts, pull requests merged in 2019-07, with the labels that each got.

#11216 docs/jsdoc-internal-options
  js/parts/Axis.js
  js/parts/Navigator.js
  js/parts/Options.js
  js/parts/Series.js
  ts/parts/Axis.ts
  ts/parts/Navigator.ts
  ts/parts/Options.ts
  ts/parts/Series.ts
Labels: Status: Backlog

#11226 ts/utilities-pick
  js/parts/Axis.js
  js/parts/RangeSelector.js
  js/parts/Series.js
  js/parts/Utilities.js
  package.json
  ts/.eslintrc
  ts/parts/Axis.ts
  ts/parts/Navigator.ts
  ts/parts/Point.ts
  ts/parts/Pointer.ts
  ts/parts/RangeSelector.ts
  ts/parts/Series.ts
  ts/parts/SvgRenderer.ts
  ts/parts/Tick.ts
  ts/parts/Tooltip.ts
  ts/parts/Utilities.ts
Labels: Status: Backlog

#11218 bugfix/11211-networkgraph-node-update
  js/modules/networkgraph/networkgraph.src.js
  samples/unit-tests/series-networkgraph/networkgraph/demo.js
Labels: Changelog: Bugfix

#11220 bugfix/11212-networkgraph-selected-state
  js/mixins/nodes.js
  samples/unit-tests/series-networkgraph/networkgraph/demo.js
Labels: Changelog: Bugfix

#11230 ts/mixins-centeredseries
  .eslintignore
  js/mixins/centered-series.js
  ts/mixins/centered-series.ts
  ts/parts/Globals.ts
Labels: Priority: Blocker

#11234 Export isString in parts/Utilities.js
  js/annotations/annotations.src.js
  js/annotations/controllable/controllableMixin.js
  js/annotations/popup.js
  js/masters/highcharts.src.js
  js/modules/sunburst.src.js
  js/modules/treemap.src.js
  js/modules/venn.src.js
  js/parts-gantt/TreeGrid.js
  js/parts/Axis.js
  js/parts/Chart.js
  js/parts/Dynamics.js
  js/parts/Series.js
  js/parts/StockChart.js
  js/parts/SvgRenderer.js
  js/parts/Tooltip.js
  js/parts/Utilities.js
  ts/parts/Axis.ts
  ts/parts/Chart.ts
  ts/parts/Dynamics.ts
  ts/parts/Series.ts
  ts/parts/SvgRenderer.ts
  ts/parts/Tooltip.ts
  ts/parts/Utilities.ts
Labels: Product: Highcharts

#11240 Fixed #11229, avoid negative width and height in heatmap shapes
  js/parts-map/HeatmapSeries.js
Labels: Changelog: Bugfix, Product: Highcharts

#11247 Export pInt in parts/Utilities.js
  js/masters/highcharts.src.js
  js/modules/oldie.src.js
  js/modules/solid-gauge.src.js
  js/parts-more/BubbleSeries.js
  js/parts-more/GaugeSeries.js
  js/parts-more/RadialAxis.js
  js/parts/Chart.js
  js/parts/Color.js
  js/parts/Html.js
  js/parts/Legend.js
  js/parts/RangeSelector.js
  js/parts/SvgRenderer.js
  js/parts/Utilities.js
  ts/modules/oldie.src.ts
  ts/parts/Chart.ts
  ts/parts/Color.ts
  ts/parts/Html.ts
  ts/parts/Legend.ts
  ts/parts/RangeSelector.ts
  ts/parts/SvgRenderer.ts
  ts/parts/Utilities.ts
Labels: Product: Highcharts

#10981 Install highcharts-utils
  package.json
Labels: Product: Docs

#11257 bugfix/11239-heatmap-animate-colors
  js/parts-map/HeatmapSeries.js
  samples/unit-tests/series-heatmap/animation/demo.details
  samples/unit-tests/series-heatmap/animation/demo.html
  samples/unit-tests/series-heatmap/animation/demo.js
Labels: Changelog: Bugfix

#11259 bugfix/10896-series-labels-color-stylemode
  js/modules/series-label.src.js
Labels: Changelog: Bugfix, Product: Highcharts

#11292 bugfix/11169-loading-lang-undefined
  samples/unit-tests/loading/lang/demo.details
  samples/unit-tests/loading/lang/demo.html
  samples/unit-tests/loading/lang/demo.js
  ts/parts/Dynamics.ts
Labels: Changelog: Bugfix

#11304 Export splat in parts/Utilities.js
  js/annotations/annotations.src.js
  js/annotations/controllable/controllableMixin.js
  js/annotations/controllable/markerMixin.js
  js/indicators/indicators.src.js
  js/masters/highcharts.src.js
  js/modules/data.src.js
  js/modules/parallel-coordinates.src.js
  js/modules/sonification/Timeline.js
  js/modules/sonification/chartSonify.js
  js/parts-3d/Axis.js
  js/parts-gantt/GanttChart.js
  js/parts-gantt/GanttSeries.js
  js/parts-gantt/Pathfinder.js
  js/parts-map/MapSeries.js
  js/parts-more/Pane.js
  js/parts-more/Polar.js
  js/parts/Axis.js
  js/parts/Chart.js
  js/parts/DataLabels.js
  js/parts/Dynamics.js
  js/parts/Navigator.js
  js/parts/Pointer.js
  js/parts/RangeSelector.js
  js/parts/Responsive.js
  js/parts/Series.js
  js/parts/StockChart.js
  js/parts/SvgRenderer.js
  js/parts/Time.js
  js/parts/Tooltip.js
  js/parts/Utilities.js
  ts/parts/Axis.ts
  ts/parts/Chart.ts
  ts/parts/DataLabels.ts
  ts/parts/Dynamics.ts
  ts/parts/Navigator.ts
  ts/parts/Pointer.ts
  ts/parts/RangeSelector.ts
  ts/parts/Responsive.ts
  ts/parts/Series.ts
  ts/parts/SvgRenderer.ts
  ts/parts/Time.ts
  ts/parts/Tooltip.ts
  ts/parts/Utilities.ts
Labels: Product: Highcharts

#11335 bugfix/10285-dragdrop-logarithmic
  js/modules/draggable-points.src.js
  samples/unit-tests/dragdrop/dynamic/demo.js
Labels: Changelog: Bugfix

#11333 Fixed #10564, issue with tabbing to legend without chart height set.
  js/modules/accessibility/AccessibilityComponent.js
  samples/highcharts/accessibility/accessible-keyboardnav/demo.css
Labels: Changelog: Bugfix, Product: Highcharts

#11349 feature/10648-annotations-remove-integer
  js/annotations/annotations.src.js
  samples/unit-tests/annotations/annotations-dynamic/demo.js
Labels: Changelog: Feature

#11341 bugfix/8735-boost-gapsize
  js/modules/boost/wgl-renderer.js
Labels: Changelog: Bugfix

#11361 Fixed #10561, issue with legend click on IE11 with a11y module.
  js/modules/accessibility/AccessibilityComponent.js
Labels: Changelog: Bugfix

#11362 Made chart credits accessible to screen readers.
  js/modules/accessibility/a11y-i18n.js
  js/modules/accessibility/components/ContainerComponent.js
Labels: Changelog: Feature

#11367 bugfix/11351-gapsize-datagrouping
  js/modules/broken-axis.src.js
  js/parts/Series.js
  samples/unit-tests/series/datagrouping-with-gapsize/demo.js
  ts/parts/Series.ts
Labels: Changelog: Bugfix, Product: Highstock

#11374 bugfix/10745-data-update-datagrouping
  js/parts/Series.js
  samples/unit-tests/series/datagrouping/demo.js
  ts/parts/Series.ts
Labels: Changelog: Bugfix, Product: Highstock

#11383 bugfix/11191-datagrouping-average-correctfloat
  js/parts/DataGrouping.js
  samples/unit-tests/series/datagrouping/demo.js
  ts/parts/DataGrouping.ts
Labels: Changelog: Bugfix, Product: Highstock

#11387 bugfix/11156/boost-draggable-group-points
  js/modules/draggable-points.src.js
  samples/unit-tests/dragdrop/dynamic/demo.html
  samples/unit-tests/dragdrop/dynamic/demo.js
Labels: Changelog: Bugfix

#11385 bugfix/10980-stocktools-single-item
  js/modules/stock-tools-gui.js
  samples/unit-tests/stock-tools/gui/demo.details
  samples/unit-tests/stock-tools/gui/demo.html
  samples/unit-tests/stock-tools/gui/demo.js
Labels: Changelog: Bugfix, Product: Highstock

#11375 Fixed #11340, issue with big data export to CSV and XLS.
  js/modules/export-data.src.js
Labels: Changelog: Bugfix

#11404 Fixed #10542, show hide series from screen readers.
  js/modules/accessibility/components/SeriesComponent.js
  samples/unit-tests/accessibility/series-showhide/demo.details
  samples/unit-tests/accessibility/series-showhide/demo.html
  samples/unit-tests/accessibility/series-showhide/demo.js
Labels: Changelog: Bugfix, Product: Highcharts

#11409 bugfix/11174-annotation-measure-size-fullscreen
  js/annotations/types/Measure.js
Labels: Changelog: Bugfix, Product: Highstock

#11419 bugfix/11415-annotation-popup-overflow
  css/annotations/popup.scss
Labels: Changelog: Bugfix, Product: Highstock

#11416 feature/11175-rect-annotation-value-coords
  js/annotations/navigationBindings.js
Labels: Changelog: Bugfix

#11449 docs/11381-axis-zoom-enabled
  samples/highcharts/xaxis/zoomenabled/demo.details
  samples/highcharts/xaxis/zoomenabled/demo.html
  samples/highcharts/xaxis/zoomenabled/demo.js
  ts/parts/Axis.ts
Labels: Changelog: Bugfix, Product: Docs

#11450 bugfix/11386-exporting-missing-css-filters
  js/modules/exporting.src.js
  samples/unit-tests/exporting/styled-mode/demo.css
  samples/unit-tests/exporting/styled-mode/demo.details
  samples/unit-tests/exporting/styled-mode/demo.html
  samples/unit-tests/exporting/styled-mode/demo.js
Labels: Changelog: Bugfix

#11472 Exported isObject in parts/Utilities.js
  js/annotations/controllable/controllableMixin.js
  js/annotations/navigationBindings.js
  js/annotations/popup.js
  js/masters/highcharts.src.js
  js/mixins/tree-series.js
  js/modules/export-data.src.js
  js/modules/exporting.src.js
  js/modules/oldie.src.js
  js/modules/sankey.src.js
  js/modules/sunburst.src.js
  js/modules/treemap.src.js
  js/modules/venn.src.js
  js/modules/wordcloud.src.js
  js/modules/xrange.src.js
  js/parts-gantt/GridAxis.js
  js/parts-gantt/TreeGrid.js
  js/parts/Chart.js
  js/parts/Dynamics.js
  js/parts/Interaction.js
  js/parts/Point.js
  js/parts/Pointer.js
  js/parts/Responsive.js
  js/parts/SvgRenderer.js
  js/parts/Time.js
  js/parts/Utilities.js
  ts/mixins/tree-series.ts
  ts/modules/oldie.src.ts
  ts/parts/Chart.ts
  ts/parts/Dynamics.ts
  ts/parts/Interaction.ts
  ts/parts/Point.ts
  ts/parts/Pointer.ts
  ts/parts/Responsive.ts
  ts/parts/SvgRenderer.ts
  ts/parts/Time.ts
  ts/parts/Utilities.ts
Labels: Product: Highcharts

#11473 Export isDOMElement in parts/Utilities.js
  js/masters/highcharts.src.js
  js/parts/Utilities.js
  ts/parts/Utilities.ts
Labels: Product: Highcharts

#11478 Export isClass in parts/Utilities.js
  js/masters/highcharts.src.js
  js/parts/Utilities.js
  ts/parts/Utilities.ts
Labels: Product: Highcharts

#11446 bugfix/svgrenderer-symbol-demo
  samples/unit-tests/svgrenderer/symbol/demo.js
Labels: Status: Pending review

#11399 docs/10582-nodes-dataLabels-docs
  js/modules/dependency-wheel.src.js
  js/modules/networkgraph/networkgraph.src.js
  js/modules/organization.src.js
  js/modules/sankey.src.js
Labels: Product: Docs

#11508 Add missing TS changes in JS
  js/modules/networkgraph/networkgraph.src.js
  js/parts/Axis.js
  ts/modules/networkgraph/networkgraph.src.ts
Labels: Product: Highcharts

#11518 Fixed #11505, gauge crashed when stacking config present
  js/parts/Stacking.js
  samples/unit-tests/series-gauge/addpoint/demo.js
  ts/parts/Stacking.ts
Labels: Changelog: Bugfix
