Repository highcharts/highcharts, pull requests merged in 2019-06, with the labels that each got.

#10837 bugfix/10245-datalabels-disappear-low-columns
  js/parts/DataLabels.js
  samples/unit-tests/datalabels/crop/demo.details
  samples/unit-tests/datalabels/crop/demo.html
  samples/unit-tests/datalabels/crop/demo.js
Labels: Changelog: Bugfix

#10858 Addition #10816, columns regression
  js/parts-gantt/GridAxis.js
Labels: Priority: Blocker, Product: Highcharts Gantt

#10857 docs/axis-doclet
  js/parts/Axis.js
  ts/parts/Axis.ts
Labels: Status: Backlog

#10866 Improve grid axis isOuterAxis
  js/parts-gantt/GridAxis.js
  samples/unit-tests/gantt/grid-axis-stock/demo.js
  samples/unit-tests/gantt/grid-axis/demo.js
Labels: Product: Highcharts Gantt

#10879 Fixed #10826, add missing jquery
  samples/highcharts/demo/treemap-large-dataset/demo.html
Labels: Changelog: Bugfix, Priority: High, Product: Docs

#10891 Fixed #10865, networkgraph marker image errors.
  js/modules/networkgraph/networkgraph.src.js
Labels: Changelog: Bugfix, Product: Highcharts

#10895 Fixed #10788, wrong docs for stock tools.
  docs/stock/stock-tools.md
  samples/stock/stocktools/basic-gui/demo.details
  samples/stock/stocktools/basic-gui/demo.html
  samples/stock/stocktools/basic-gui/demo.js
  samples/stock/stocktools/basic-gui/test-notes.md
  samples/stock/stocktools/custom-popup/demo.css
  samples/stock/stocktools/custom-popup/demo.details
  samples/stock/stocktools/custom-popup/demo.html
  samples/stock/stocktools/custom-popup/demo.js
  samples/stock/stocktools/custom-popup/test-notes.md
Labels: Product: Docs

#10898 Fixed #10524, skip tspan when nowrap
  js/modules/wordcloud.src.js
  js/parts/SvgRenderer.js
  samples/unit-tests/svgrenderer/text/demo.js
  ts/parts/SvgRenderer.ts
Labels: Changelog: Bugfix, Product: Highcharts

#10900 bugfix/10323-hidden-connectors-after-zoom
  js/modules/timeline.src.js
  samples/unit-tests/series-timeline/datetime-axis/demo.js
Labels: Changelog: Bugfix, Product: Highcharts

#10897 Fixed #10870, regression with updating marker symbol
  js/parts/Dynamics.js
  samples/unit-tests/series/update/demo.js
  ts/parts/Dynamics.ts
Labels: Changelog: Bugfix

#10908 bugfix/10874-tooltip-for-points-that-were-null
  js/parts/Point.js
  samples/unit-tests/tooltip/nullformat/demo.js
  ts/parts/Point.ts
Labels: Changelog: Bugfix

#10885 Fixed #10708, remove use of findIndex
  js/modules/sankey.src.js
Labels: Changelog: Bugfix, Product: Highcharts

#10907 bugfix/10670-heatmap-zones-coloraxis
  js/parts/ColumnSeries.js
  samples/unit-tests/coloraxis/zones/demo.details
  samples/unit-tests/coloraxis/zones/demo.html
  samples/unit-tests/coloraxis/zones/demo.js
Labels: Changelog: Bugfix

#10893 Fixed issue with the data module failing on CORS resources
  js/mixins/ajax.js
  samples/highcharts/demo/treemap-large-dataset/demo.html
  samples/highcharts/demo/treemap-large-dataset/demo.js
Labels: Changelog: Bugfix

#10927 Fixed #9099, getSelectedPoints with series select event
  js/parts/Chart.js
  js/parts/Interaction.js
  samples/unit-tests/point/point-select/demo.details
  samples/unit-tests/point/point-select/demo.html
  samples/unit-tests/point/point-select/demo.js
  ts/parts/Chart.ts
Labels: Changelog: Bugfix

#10938 bugfix/10932-minpadding-datagrouping
  js/parts/DataGrouping.js
  samples/unit-tests/series/datagrouping/demo.js
Labels: Changelog: Bugfix, Product: Highstock

#10947 Fixed #10909, subpixel precision caused unwanted space in area
  js/parts/AreaSeries.js
Labels: Changelog: Bugfix

#10949 Update jsdoc to v3.6.2
  package.json
Labels: Product: Docs, Status: In progress

#10953 Fixed #10952, plot background in scrollable plot area
  js/parts/ScrollablePlotArea.js
Labels: Changelog: Bugfix

#10946 bugfix/10943-dts-for-newer-files
  test/typescript-lint/tsconfig.json
  tools/gulptasks/jsdoc-dts.js
  tools/gulptasks/lib/gulp.js
Labels: Changelog: Bugfix, Status: Backlog

#10948 Fixed #10791, disable halo in venn
  js/modules/venn.src.js
  js/parts/Series.js
  samples/unit-tests/series-venn/integration/demo.js
Labels: Changelog: Bugfix, Product: Highcharts

#10950 bugfix/10827-tema-name-collision
  js/indicators/dema.src.js
  js/indicators/tema.src.js
  js/indicators/trix.src.js
Labels: Changelog: Bugfix, Product: Highstock, Status: Pending review

#10954 Fixed #10699, enable inactiveOtherPoints in venn
  js/modules/venn.src.js
Labels: Changelog: Bugfix, Product: Highcharts

#10956 Addition #10878
  js/modules/venn.src.js
  samples/unit-tests/series-venn/members/demo.js
Labels: Product: Highcharts

#10958 Fixed #10671, responsive spacing caused crash
  js/parts/Dynamics.js
  samples/unit-tests/responsive/responsive/demo.js
  ts/parts/Dynamics.ts
Labels: Changelog: Bugfix

#10959 tools/update-declaration-generator
  package.json
Labels: Status: Backlog

#10964 ts/interaction
  .eslintignore
  js/parts/DataGrouping.js
  js/parts/DateTimeAxis.js
  js/parts/Interaction.js
  js/parts/Legend.js
  js/parts/Point.js
  js/parts/Pointer.js
  js/parts/SvgRenderer.js
  js/parts/Time.js
  ts/parts/Axis.ts
  ts/parts/DataGrouping.ts
  ts/parts/DataLabels.ts
  ts/parts/DateTimeAxis.ts
  ts/parts/Dynamics.ts
  ts/parts/Globals.ts
  ts/parts/Interaction.ts
  ts/parts/Legend.ts
  ts/parts/Navigator.ts
  ts/parts/OrdinalAxis.ts
  ts/parts/Point.ts
  ts/parts/Pointer.ts
  ts/parts/SvgRenderer.ts
  ts/parts/Time.ts
Labels: Priority: High, Status: Backlog

#10966 Fixed #10942, gantt progress is not redrawn after toggle
  js/modules/xrange.src.js
  js/parts/SvgRenderer.js
  samples/unit-tests/series-xrange/xrange/demo.js
  ts/parts/SvgRenderer.ts
Labels: Changelog: Bugfix, Product: Highcharts Gantt

#10965 Fixed #10804, ignore internal series in pathfinder
  js/parts-gantt/Pathfinder.js
Labels: Changelog: Bugfix, Product: Highcharts Gantt

#10967 Fixed #10717, xAxis.reversed should reverse partialFill on xrange
  js/modules/xrange.src.js
  samples/unit-tests/series-xrange/xrange/demo.js
Labels: Changelog: Bugfix

#10973 Fix scripts-watch windows compatibility
  tools/gulptasks/scripts-watch.js
Labels: Product: Docs

#10992 ts/stacking
  .eslintignore
  js/parts/RangeSelector.js
  js/parts/Series.js
  js/parts/Stacking.js
  ts/parts/Axis.ts
  ts/parts/Globals.ts
  ts/parts/Navigator.ts
  ts/parts/RangeSelector.ts
  ts/parts/Scrollbar.ts
  ts/parts/Stacking.ts
Labels: Status: Backlog

#11007 ts/module-oldie
  .eslintignore
  js/modules/oldie.src.js
  js/parts/Color.js
  js/parts/Pointer.js
  js/parts/SvgRenderer.js
  ts/modules/oldie.src.ts
  ts/parts/Color.ts
  ts/parts/Globals.ts
  ts/parts/Html.ts
  ts/parts/Pointer.ts
  ts/parts/SvgRenderer.ts
  ts/parts/Tick.ts
  ts/parts/TouchPointer.ts
Labels: Status: Backlog

#10970 bugfix/10961-annotations-mousedown-block
  js/annotations/eventEmitterMixin.js
  samples/unit-tests/annotations/annotations-events/demo.js
Labels: Changelog: Bugfix

#10972 Fixed #10887, treegrid update regression
  js/parts-gantt/TreeGrid.js
  samples/unit-tests/gantt/treegrid/demo.js
Labels: Changelog: Bugfix, Priority: Blocker, Product: Highcharts Gantt

#10977 tools/fix-error-handling
  tools/gulptasks/lib/gulp.js
  tools/gulptasks/lib/process.js
  tools/gulptasks/scripts.js
Labels: Status: Backlog

#10979 tools/update-documentation-generators
  package.json
Labels: Status: Backlog

#10997 Bugfix/pattern fill issues
  js/modules/pattern-fill.src.js
Labels: Changelog: Bugfix, Product: Highcharts

#10999 docs/10991-fix-doclets-issues
  js/modules/item-series.src.js
  js/modules/solid-gauge.src.js
  js/parts/PlotLineOrBand.js
  ts/parts/PlotLineOrBand.ts
Labels: Status: Backlog

#11002 docs/10983-networgraph-weight
  js/modules/networkgraph/networkgraph.src.js
Labels: Product: Docs

#11004 bugfix/10993-points-visible-outside-of-extremes
  js/modules/timeline.src.js
  samples/unit-tests/series-timeline/datetime-axis/demo.js
Labels: Changelog: Bugfix

#11008 tools/fix-single-test
  tools/gulptasks/test.js
Labels: Status: Inbox

#10969 docs/10821-navigator-series-type
  js/parts/Navigator.js
  ts/parts/Navigator.ts
Labels: Status: Backlog

#11013 bugfix/10984-networkgraph-data-module
  js/modules/data.src.js
  js/modules/networkgraph/networkgraph.src.js
  js/modules/sankey.src.js
  samples/unit-tests/data/general/demo.html
  samples/unit-tests/data/general/demo.js
Labels: Changelog: Bugfix

#11014 bugfix/10941-stacking-null-x
  js/parts/Series.js
  samples/unit-tests/series/stacking/demo.js
Labels: Changelog: Bugfix

#11054 Fixed #10522, series.colors was ignored in sunburst
  js/modules/sunburst.src.js
  samples/unit-tests/series-sunburst/colors/demo.js
Labels: Changelog: Bugfix, Product: Highcharts

#11003 docs/missing-boost-module-description
  js/masters/modules/boost.src.js
Labels: Product: Docs, Status: In progress

#11084 Fixed #10518, single orientation in Wordcloud crash render
  js/modules/wordcloud.src.js
  samples/unit-tests/series-wordcloud/members/demo.js
Labels: Changelog: Bugfix, Product: Highcharts

#11086 Fixed #11005, X axis line width affects clipping
  js/parts/StockChart.js
  samples/unit-tests/series-column/axis-line-width/demo.js
Labels: Changelog: Bugfix, Product: Highstock

#11082 Fixed #10498, wrong chart width if parent had transform style
  js/parts/Utilities.js
  samples/unit-tests/chart/container-size/demo.js
  ts/parts/Utilities.ts
Labels: Changelog: Bugfix

#11096 docs/10982-custom-point-properties
  js/modules/accessibility/accessibility.js
  js/modules/draggable-points.src.js
  js/modules/xrange.src.js
  js/parts-map/HeatmapSeries.js
  js/parts-more/AreaRangeSeries.js
  js/parts/DataLabels.js
  js/parts/Interaction.js
  js/parts/Legend.js
  js/parts/PieSeries.js
  js/parts/Point.js
  js/parts/Series.js
  package.json
  test/typescript/highcharts-more/highcharts-more.ts
  test/typescript/highcharts/highcharts.ts
  ts/parts/DataLabels.ts
  ts/parts/Globals.ts
  ts/parts/Interaction.ts
  ts/parts/Legend.ts
  ts/parts/Point.ts
Labels: Status: Backlog

#11098 docs/11093-indicators-popup-id
  js/modules/stock-tools-bindings.js
Labels: Product: Docs

#11104 Fixed #10861, a regression with series events and update
  js/parts/Dynamics.js
  js/parts/Series.js
  samples/unit-tests/chart/chart-update-series/demo.js
  samples/unit-tests/series/update/demo.js
  ts/parts/Dynamics.ts
Labels: Changelog: Bugfix

#11107 Added Windows High Contrast Mode capabilities. Closes #7424.
  js/modules/accessibility/accessibility.js
  js/modules/accessibility/high-contrast-mode.js
  js/modules/accessibility/high-contrast-theme.js
  js/modules/accessibility/options.js
Labels: Changelog: Feature, Product: Highcharts

#11110 bugfix/10597-update-after-drilldown
  js/modules/drilldown.src.js
  samples/unit-tests/drilldown/drilldown-general/demo.js
Labels: Changelog: Bugfix

#11122 Added accessibility.pointNavigationThreshold. Also closes #10876.
  js/modules/accessibility/components/SeriesComponent.js
  js/modules/accessibility/options.js
  samples/unit-tests/accessibility/accessibility-options/demo.js
  samples/unit-tests/accessibility/accessible-highstock/demo.js
  samples/unit-tests/accessibility/forced-markers/demo.js
Labels: Changelog: Feature, Product: Highcharts

#11139 bugfix/11124-networkgraph-draggable-delay
  js/modules/networkgraph/draggable-nodes.js
Labels: Changelog: Bugfix

#11168 docs/11155-corrected-PackedBubble-documentation
  js/parts-more/PackedBubbleSeries.js
Labels: Product: Docs

#11120 Improved keyboard navigation for inverted charts.
  js/modules/accessibility/components/SeriesComponent.js
  samples/highcharts/accessibility/accessible-bar/demo.css
  samples/highcharts/accessibility/accessible-bar/demo.details
  samples/highcharts/accessibility/accessible-bar/demo.html
  samples/highcharts/accessibility/accessible-bar/demo.js
Labels: Changelog: Feature, Product: Highcharts

#11186 ts/series
  .eslintignore
  js/modules/accessibility/accessibility.js
  js/modules/xrange.src.js
  js/parts/Axis.js
  js/parts/Chart.js
  js/parts/Color.js
  js/parts/DataGrouping.js
  js/parts/DataLabels.js
  js/parts/DateTimeAxis.js
  js/parts/Dynamics.js
  js/parts/Interaction.js
  js/parts/Legend.js
  js/parts/Navigator.js
  js/parts/OrdinalAxis.js
  js/parts/Point.js
  js/parts/Pointer.js
  js/parts/Series.js
  js/parts/Stacking.js
  js/parts/Time.js
  js/parts/Tooltip.js
  js/parts/Utilities.js
  test/typescript/highcharts-more/highcharts-more.ts
  test/typescript/modules/data.ts
  ts/modules/oldie.src.ts
  ts/parts-map/ColorAxis.ts
  ts/parts/Axis.ts
  ts/parts/Chart.ts
  ts/parts/Color.ts
  ts/parts/DataGrouping.ts
  ts/parts/DataLabels.ts
  ts/parts/DateTimeAxis.ts
  ts/parts/Dynamics.ts
  ts/parts/Globals.ts
  ts/parts/Interaction.ts
  ts/parts/Legend.ts
  ts/parts/Navigator.ts
  ts/parts/Options.ts
  ts/parts/OrdinalAxis.ts
  ts/parts/PlotLineOrBand.ts
  ts/parts/Point.ts
  ts/parts/Pointer.ts
  ts/parts/RangeSelector.ts
  ts/parts/Scrollbar.ts
  ts/parts/Series.ts
  ts/parts/Stacking.ts
  ts/parts/Tick.ts
  ts/parts/Time.ts
  ts/parts/Tooltip.ts
  ts/parts/Utilities.ts
Labels: Status: Inbox

#11152 bugfix/11146-ts-TooltipFormatterCallbackFunction
  js/parts/Tooltip.js
  ts/parts/Tooltip.ts
Labels: Product: TypeScript, Status: In progress, Status: Pending reply

#11194 bugfix/7882-api-docs-search
  package.json
Labels: Status: Backlog

#11178 Fixed #11101, a regression causing crash on responsive chart
  js/parts/Responsive.js
  samples/unit-tests/responsive/responsive/demo.js
  ts/parts/Responsive.ts
Labels: Changelog: Bugfix

#11203 bugfix/11176-networkgraph-clear-data
  js/modules/networkgraph/networkgraph.src.js
  samples/unit-tests/series-networkgraph/networkgraph/demo.js
Labels: Changelog: Bugfix

#11208 bugfix/11109-oldie-polyfills
  ts/modules/oldie-polyfills.src.ts
  ts/parts/Series.ts
Labels: Status: Backlog
