Repository highcharts/highcharts, pull requests merged in 2019-09, with the labels that each got.

#11819 docs/fix-gauge-types
  js/parts-more/GaugeSeries.js
  ts/parts-more/GaugeSeries.ts
Labels: Status: Inbox

#11821 Fixed #11792, error in organization chart with one point
  js/modules/sankey.src.js
  samples/unit-tests/series-organization/organization/demo.js
  ts/modules/sankey.src.ts
Labels: Changelog: Bugfix

#11822 ts/modules-map-parser
  .eslintignore
  js/modules/map-parser.src.js
  ts/modules/map-parser.src.ts
Labels: Status: Inbox

#11880 docs/11695-typo-responsive-callback-function
  js/parts/Responsive.js
  ts/parts/Responsive.ts
Labels: Product: Docs

#11877 ts/modules-offline-exporting
  .eslintignore
  js/modules/offline-exporting.src.js
  js/modules/oldie-polyfills.src.js
  js/modules/oldie.src.js
  js/modules/sankey.src.js
  ts/modules/offline-exporting.src.ts
  ts/modules/oldie-polyfills.src.ts
  ts/modules/oldie.src.ts
  ts/modules/sankey.src.ts
Labels: Status: Inbox

#11881 Ts/indicators accumulation distribution
  .eslintignore
  js/indicators/accumulation-distribution.src.js
  ts/indicators/accumulation-distribution.src.ts
Labels: Status: Inbox

#11882 tools/eslint-updates
  package.json
Labels: Status: Inbox

#11888 Tools: Testing to increase Win.Chrome+ Mac.Firefox browsercount
  .circleci/config.yml
Labels: Priority: High, Status: Inbox

#11890 ts/modules-organization
  .eslintignore
  js/modules/organization.src.js
  ts/modules/organization.src.ts
  ts/modules/sankey.src.ts
  ts/parts/Globals.ts
Labels: Status: Inbox

#11894 docs/fix-option-navigation
  js/annotations/navigationBindings.js
  package.json
Labels: Status: Inbox

#11835 ts/indicators-wma
  .eslintignore
  js/indicators/wma.src.js
  ts/indicators/wma.src.ts
Labels: Status: Inbox

#11892 ts/modules-overlapping-datalabels
  .eslintignore
  js/modules/overlapping-datalabels.src.js
  ts/modules/overlapping-datalabels.src.ts
  ts/parts/Chart.ts
  ts/parts/Globals.ts
Labels: Status: Inbox

#11908 docs/11866-navigator-options-type
  js/parts/Navigator.js
  ts/parts/Navigator.ts
Labels: Status: Inbox

#11916 ts/fix-merge
  ts/indicators/wma.src.ts
Labels: Priority: Blocker, Status: Backlog

#11901 bugfix/11897-panes-polar-and-pie
  js/parts-more/Polar.js
  samples/unit-tests/chart/polar/demo.js
  ts/parts-more/Polar.ts
Labels: Changelog: Bugfix

#11910 ts/modules-pareto
  .eslintignore
  js/modules/pareto.src.js
  ts/modules/pareto.src.ts
Labels: Status: Inbox

#11914 ts/modules-series-label
  .eslintignore
  js/modules/series-label.src.js
  ts/modules/series-label.src.ts
  ts/parts/Globals.ts
  ts/parts/Interaction.ts
  ts/parts/SvgRenderer.ts
Labels: Status: Inbox

#11923 delete/modules-map
  js/modules/map.src.js
Labels: Status: Inbox

#11933 tools/dependencies-update
  package.json
Labels: Status: Inbox

#11932 docs/readme-test-templates
  samples/readme.md
  test/readme.md
Labels: Status: Inbox

#11950 bugfix/11924-addcoloraxis-in-highmpas
  js/parts/Dynamics.js
  samples/unit-tests/coloraxis/coloraxis-update/demo.html
  samples/unit-tests/coloraxis/coloraxis-update/demo.js
  ts/parts/Dynamics.ts
Labels: Changelog: Bugfix, Product: Highmaps

#11965 bugfix/11100-3d-column-animation
  js/modules/cylinder.src.js
  js/modules/funnel3d.src.js
  js/parts-3d/Column.js
  js/parts/ColumnSeries.js
  js/parts/Point.js
  samples/unit-tests/3d/column-animation/demo.css
  samples/unit-tests/3d/column-animation/demo.details
  samples/unit-tests/3d/column-animation/demo.html
  samples/unit-tests/3d/column-animation/demo.js
  ts/modules/cylinder.src.ts
  ts/modules/funnel3d.src.ts
  ts/parts-3d/Column.ts
  ts/parts/ColumnSeries.ts
  ts/parts/Point.ts
Labels: Changelog: Bugfix

#11694 Export syncTimeout in parts/Utilities.ts
  js/masters/highcharts.src.js
  js/modules/drilldown.src.js
  js/modules/series-label.src.js
  js/parts/Axis.js
  js/parts/Chart.js
  js/parts/Series.js
  js/parts/Tooltip.js
  js/parts/Utilities.js
  ts/modules/drilldown.src.ts
  ts/modules/series-label.src.ts
  ts/parts/Axis.ts
  ts/parts/Chart.ts
  ts/parts/Series.ts
  ts/parts/Tooltip.ts
  ts/parts/Utilities.ts
Labels: Product: Highcharts

#11626 bugfix/11477-export-data-parallel-coords
  js/modules/export-data.src.js
  samples/unit-tests/export-data/basics/demo.js
  samples/unit-tests/pointer/members/demo.js
  ts/modules/export-data.src.ts
Labels: Changelog: Bugfix, Status: Inbox

#11884 bugfix/11405-plotlines-bottom-chart-edge
  js/parts/Axis.js
  samples/unit-tests/plotbandslines/plotbandslines/demo.js
  ts/parts/Axis.ts
Labels: Changelog: Bugfix

#11979 ts/modules-timeline
  .eslintignore
  js/modules/timeline.src.js
  ts/modules/timeline.src.ts
Labels: Status: Inbox

#11989 enhancement/plot-lines-radialAxis-3
  js/parts-more/RadialAxis.js
  js/parts/PlotLineOrBand.js
  samples/highcharts/series-solidgauge/labels-auto-aligned/demo.js
  samples/unit-tests/axis/plotlines-and-plotbands/demo.html
  samples/unit-tests/axis/plotlines-and-plotbands/demo.js
  ts/parts-more/RadialAxis.ts
  ts/parts/PlotLineOrBand.ts
Labels: Changelog: Feature

#11983 bugfix/11510-variwide-minimum-point-width
  js/modules/variwide.src.js
  samples/unit-tests/series-variwide/variwide/demo.js
Labels: Changelog: Bugfix

#11998 bugfix/11955-inverted-chart-incorrect-point-positions
  js/parts/Series.js
  samples/unit-tests/axis/pointplacement/demo.js
  ts/parts/Series.ts
Labels: Changelog: Bugfix

#11999 bugfix/11956-pointplacement-single-axis
  js/parts/Axis.js
  samples/unit-tests/axis/members/demo.js
  ts/parts/Axis.ts
Labels: Changelog: Bugfix

#12020 ts/plot-options-reflections
  js/parts/Chart.js
  js/parts/DataGrouping.js
  ts/mixins/centered-series.ts
  ts/modules/broken-axis.src.ts
  ts/modules/dependency-wheel.src.ts
  ts/modules/draggable-points.src.ts
  ts/modules/funnel3d.src.ts
  ts/modules/networkgraph/networkgraph.src.ts
  ts/modules/price-indicator.src.ts
  ts/modules/sankey.src.ts
  ts/modules/series-label.src.ts
  ts/modules/sunburst.src.ts
  ts/modules/timeline.src.ts
  ts/modules/treemap.src.ts
  ts/parts-3d/Column.ts
  ts/parts-map/ColorAxis.ts
  ts/parts-map/MapSeries.ts
  ts/parts-more/BubbleSeries.ts
  ts/parts-more/PackedBubbleSeries.ts
  ts/parts-more/Polar.ts
  ts/parts/AreaSeries.ts
  ts/parts/AreaSplineSeries.ts
  ts/parts/CandlestickSeries.ts
  ts/parts/Chart.ts
  ts/parts/ColumnSeries.ts
  ts/parts/DataGrouping.ts
  ts/parts/Globals.ts
  ts/parts/Interaction.ts
  ts/parts/Legend.ts
  ts/parts/PieSeries.ts
  ts/parts/Point.ts
  ts/parts/Series.ts
  ts/parts/StockChart.ts
  ts/parts/Tooltip.ts
Labels: Status: Inbox

#12028 ts/modules-variwide
  .eslintignore
  js/modules/variwide.src.js
  ts/modules/variwide.src.ts
  ts/parts/Axis.ts
Labels: Status: Inbox

#12039 ts/modules-vector
  .eslintignore
  js/modules/vector.src.js
  ts/modules/vector.src.ts
Labels: Status: Inbox

#12038 ts/modules-venn
  .eslintignore
  js/modules/venn.src.js
  ts/mixins/draw-point.ts
  ts/mixins/tree-series.ts
  ts/modules/venn.src.ts
Labels: Status: Inbox

#12048 bugfix/12043-liveredraw-mobile
  js/parts/Navigator.js
  ts/parts/Navigator.ts
Labels: Product: Highstock

#12062 Fixed #12033, error when toggling stacking on area series with nulls
  js/parts/AreaSeries.js
  samples/unit-tests/series-area/update/demo.details
  samples/unit-tests/series-area/update/demo.html
  samples/unit-tests/series-area/update/demo.js
  ts/parts/AreaSeries.ts
Labels: Changelog: Bugfix

#11672 Bugfix/11670 scrollable navigator
  js/parts/Navigator.js
  js/parts/ScrollablePlotArea.js
  ts/parts/Navigator.ts
  ts/parts/ScrollablePlotArea.ts
Labels: Changelog: Bugfix, Product: Highstock

#12082 Fixed #12064, useless spaces in class attributes
  js/parts/SvgRenderer.js
  samples/unit-tests/svgrenderer/addclass-hasclass-removeclass/demo.js
  ts/parts/SvgRenderer.ts
Labels: Changelog: Bugfix

#12083 Fixed #12058, compare with one data value failed
  js/parts/StockChart.js
  samples/unit-tests/series/compare/demo.js
  ts/parts/StockChart.ts
Labels: Changelog: Bugfix, Product: Highstock

#12089 Bugfix/12055 overlapping legend items
  js/parts/Legend.js
  js/parts/Options.js
  samples/unit-tests/legend/layout/demo.js
  ts/parts/Legend.ts
  ts/parts/Options.ts
Labels: Changelog: Bugfix
