Repository highcharts/highcharts, pull requests merged in 2020-04, with the labels that each got.

#13213 bugfix/12834-hidden-series-wrong-extremes
  js/parts/ScrollbarAxis.js
  samples/unit-tests/scrollbar/extremes/demo.js
  ts/parts/ScrollbarAxis.ts
Labels: Changelog: Bugfix, Product: Highstock, Status: Pending review

#13234 bugfix/11480-priceIndicator-yAxis-crosshair
  js/modules/price-indicator.src.js
  samples/unit-tests/indicator-price-indicator/recalculations/demo.js
  ts/modules/price-indicator.src.ts
Labels: Changelog: Bugfix, Product: Highstock, Status: Pending review

#13232 bugfix/tilemap-incorrect-marker-attributes
  js/modules/tilemap.src.js
  samples/unit-tests/series-tilemap/coloraxis/demo.js
  ts/modules/tilemap.src.ts
Labels: Priority: High, Status: Pending review, Type: Regression

#13176 bugfix/13175-fullscreen-stockTools-bindings
  js/modules/full-screen.src.js
  js/modules/stock-tools-bindings.js
  js/modules/stock-tools-gui.js
  ts/modules/full-screen.src.ts
  ts/modules/stock-tools-bindings.ts
  ts/modules/stock-tools-gui.ts
Labels: Changelog: Bugfix, Product: Highstock

#13235 ts/parallel-axis
  js/modules/parallel-coordinates.src.js
  ts/modules/parallel-coordinates.src.ts
  ts/parts/axis/types.d.ts
Labels: Status: Pending review

#13259 bugfix/13226-tooltip-prevents-interaction
  js/parts/SvgRenderer.js
  ts/parts/SvgRenderer.ts
Labels: Changelog: Bugfix, Status: Pending review

#13272 bugfix/13184-scrollbar-toggle-extremes
  js/parts/Navigator.js
  samples/unit-tests/scrollbar/extremes/demo.js
  ts/parts/Navigator.ts
Labels: Changelog: Bugfix, Product: Highstock

#13289 bugfix/12391-crash-zones
  js/parts/Series.js
  samples/unit-tests/series/zones-highstock/demo.details
  samples/unit-tests/series/zones-highstock/demo.html
  samples/unit-tests/series/zones-highstock/demo.js
  ts/parts/Series.ts
Labels: Changelog: Bugfix, Product: Highstock

#13296 bugfix/13098-wordcloud-animation-duration
  js/mixins/draw-point.js
  samples/unit-tests/series-wordcloud/api-dynamics/demo.js
  ts/mixins/draw-point.ts
Labels: Changelog: Bugfix, Product: Highcharts

#13282 bugfix/8280-wrong-3d-columns-zIndex
  js/parts-3d/SVGRenderer.js
  ts/parts-3d/SVGRenderer.ts
Labels: Changelog: Bugfix

#13318 bugfix/12054-stocktools-restore-annotations
  js/annotations/navigationBindings.js
  js/annotations/types/BasicAnnotation.js
  js/masters/modules/annotations-advanced.src.js
  samples/unit-tests/stock-tools/bindings/demo.js
  ts/annotations/navigationBindings.ts
  ts/annotations/types/BasicAnnotation.ts
Labels: Changelog: Bugfix, Product: Highstock, Status: Pending review

#13317 bugfix/12924-map-pie-mobile-version
  samples/maps/demo/map-pies/demo.js
Labels: Product: Website

#13333 bugfix/13332-3d-column-ie-not-working
  js/parts-3d/SVGRenderer.js
  ts/parts-3d/SVGRenderer.ts
Labels: Changelog: Bugfix, Status: Pending review

#13343 docs/13316-export-download-data
  js/modules/export-data.src.js
  ts/modules/export-data.src.ts
Labels: Status: Pending review

#13328 Tools: Fixed filesize gulp task failing
  tools/gulptasks/unsorted/filesize.js
Labels: Status: Pending review

#13349 Change a link in network-graph.md
  docs/chart-and-series-types/network-graph.md
Labels: Product: Docs, Status: Pending review

#13354 docs/custom-maps-support-link
  docs/maps/create-custom-maps-for-highmaps.md
Labels: Status: Pending review

#13362 Fixed #13305, focus border not updated with scrolling points.
  js/modules/accessibility/components/SeriesComponent/SeriesKeyboardNavigation.js
  js/modules/accessibility/focusBorder.js
  js/modules/accessibility/utils/chartUtilities.js
  samples/stock/yaxis/inverted-bar-scrollbar/demo.html
  samples/unit-tests/accessibility/focus-border/demo.details
  samples/unit-tests/accessibility/focus-border/demo.html
  samples/unit-tests/accessibility/focus-border/demo.js
  ts/modules/accessibility/components/SeriesComponent/SeriesKeyboardNavigation.ts
  ts/modules/accessibility/focusBorder.ts
  ts/modules/accessibility/utils/chartUtilities.ts
Labels: Changelog: Bugfix, Status: Pending review

#13181 Fixed #12984, gantt tasks not collapsed with addseries
  js/parts-gantt/TreeGridAxis.js
  samples/unit-tests/gantt/treegrid/demo.js
  ts/parts-gantt/TreeGridAxis.ts
Labels: Changelog: Bugfix, Product: Highcharts Gantt, Status: Pending review

#13358 bugfix/11500-stacklabels-moved-yAxis
  js/parts/Stacking.js
  samples/unit-tests/axis/stacklabels/demo.js
  ts/parts/Stacking.ts
Labels: Changelog: Bugfix, Status: Pending review

#13364 bugfix/13330-stacklabels-backgroundColor-issue
  js/parts/Axis.js
  js/parts/Stacking.js
  samples/highcharts/yaxis/stacklabels-box/demo.details
  samples/highcharts/yaxis/stacklabels-box/demo.html
  samples/highcharts/yaxis/stacklabels-box/demo.js
  samples/unit-tests/axis/stacklabels/demo.js
  ts/parts/Axis.ts
  ts/parts/Stacking.ts
Labels: Changelog: Feature, Status: Pending review

#13382 axis-types
  js/modules/parallel-coordinates.src.js
  ts/modules/broken-axis.src.ts
  ts/modules/parallel-coordinates.src.ts
  ts/parts-3d/Axis3D.ts
  ts/parts-3d/VMLAxis3D.ts
  ts/parts-3d/ZAxis.ts
  ts/parts-gantt/GridAxis.ts
  ts/parts-gantt/TreeGridAxis.ts
  ts/parts-map/MapAxis.ts
  ts/parts-more/HiddenAxis.ts
  ts/parts-more/RadialAxis.ts
  ts/parts/DateTimeAxis.ts
  ts/parts/LogarithmicAxis.ts
  ts/parts/NavigatorAxis.ts
  ts/parts/OrdinalAxis.ts
  ts/parts/ScrollbarAxis.ts
  ts/parts/StackingAxis.ts
  ts/parts/axis/types.d.ts
Labels: Status: In progress

#13351 TypeScript: Corrected typing for SVGElement.text
  js/annotations/eventEmitterMixin.js
  js/modules/organization.src.js
  js/parts/SvgRenderer.js
  ts/annotations/eventEmitterMixin.ts
  ts/modules/organization.src.ts
  ts/parts/SvgRenderer.ts
Labels: Status: Pending review

#13355 enhancement/navigationBindings
  js/annotations/navigationBindings.js
  js/annotations/popup.js
  js/modules/stock-tools-bindings.js
  js/modules/stock-tools-gui.js
  ts/annotations/navigationBindings.ts
  ts/annotations/popup.ts
  ts/modules/stock-tools-bindings.ts
  ts/modules/stock-tools-gui.ts
Labels: Status: Pending review

#13377 Fixed dead link to Download section.
  docs/getting-started/installation.md
Labels: Status: Pending review

#13393 Docs: Fixed unescaped codeblock in map-collection doc
  docs/maps/map-collection.md
Labels: Status: Pending review

#13395 bugfix/12767-incorrect-table-data
  js/modules/export-data.src.js
  samples/unit-tests/export-data/basics/demo.js
  ts/modules/export-data.src.ts
Labels: Changelog: Bugfix, Product: Highcharts, Status: Pending review

#13399 bugfix/13177-zones-update-color
  js/parts/Point.js
  samples/unit-tests/series/zones/demo.js
  ts/parts/Point.ts
Labels: Status: Pending review

#13403 Fixed issue where browser outline was visible on point click.
  js/modules/accessibility/KeyboardNavigation.js
  js/modules/accessibility/components/SeriesComponent/SeriesDescriber.js
  samples/unit-tests/svgrenderer/styled-mode/demo.js
  ts/modules/accessibility/KeyboardNavigation.ts
  ts/modules/accessibility/components/SeriesComponent/SeriesDescriber.ts
Labels: Status: Pending review

#13404 Fixed issue with missing a11y options in API.
  js/modules/accessibility/options/options.js
  ts/modules/accessibility/options/options.ts
Labels: Changelog: Bugfix, Status: Pending review

#13241 enhancement/packedbubble-smooth-animation
  css/highcharts.scss
  js/indicators/ao.src.js
  js/indicators/macd.src.js
  js/modules/dumbbell.src.js
  js/modules/item-series.src.js
  js/modules/networkgraph/networkgraph.src.js
  js/modules/overlapping-datalabels.src.js
  js/parts-more/PackedBubbleSeries.js
  js/parts/ColumnSeries.js
  js/parts/Interaction.js
  js/parts/Series.js
  samples/unit-tests/axis/stacklabels/demo.js
  samples/unit-tests/datalabels/overlapping/demo.js
  samples/unit-tests/series/datalabels/demo.js
  ts/indicators/ao.src.ts
  ts/indicators/macd.src.ts
  ts/modules/dumbbell.src.ts
  ts/modules/item-series.src.ts
  ts/modules/networkgraph/networkgraph.src.ts
  ts/modules/overlapping-datalabels.src.ts
  ts/parts-more/PackedBubbleSeries.ts
  ts/parts/ColumnSeries.ts
  ts/parts/Interaction.ts
  ts/parts/Series.ts
Labels: Status: Pending review
