Repository highcharts/highcharts, pull requests merged in 2020-06, with the labels that each got.

#13617 bugfix/lollipop-point
  ts/modules/lollipop.src.ts
Labels: Priority: Blocker, Status: Pending review

#13603 Fixed issue with oneToOne and ids
  js/parts/Dynamics.js
  samples/unit-tests/chart/chart-update-onetoone/demo.js
  samples/unit-tests/series-histogram/histogram/demo.js
  ts/parts/Dynamics.ts
Labels: Status: Pending review

#13604 bugfix/13420-annotations-not-added-on-ios
  js/annotations/eventEmitterMixin.js
  js/annotations/navigationBindings.js
  ts/annotations/eventEmitterMixin.ts
  ts/annotations/navigationBindings.ts
Labels: Changelog: Bugfix, Status: Pending review

#13596 bugfix/13372-horizontal-item-series-drilldown
  js/modules/drilldown.src.js
  samples/unit-tests/series-item/dynamic/demo.html
  samples/unit-tests/series-item/dynamic/demo.js
  ts/modules/drilldown.src.ts
Labels: Changelog: Bugfix, Product: Highcharts, Status: Pending review

#13612 Corrected a dead link to create custom map article
  docs/maps/map-collection.md
Labels: Status: Pending review

#13244 enhancement/11782-packedbubble-parent node selection
  js/modules/networkgraph/draggable-nodes.js
  js/modules/networkgraph/layouts.js
  js/parts-more/PackedBubbleSeries.js
  samples/unit-tests/series-packedbubble/packedbubble/demo.js
  ts/modules/networkgraph/draggable-nodes.ts
  ts/modules/networkgraph/layouts.ts
  ts/parts-more/PackedBubbleSeries.ts
  ts/parts/Interaction.ts
Labels: Changelog: Feature, Status: Pending review

#13623 bugfix/packedbubble-chart
  js/parts-more/PackedBubbleSeries.js
  ts/parts-more/PackedBubbleSeries.ts
Labels: Priority: Blocker, Status: Pending review

#13357 bugfix/13309-pdf-export-orientation
  js/modules/offline-exporting.src.js
  ts/modules/offline-exporting.src.ts
Labels: Changelog: Bugfix, Status: Pending review

#13453 enhancement/deprecate
  errors/32/readme.md
  errors/errors.json
  js/error-messages.js
  js/modules/accessibility/options/deprecatedOptions.js
  js/modules/treemap.src.js
  js/parts/Utilities.js
  samples/highcharts/common-js/browserify/app.js
  samples/unit-tests/series-pie/pie/demo.js
  ts/modules/accessibility/options/deprecatedOptions.ts
  ts/modules/treemap.src.ts
  ts/parts/Utilities.ts
Labels: Changelog: Feature, Status: Pending review, Type: Enhancement

#12846 Added new stacking option, category-center
  js/parts/ColumnSeries.js
  js/parts/Series.js
  js/parts/Stacking.js
  js/parts/StackingAxis.js
  samples/highcharts/series-column/centerincategory/demo.css
  samples/highcharts/series-column/centerincategory/demo.details
  samples/highcharts/series-column/centerincategory/demo.html
  samples/highcharts/series-column/centerincategory/demo.js
  samples/unit-tests/series/centerincategory/demo.details
  samples/unit-tests/series/centerincategory/demo.html
  samples/unit-tests/series/centerincategory/demo.js
  ts/parts/ColumnSeries.ts
  ts/parts/Series.ts
  ts/parts/Stacking.ts
  ts/parts/StackingAxis.ts
Labels: Changelog: Feature

#13640 docs/gantt-point-id
  js/parts-gantt/GanttSeries.js
  ts/parts-gantt/GanttSeries.ts
Labels: Status: Pending review

#13639 docs/series-useroptions
  js/parts/Series.js
  ts/parts/Series.ts
Labels: Status: Pending review

#13650 Regression with labels and shape = rect
  js/parts/SVGLabel.js
  ts/parts/SVGLabel.ts
Labels: Status: Pending review

#13654 bugfix/13195-dataclasses-hidden-points
  js/parts-map/ColorSeriesMixin.js
  samples/unit-tests/coloraxis/dataclasses/demo.js
  ts/parts-map/ColorSeriesMixin.ts
Labels: Changelog: Bugfix, Product: Highcharts Maps, Status: Pending review

#13662 bugfix/module-imports
  js/modules/export-data.src.js
  js/modules/funnel.src.js
  js/modules/offline-exporting.src.js
  ts/modules/export-data.src.ts
  ts/modules/funnel.src.ts
  ts/modules/offline-exporting.src.ts
Labels: Status: Pending review

#13663 Fixed a11y issue, errors on drillup button touch
  js/modules/accessibility/AccessibilityComponent.js
  ts/modules/accessibility/AccessibilityComponent.ts
Labels: Changelog: Bugfix, Status: Pending review

#13661 Fixed #13641, legend click on mobile sometimes fails with a11y module.
  js/modules/accessibility/AccessibilityComponent.js
  ts/modules/accessibility/AccessibilityComponent.ts
Labels: Changelog: Bugfix, Status: Pending review

#13675 enhancement/rangeselector-es6
  js/parts/RangeSelector.js
  ts/parts/RangeSelector.ts
  ts/parts/Utilities.ts
Labels: Status: Pending review

#13666 bugfix/13327-pattern-export-safari
  js/modules/pattern-fill.src.js
  ts/modules/pattern-fill.src.ts
Labels: Changelog: Bugfix

#13668 bugfix/13629-pie-gauge-inner-size
  js/mixins/centered-series.js
  samples/unit-tests/series-pie/innersize/demo.html
  samples/unit-tests/series-pie/innersize/demo.js
  ts/mixins/centered-series.ts
Labels: Changelog: Bugfix, Status: Pending review

#13669 tools/tsdoc-debug
  gulpfile.js
  package.json
  tools/gulptasks/tsdoc-debug.js
Labels: Status: Pending review

#13665 ts/deprecate-dictionary
  js/parts/Utilities.js
  ts/parts/Utilities.ts
Labels: Changelog: Bugfix, Product: TypeScript, Status: Pending review

#13695 Docs: Missing items in changelog for v8.1.1
  changelog/changelog.html
  changelog/highcharts/8.1.1.md
Labels: Status: Pending review

#13645 bugfix/13576-boxplot-series-draggable-values
  js/modules/draggable-points.src.js
  samples/unit-tests/series-boxplot/boxplot/demo.html
  samples/unit-tests/series-boxplot/boxplot/demo.js
  samples/unit-tests/series-xrange/xrange/demo.js
  ts/modules/draggable-points.src.ts
Labels: Changelog: Bugfix, Product: Highcharts, Status: Pending review

#13703 enhancement/annotations-types-es6
  js/annotations/navigationBindings.js
  js/annotations/types/CrookedLine.js
  js/annotations/types/ElliottWave.js
  js/annotations/types/Fibonacci.js
  js/annotations/types/InfinityLine.js
  js/annotations/types/Pitchfork.js
  js/annotations/types/Tunnel.js
  ts/annotations/navigationBindings.ts
  ts/annotations/types/CrookedLine.ts
  ts/annotations/types/ElliottWave.ts
  ts/annotations/types/Fibonacci.ts
  ts/annotations/types/InfinityLine.ts
  ts/annotations/types/Pitchfork.ts
  ts/annotations/types/Tunnel.ts
Labels: Status: Pending review

#13696 docs/13689-axis-labels-context
  js/parts/Axis.js
  ts/parts/Axis.ts
Labels: Status: Pending review

#13693 bugfix/13678-private-constructor-props
  js/annotations/annotations.src.js
  js/parts/SVGRenderer.js
  test/typescript/classes/SVGRenderer.ts
  ts/annotations/annotations.src.ts
  ts/parts/SVGRenderer.ts
Labels: Status: Pending review

#13704 docs/13699-plot-column-y
  js/parts/ColumnSeries.js
  ts/parts/ColumnSeries.ts
Labels: Status: Pending review

#13714 Fixed #13698, a11y not working properly with user tabindex.
  js/modules/accessibility/KeyboardNavigation.js
  js/modules/accessibility/components/InfoRegionsComponent.js
  ts/modules/accessibility/KeyboardNavigation.ts
  ts/modules/accessibility/components/InfoRegionsComponent.ts
Labels: Changelog: Bugfix, Status: Pending review

#13717 Fixed #13680, addSeries failed after setSize
  js/parts/Chart.js
  samples/unit-tests/chart/setsize/demo.js
  ts/parts/Chart.ts
Labels: Changelog: Bugfix, Priority: Blocker, Status: Pending review

#13718 Fixed #13708, a regression breaking Highcharts.keys
  js/parts/Utilities.js
  samples/unit-tests/utilities/utilities/demo.js
  ts/parts/Utilities.ts
Labels: Changelog: Bugfix, Priority: Blocker, Status: Pending review

#13725 Friendlier error message for deprecated members
  js/modules/accessibility/options/deprecatedOptions.js
  js/modules/treemap.src.js
  js/parts/Utilities.js
  ts/modules/accessibility/options/deprecatedOptions.ts
  ts/modules/treemap.src.ts
  ts/parts/Utilities.ts
Labels: Status: Pending review

#13728 bugfix/13664-measure-yAxis
  js/annotations/types/Measure.js
  samples/unit-tests/annotations/annotations-measure/demo.details
  samples/unit-tests/annotations/annotations-measure/demo.html
  samples/unit-tests/annotations/annotations-measure/demo.js
  ts/annotations/types/Measure.ts
Labels: Changelog: Bugfix, Product: Highcharts Stock, Status: Pending review

#13767 Docs: Updated custom files tutorial
  docs/getting-started/how-to-create-custom-highcharts-files.md
Labels: Status: Pending review

#13764 bugfix/13742-dataLabels-allowoverlap-not-working
  js/modules/overlapping-datalabels.src.js
  ts/modules/overlapping-datalabels.src.ts
Labels: Status: Pending review

#13770 bugfix/13710-pie-drawempty-regression
  js/parts/PieSeries.js
  ts/parts/PieSeries.ts
Labels: Changelog: Bugfix, Product: Highcharts, Status: Pending review

#13786 docs/13775-svgpath-type-compatibility
  js/parts/SVGRenderer.js
  ts/parts/SVGRenderer.ts
Labels: Status: Pending review
