Repository highcharts/highcharts, pull requests merged in 2020-01, with the labels that each got.

#12695 bugfix/12424-fdg-in-legend
  js/modules/networkgraph/networkgraph.src.js
  samples/unit-tests/series-networkgraph/networkgraph/demo.js
  ts/modules/networkgraph/networkgraph.src.ts
Labels: Changelog: Bugfix

#12704 bugfix/12156-series-inactive-enabled
  js/parts/Series.js
  samples/highcharts/plotoptions/series-states-inactive-disabled/demo.css
  samples/highcharts/plotoptions/series-states-inactive-disabled/demo.details
  samples/highcharts/plotoptions/series-states-inactive-disabled/demo.html
  samples/highcharts/plotoptions/series-states-inactive-disabled/demo.js
  ts/parts/Series.ts
Labels: Changelog: Bugfix

#12712 bugfix/12711-split-header-box
  js/parts/Tooltip.js
  ts/parts/Tooltip.ts
Labels: Changelog: Bugfix

#12693 bugfix/12515-update-3d-pie-depth
  js/parts-3d/SVGRenderer.js
  samples/unit-tests/3d/series-pie/demo.js
  ts/parts-3d/SVGRenderer.ts
Labels: Changelog: Bugfix, Product: Highcharts

#12717 Fixed #12690, a11y module caused render issues for 3D funnel.
  js/modules/accessibility/components/SeriesComponent/SeriesDescriber.js
  ts/modules/accessibility/components/SeriesComponent/SeriesDescriber.ts
Labels: Changelog: Bugfix

#12723 docs/6737-fix-dateTime-doclet
  js/parts/Options.js
  ts/parts/Options.ts
Labels: Product: Docs

#12655 bugfix/12589-tooltip-wrong-position
  js/parts/ColumnSeries.js
  samples/unit-tests/tooltip/position/demo.js
  ts/parts/ColumnSeries.ts
Labels: Changelog: Bugfix

#12729 Dismiss popup content when user presses ESC key.
  js/modules/accessibility/KeyboardNavigation.js
  js/modules/accessibility/KeyboardNavigationHandler.js
  ts/modules/accessibility/KeyboardNavigation.ts
  ts/modules/accessibility/KeyboardNavigationHandler.ts
Labels: Changelog: Feature

#12722 Fixed #12718, markers invisible on chart update with a11y module.
  js/modules/accessibility/components/SeriesComponent/SeriesDescriber.js
  js/parts/Dynamics.js
  samples/unit-tests/accessibility/null-points/demo.js
  ts/modules/accessibility/components/SeriesComponent/SeriesDescriber.ts
  ts/parts/Dynamics.ts
Labels: Changelog: Bugfix

#12755 Fixed #12617, children of collapsed tree nodes visible
  js/modules/xrange.src.js
  js/parts-gantt/GanttSeries.js
  js/parts/DataLabels.js
  samples/unit-tests/gantt/gantt/demo.js
  ts/modules/xrange.src.ts
  ts/parts-gantt/GanttSeries.ts
  ts/parts/DataLabels.ts
Labels: Changelog: Bugfix, Product: Highcharts Gantt

#12616 enhancement/Inverted-3d-improvements
  .eslintignore
  js/parts-3d/Chart.js
  js/parts-3d/Column.js
  samples/mapdata/countries/fr/fr-pac-all/demo.js
  samples/mapdata/historical/countries/fr-2015/fr-u-all-2015/demo.js
  samples/unit-tests/3d/column-data-labels-visibility/demo.js
  ts/parts-3d/Chart.ts
  ts/parts-3d/Column.ts
Labels: Changelog: Bugfix

#12839 samples/typo-in-capital-name
  samples/data/us-capitals.json
Labels: Product: Highmaps

#12796 bugfix/12736-mouse-over-sticky-tooltip
  js/parts/Interaction.js
  js/parts/Options.js
  js/parts/Pointer.js
  js/parts/Utilities.js
  samples/highcharts/tooltip/stickonhover/demo.details
  samples/highcharts/tooltip/stickonhover/demo.html
  samples/highcharts/tooltip/stickonhover/demo.js
  samples/unit-tests/tooltip/stickonhover/demo.js
  ts/modules/oldie.src.ts
  ts/parts/Interaction.ts
  ts/parts/MSPointer.ts
  ts/parts/Options.ts
  ts/parts/Pointer.ts
  ts/parts/Tooltip.ts
  ts/parts/Utilities.ts
Labels: Changelog: Feature, Priority: High

#12844 bugfix/12666-sankey-connectNulls-functionality
  js/mixins/nodes.js
  js/modules/sankey.src.js
  samples/unit-tests/series-sankey/sankey/demo.js
  ts/mixins/nodes.ts
  ts/modules/sankey.src.ts
Labels: Changelog: Bugfix

#12858 bugfix/12856-polar-tooltip-regression
  js/parts-more/Pane.js
  js/parts/Pointer.js
  samples/unit-tests/pointer/hover/demo.js
  ts/parts-more/Pane.ts
  ts/parts/Pointer.ts
Labels: Type: Regression
