Repository highcharts/highcharts, pull requests merged in 2020-08, with the labels that each got.

#13974 bugfix/10555-scrollablePlotArea-absolute
  js/Extensions/ScrollablePlotArea.js
  ts/Extensions/ScrollablePlotArea.ts
Labels: Changelog: Bugfix, Product: Highcharts, Status: Pending review

#13919 bugfix/13914-axis-negative-log
  .eslintignore
  js/Core/Axis/Axis.js
  js/Core/Axis/LogarithmicAxis.js
  samples/highcharts/yaxis/type-log-negative/demo.js
  samples/unit-tests/axis/type-logarithmic/demo.js
  tools/gulptasks/jsdoc-classes.js
  tools/gulptasks/jsdoc-options.js
  ts/Core/Axis/Axis.ts
  ts/Core/Axis/LogarithmicAxis.ts
Labels: Status: Pending review

#13988 Fixed #13707, view table link should be a button.
  js/Accessibility/Components/InfoRegionsComponent.js
  ts/Accessibility/Components/InfoRegionsComponent.ts
Labels: Changelog: Bugfix, Status: Pending review

#13989 Fixed #13864, better accessible legend item labels.
  js/Accessibility/Options/LangOptions.js
  ts/Accessibility/Options/LangOptions.ts
Labels: Changelog: Bugfix, Status: Pending review

#13975 tools/update
  package.json
Labels: Status: Pending review

#13990 Fixed #13729, focus issues with shift+tab.
  js/Accessibility/KeyboardNavigation.js
  ts/Accessibility/KeyboardNavigation.ts
Labels: Changelog: Bugfix, Status: Pending review

#13991 docs/ts-readme
  ts/README.md
Labels: Status: Pending review

#13978 docs/13965-ajax-options-types
  js/Extensions/Ajax.js
  js/Extensions/Data.js
  js/Extensions/DownloadURL.js
  js/Extensions/ExportData.js
  js/Extensions/OfflineExporting.js
  ts/Extensions/Ajax.ts
  ts/Extensions/Data.ts
  ts/Extensions/DownloadURL.ts
  ts/Extensions/ExportData.ts
  ts/Extensions/OfflineExporting.ts
Labels: Status: Pending review

#13970 bugfix/10779-yAxis-max-issue
  js/Core/Axis/Tick.js
  js/Core/Axis/TreeGridAxis.js
  samples/unit-tests/gantt/grid-axis/demo.js
  ts/Core/Axis/Tick.ts
  ts/Core/Axis/TreeGridAxis.ts
Labels: Changelog: Bugfix, Product: Highcharts Gantt, Status: Pending review

#14032 data-layer/events
  js/Data/DataRow.js
  js/Data/DataTable.js
  js/Data/Modifiers/ChainDataModifier.js
  js/Data/Modifiers/DataModifier.js
  js/Data/Modifiers/GroupDataModifier.js
  js/Data/Modifiers/RangeDataModifier.js
  js/Data/Parsers/CSVDataParser.js
  js/Data/Parsers/DataParser.js
  js/Data/Parsers/HTMLTableParser.js
  js/Data/Stores/CSVDataStore.js
  js/Data/Stores/DataStore.js
  js/Data/Stores/GoogleDataStore.js
  js/Data/Stores/HTMLTableDataStore.js
  test/typescript-karma/Data/CSVDataStore/tests.js
  ts/Data/DataEventEmitter.d.ts
  ts/Data/DataRow.ts
  ts/Data/DataTable.ts
  ts/Data/Modifiers/ChainDataModifier.ts
  ts/Data/Modifiers/DataModifier.ts
  ts/Data/Modifiers/GroupDataModifier.ts
  ts/Data/Modifiers/RangeDataModifier.ts
  ts/Data/Parsers/CSVDataParser.ts
  ts/Data/Parsers/DataParser.ts
  ts/Data/Parsers/HTMLTableParser.ts
  ts/Data/Stores/CSVDataStore.ts
  ts/Data/Stores/DataStore.ts
  ts/Data/Stores/GoogleDataStore.ts
  ts/Data/Stores/HTMLTableDataStore.ts
Labels: Status: Pending review

#13797 bugfix/13533-negative-xValue-on-log-axis
  js/Core/Axis/Axis.js
  js/Core/Series/Series.js
  samples/unit-tests/axis/type-logarithmic/demo.js
  ts/Core/Axis/Axis.ts
  ts/Core/Series/Series.ts
Labels: Changelog: Bugfix, Status: Pending review

#14038 Docs: Typo in legend options
  js/Core/Options.js
  ts/Core/Options.ts
Labels: Status: Pending review

#13896 bugfix/13846-dataLabels-hidden-pie
  js/Extensions/OverlappingDataLabels.js
  ts/Extensions/OverlappingDataLabels.ts
Labels: Changelog: Bugfix, Status: Pending review

#14022 enhancement/13715-axis-label-format-vacation
  js/Core/Axis/GridAxis.js
  ts/Core/Axis/GridAxis.ts
Labels: Status: Pending review

#14028 docs/stock-navigator-redirect
  docs/doc-config.js
  docs/stock/understanding-highcharts-stock.md
Labels: Status: Pending review

#14027 tools/jsdoc-fix
  tools/gulptasks/jsdoc-classes.js
Labels: Status: In progress

#13836 bugfix/13798-range-selector-buttons-text
  js/Core/Renderer/SVG/SVGRenderer.js
  samples/unit-tests/svgrenderer/button/demo.js
  ts/Core/Renderer/SVG/SVGRenderer.ts
Labels: Changelog: Bugfix, Product: Highcharts Stock, Status: Pending review

#13814 bugfix/13788-update-rangeselector
  js/Extensions/RangeSelector.js
  samples/unit-tests/rangeselector/selected/demo.js
  ts/Extensions/RangeSelector.ts
Labels: Changelog: Bugfix, Product: Highcharts Stock, Status: Pending review

#14037 docs/typescript-changes-v7-v8
  docs/advanced-chart-features/highcharts-typescript-declarations.md
Labels: Priority: High, Status: Pending review

#14047 Fixed issue with negative sonification timestamps.
  js/modules/sonification/chartSonify.js
  js/modules/sonification/options.js
  ts/modules/sonification/chartSonify.ts
  ts/modules/sonification/options.ts
Labels: Priority: High, Status: Pending review

#14051 bugfix/13570-update-networkgraph
  js/Series/Networkgraph/Networkgraph.js
  samples/unit-tests/series-networkgraph/networkgraph/demo.js
  ts/Series/Networkgraph/Networkgraph.ts
Labels: Changelog: Bugfix, Status: Pending review

#14052 bugfix/13813-datagrouping-proximate-legend
  js/Core/Legend.js
  samples/unit-tests/legend/layout/demo.js
  ts/Core/Legend.ts
Labels: Changelog: Bugfix, Product: Highcharts Stock, Status: Pending review

#13773 enhancement/13690-toggle-data-table
  js/Extensions/ExportData.js
  samples/highcharts/studies/exporting-table-html/demo.js
  samples/unit-tests/export-data/basics/demo.js
  ts/Extensions/ExportData.ts
Labels: Changelog: Feature, Product: Highcharts, Status: Pending review

#14003 docs/13583-fullscreen
  js/Extensions/FullScreen.js
  js/Stock/StockToolsBindings.js
  ts/Extensions/FullScreen.ts
  ts/Stock/StockToolsBindings.ts
Labels: Status: Pending review

#14062 tools/karma-100-load-attempts
  test/karma-conf.js
Labels: Status: Pending review

#14061 enhancement/pathfinderalgorithms-es6
  js/Gantt/PathfinderAlgorithms.js
  ts/Gantt/Pathfinder.ts
  ts/Gantt/PathfinderAlgorithms.ts
Labels: Status: Pending review

#14087 enhancement/12901-annotation-opacity-fix
  js/Extensions/Annotations/Annotations.js
  ts/Extensions/Annotations/Annotations.ts
Labels: Status: Pending review

#14070 docs/14008-update-highcharts-error-demo
  samples/highcharts/chart/highcharts-error/demo.js
Labels: Status: Pending review

#14069 enhancement/tree-es6
  ts/Core/Axis/TreeGridAxis.ts
  ts/Gantt/Tree.ts
Labels: Status: Pending review

#14083 docs/sankey-dependency
  js/Series/DependencyWheelSeries.js
  js/Series/OrganizationSeries.js
  ts/Series/DependencyWheelSeries.ts
  ts/Series/OrganizationSeries.ts
Labels: Product: Docs, Status: Pending review

#14075 docs/series-centerincategory
  js/Series/ColumnSeries.js
  ts/Core/Series/Series.ts
  ts/Series/ColumnSeries.ts
Labels: Product: Docs, Status: Pending review

#14097 bugfix/12273-exporting-getSVG-iFrame
  js/Extensions/Exporting.js
  samples/unit-tests/exporting/getsvg/demo.js
  ts/Extensions/Exporting.ts
Labels: Changelog: Bugfix, Status: Pending review

#14084 enhancement/map-es6
  js/Maps/Map.js
  js/Series/MapSeries.js
  ts/Maps/Map.ts
  ts/Series/MapSeries.ts
Labels: Status: Pending review

#14106 enhancement/datagrouping-es6
  ts/Extensions/DataGrouping.ts
Labels: Status: Pending review

#14109 enhancement/currentdateindication-es6
  ts/Extensions/CurrentDateIndication.ts
Labels: Status: Pending review

#14112 enhancement/draggablepoints-es6
  js/Extensions/DraggablePoints.js
  ts/Extensions/DraggablePoints.ts
Labels: Status: Pending review

#14116 enhancement/drilldown-es6
  js/Extensions/Drilldown.js
  ts/Extensions/Drilldown.ts
Labels: Status: Pending review

#14117 enhancement/exportdata-es6
  ts/Extensions/ExportData.ts
Labels: Status: Pending review

#14118 enhancement/markerclusters-es6
  js/Extensions/MarkerClusters.js
  ts/Extensions/MarkerClusters.ts
Labels: Status: Pending review

#14121 enhancement/colormapseries-es6
  js/Mixins/ColorMapSeries.js
  js/Series/HeatmapSeries.js
  js/Series/MapSeries.js
  js/Series/TreemapSeries.js
  ts/Mixins/ColorMapSeries.ts
  ts/Series/HeatmapSeries.ts
  ts/Series/MapSeries.ts
  ts/Series/TreemapSeries.ts
Labels: Status: Pending review

#14122 enhancement/data-layer-spec
  package.json
  tools/gulptasks/tsdoc.js
  ts/Data/Specifications.d.ts
  ts/typedoc.json
Labels: Status: Pending review

#14129 enhancement/nodatatodisplay-es6
  js/Extensions/NoDataToDisplay.js
  ts/Extensions/NoDataToDisplay.ts
Labels: Status: Pending review

#14127 enhancement/colorseries-es6
  js/Core/Axis/ColorAxis.js
  js/Mixins/ColorSeries.js
  js/Series/TilemapSeries.js
  ts/Core/Axis/ColorAxis.ts
  ts/Mixins/ColorSeries.ts
  ts/Series/TilemapSeries.ts
Labels: Status: Pending review

#14133 enhancement/patternfill-es6
  js/Extensions/PatternFill.js
  ts/Extensions/PatternFill.ts
Labels: Status: Pending review

#14131 enhancement/offlineexporting-es6
  js/Extensions/OfflineExporting.js
  ts/Extensions/OfflineExporting.ts
Labels: Status: Pending review

#14134 enhancement/polar-es6
  ts/Extensions/Polar.ts
Labels: Status: Pending review

#14135 enhancement/staticscale-es6
  js/Extensions/StaticScale.js
  ts/Extensions/StaticScale.ts
Labels: Status: Pending review

#14137 Added hook for additional processing of sonification instruments.
  js/Extensions/Sonification/Instrument.js
  ts/Extensions/Sonification/Instrument.ts
Labels: Status: Pending review
