Repository highcharts/highcharts, pull requests merged in 2020-07, with the labels that each got.

#13802 bugfix/13722-highcharts-namespace-columnseries
  js/parts/ColumnSeries.js
  ts/parts/ColumnSeries.ts
Labels: Status: Pending review

#13809 ts/annotations-types-rest
  js/annotations/types/Measure.js
  js/annotations/types/VerticalLine.js
  ts/annotations/types/ElliottWave.ts
  ts/annotations/types/Fibonacci.ts
  ts/annotations/types/Measure.ts
  ts/annotations/types/Pitchfork.ts
  ts/annotations/types/Tunnel.ts
  ts/annotations/types/VerticalLine.ts
Labels: Status: Pending review

#13808 Tools: Added `scripts-code` task to `dist` task
  tools/gulptasks/dist.js
Labels: Status: In progress

#13812 tools/eslint-highcharts
  js/parts-more/BoxPlotSeries.js
  package.json
  ts/parts-more/BoxPlotSeries.ts
Labels: Status: Pending review

#13826 docs/changelog-a11y
  changelog/generate-html.js
Labels: Status: Pending review

#13819 docs/13600-pointWidth-description
  js/parts/ColumnSeries.js
  ts/parts/ColumnSeries.ts
Labels: Status: Pending review

#13827 Correct switchRowsAndColumns option name
  docs/working-with-data/data-module.md
Labels: Status: Pending review

#13833 docs/series-cropthreshold
  js/modules/networkgraph/networkgraph.src.js
  js/parts-map/HeatmapSeries.js
  js/parts-more/PackedBubbleSeries.js
  js/parts/PieSeries.js
  js/parts/ScatterSeries.js
  ts/modules/networkgraph/networkgraph.src.ts
  ts/parts-map/HeatmapSeries.ts
  ts/parts-more/PackedBubbleSeries.ts
  ts/parts/PieSeries.ts
  ts/parts/ScatterSeries.ts
Labels: Status: Pending review

#13834 enhancement/parts3d-math-es6
  js/modules/cylinder.src.js
  js/modules/funnel3d.src.js
  js/parts-3d/Axis3D.js
  js/parts-3d/Chart3D.js
  js/parts-3d/Column.js
  js/parts-3d/Math.js
  js/parts-3d/SVGRenderer.js
  js/parts-3d/Scatter.js
  js/parts-3d/Series.js
  ts/modules/cylinder.src.ts
  ts/modules/funnel3d.src.ts
  ts/parts-3d/Axis3D.ts
  ts/parts-3d/Chart3D.ts
  ts/parts-3d/Column.ts
  ts/parts-3d/Math.ts
  ts/parts-3d/SVGRenderer.ts
  ts/parts-3d/Scatter.ts
  ts/parts-3d/Series.ts
Labels: Status: Pending review

#13787 bugfix/13737-draggable-container-zoom
  js/parts/Pointer.js
  ts/parts/Pointer.ts
Labels: Changelog: Bugfix, Status: Pending review

#13835 bugfix/12868-zoom-not-working-after-scrolling-multiple-charts
  js/parts/Pointer.js
  ts/parts/Pointer.ts
Labels: Changelog: Bugfix, Status: Pending review

#13839 docs/series-datamax
  js/parts/Series.js
  ts/parts/Series.ts
Labels: Status: Pending review

#13854 docs/small-fixes
  changelog/generate-html.js
Labels: Status: Pending review

#13857 enhancement/mixins-centered-series-es6
  js/mixins/centered-series.js
  js/modules/sunburst.src.js
  js/parts-more/Pane.js
  js/parts/PieSeries.js
  ts/mixins/centered-series.ts
  ts/modules/sunburst.src.ts
  ts/parts-more/Pane.ts
  ts/parts/PieSeries.ts
Labels: Status: Pending review

#13863 enhancement/mixins-download-url-es6
  js/mixins/download-url.js
  js/modules/export-data.src.js
  js/modules/offline-exporting.src.js
  ts/mixins/download-url.ts
  ts/modules/export-data.src.ts
  ts/modules/offline-exporting.src.ts
Labels: Status: Pending review

#13865 enhancement/mixins-derived-series-es6
  ts/mixins/derived-series.ts
Labels: Status: Pending review

#13862 Fix typo in Stacked and grouped column demo
  samples/highcharts/demo/column-stacked-and-grouped/demo.js
Labels: Status: Pending review

#13877 tools/folder-themes
  js/Extensions/Themes/Avocado.js
  js/Extensions/Themes/DarkBlue.js
  js/Extensions/Themes/DarkGreen.js
  js/Extensions/Themes/DarkUnica.js
  js/Extensions/Themes/Gray.js
  js/Extensions/Themes/Grid.js
  js/Extensions/Themes/GridLight.js
  js/Extensions/Themes/HighContrastDark.js
  js/Extensions/Themes/HighContrastLight.js
  js/Extensions/Themes/SandSignika.js
  js/Extensions/Themes/Skies.js
  js/Extensions/Themes/Sunset.js
  js/masters/themes/avocado.src.js
  js/masters/themes/dark-blue.src.js
  js/masters/themes/dark-green.src.js
  js/masters/themes/dark-unica.src.js
  js/masters/themes/gray.src.js
  js/masters/themes/grid-light.src.js
  js/masters/themes/grid.src.js
  js/masters/themes/high-contrast-dark.src.js
  js/masters/themes/high-contrast-light.src.js
  js/masters/themes/sand-signika.src.js
  js/masters/themes/skies.src.js
  js/masters/themes/sunset.src.js
  ts/Extensions/Themes/Avocado.ts
  ts/Extensions/Themes/DarkBlue.ts
  ts/Extensions/Themes/DarkGreen.ts
  ts/Extensions/Themes/DarkUnica.ts
  ts/Extensions/Themes/Gray.ts
  ts/Extensions/Themes/Grid.ts
  ts/Extensions/Themes/GridLight.ts
  ts/Extensions/Themes/HighContrastDark.ts
  ts/Extensions/Themes/HighContrastLight.ts
  ts/Extensions/Themes/SandSignika.ts
  ts/Extensions/Themes/Skies.ts
  ts/Extensions/Themes/Sunset.ts
Labels: Status: Pending review

#13888 bugfix/extensions-geojson
  js/Extensions/GeoJSON.js
  js/masters/modules/map.src.js
  ts/Extensions/GeoJSON.ts
Labels: Priority: High, Status: In progress

#13889 enhancement/mixins-geometry-es6
  ts/mixins/geometry.ts
Labels: Status: Pending review

#13891 enhancement/mixins-legend-symbol-es6
  js/mixins/legend-symbol.js
  ts/Core/Axis/ColorAxis.ts
  ts/mixins/legend-symbol.ts
Labels: Status: Pending review

#13899 enhancement/mixins-multiple-lines-es6
  js/Stock/Indicators/ABIndicator.js
  js/Stock/Indicators/AroonIndicator.js
  js/Stock/Indicators/AroonOscillatorIndicator.js
  js/Stock/Indicators/BBIndicator.js
  js/Stock/Indicators/KeltnerChannelsIndicator.js
  js/Stock/Indicators/PCIndicator.js
  js/Stock/Indicators/StochasticIndicator.js
  js/mixins/multiple-lines.js
  ts/Stock/Indicators/ABIndicator.ts
  ts/Stock/Indicators/AroonIndicator.ts
  ts/Stock/Indicators/AroonOscillatorIndicator.ts
  ts/Stock/Indicators/BBIndicator.ts
  ts/Stock/Indicators/KeltnerChannelsIndicator.ts
  ts/Stock/Indicators/PCIndicator.ts
  ts/Stock/Indicators/StochasticIndicator.ts
  ts/mixins/multiple-lines.ts
Labels: Status: Pending review

#13900 enhancement/mixins-navigation-es6
  ts/mixins/navigation.ts
Labels: Status: Pending review

#13901 enhancement/mixins-nelder-mead-es6
  js/Series/VennSeries.js
  js/mixins/nelder-mead.js
  ts/Series/VennSeries.ts
  ts/mixins/nelder-mead.ts
Labels: Status: Pending review

#13902 enhancement/mixins-nodes-es6
  js/Series/DependencyWheelSeries.js
  js/Series/Networkgraph/Networkgraph.js
  js/Series/SankeySeries.js
  js/mixins/nodes.js
  ts/Series/DependencyWheelSeries.ts
  ts/Series/Networkgraph/Networkgraph.ts
  ts/Series/SankeySeries.ts
  ts/mixins/nodes.ts
Labels: Status: Pending review

#13904 enhancement/mixins-on-series-es6
  ts/mixins/on-series.ts
Labels: Status: Pending review

#13907 enhancement/mixins-polygon-es6
  js/Series/WordcloudSeries.js
  ts/Series/WordcloudSeries.ts
  ts/mixins/polygon.ts
Labels: Status: Pending review

#13908 enhancement/mixins-reduce-array-es6
  ts/mixins/reduce-array.ts
Labels: Status: Pending review

#13909 enhancement/mixins-tree-series-es6
  js/Core/Axis/TreeGridAxis.js
  js/Series/SunburstSeries.js
  js/Series/TreemapSeries.js
  ts/Core/Axis/TreeGridAxis.ts
  ts/Series/SunburstSeries.ts
  ts/Series/TreemapSeries.ts
  ts/mixins/tree-series.ts
Labels: Status: Pending review

#13890 enhancement/mixins-indicator-required-es6
  js/Stock/Indicators/APOIndicator.js
  js/Stock/Indicators/AroonOscillatorIndicator.js
  js/Stock/Indicators/ChaikinIndicator.js
  js/Stock/Indicators/DEMAIndicator.js
  js/Stock/Indicators/Indicators.js
  js/Stock/Indicators/PPOIndicator.js
  js/Stock/Indicators/TEMAIndicator.js
  ts/Stock/Indicators/APOIndicator.ts
  ts/Stock/Indicators/AroonOscillatorIndicator.ts
  ts/Stock/Indicators/ChaikinIndicator.ts
  ts/Stock/Indicators/DEMAIndicator.ts
  ts/Stock/Indicators/Indicators.ts
  ts/Stock/Indicators/PPOIndicator.ts
  ts/Stock/Indicators/TEMAIndicator.ts
  ts/mixins/indicator-required.ts
Labels: Status: Pending review

#13893 enhancement/13715-axis-label-format
  js/Core/Axis/Axis.js
  js/Core/Axis/GridAxis.js
  samples/gantt/grid-axis/date-time-label-formats/demo.css
  samples/gantt/grid-axis/date-time-label-formats/demo.details
  samples/gantt/grid-axis/date-time-label-formats/demo.html
  samples/gantt/grid-axis/date-time-label-formats/demo.js
  ts/Core/Axis/Axis.ts
  ts/Core/Axis/GridAxis.ts
Labels: Changelog: Feature, Product: Docs, Product: Highcharts Gantt, Status: Pending review

#13913 Fixed issue with sonification timeline.atStart false positive.
  js/modules/sonification/Timeline.js
  ts/modules/sonification/Timeline.ts
Labels: Changelog: Bugfix, Status: Pending review

#13936 tools/fix-jsdoc-classes
  tools/gulptasks/jsdoc-classes.js
Labels: Priority: High, Status: Pending review

#13921 bugfix/13789-polar-connect-ends
  js/Series/AreaRangeSeries.js
  samples/unit-tests/series-arearange/polar/demo.details
  samples/unit-tests/series-arearange/polar/demo.html
  samples/unit-tests/series-arearange/polar/demo.js
  ts/Series/AreaRangeSeries.ts
Labels: Changelog: Bugfix, Status: Pending review

#13927 bugfix/sample-rangeselector
  samples/unit-tests/rangeselector/input-range/demo.js
Labels: Status: Pending review

#13951 docs/boost-probe
  docs/advanced-chart-features/boost-module.md
Labels: Status: Pending review

#13941 tools/fix-jsdoc-classes-2
  tools/gulptasks/jsdoc-classes.js
Labels: Priority: High, Status: Pending review

#13967 bugfix/10281-gantt-yaxis-adjustment-label
  js/Core/Axis/GridAxis.js
  samples/unit-tests/gantt/grid-axis/demo.js
  ts/Core/Axis/GridAxis.ts
Labels: Status: Pending review
