Repository highcharts/highcharts, pull requests merged in 2020-12, with the labels that each got.

#14713 ts/gantt-series
  js/Core/Axis/GridAxis.js
  js/Core/Axis/TreeGridAxis.js
  js/Core/Chart/GanttChart.js
  js/Series/Gantt/GanttPoint.js
  js/Series/Gantt/GanttSeries.js
  js/masters/modules/gantt.src.js
  ts/Core/Axis/GridAxis.ts
  ts/Core/Axis/TreeGridAxis.ts
  ts/Core/Chart/GanttChart.ts
  ts/Extensions/DraggablePoints.ts
  ts/Gantt/Pathfinder.ts
  ts/Series/Gantt/GanttPoint.ts
  ts/Series/Gantt/GanttPointOptions.d.ts
  ts/Series/Gantt/GanttSeries.ts
  ts/Series/Gantt/GanttSeriesOptions.d.ts
  ts/Series/GanttSeries.ts
Labels: Product: Highcharts Gantt, Status: In progress

#14678 ts/vbp-indicator
  js/Stock/Indicators/VBP/VBPIndicator.js
  js/Stock/Indicators/VBP/VBPPoint.js
  js/masters/indicators/indicators-all.src.js
  js/masters/indicators/volume-by-price.src.js
  ts/Stock/Indicators/VBP/VBPIndicator.ts
  ts/Stock/Indicators/VBP/VBPOptions.d.ts
  ts/Stock/Indicators/VBP/VBPPoint.ts
  ts/Stock/Indicators/VBPIndicator.ts
Labels: Product: Highcharts Stock, Status: Pending review

#14730 bugfix/14729-ROCOptions-wrong-export
  ts/Stock/Indicators/ROC/ROCOptions.d.ts
Labels: Product: Highcharts Stock, Status: Pending review

#14722 ts/funnel3d-fix
  js/Series/Funnel3D/Funnel3DComposition.js
  js/Series/Funnel3D/Funnel3DPoint.js
  js/Series/Funnel3D/Funnel3DSeries.js
  js/Series/Funnel3DSeries.js
  js/masters/modules/funnel3d.src.js
  ts/Series/Funnel3D/Funnel3DComposition.ts
  ts/Series/Funnel3D/Funnel3DPoint.ts
  ts/Series/Funnel3D/Funnel3DSeries.ts
Labels: Status: Pending review

#14714 ts/waterfall-series
  js/Core/Axis/WaterfallAxis.js
  js/Series/Waterfall/WaterfallPoint.js
  js/Series/Waterfall/WaterfallSeries.js
  js/masters/highcharts-more.src.js
  ts/Core/Axis/WaterfallAxis.ts
  ts/Extensions/DraggablePoints.ts
  ts/Series/Waterfall/WaterfallPoint.ts
  ts/Series/Waterfall/WaterfallPointOptions.d.ts
  ts/Series/Waterfall/WaterfallSeries.ts
  ts/Series/Waterfall/WaterfallSeriesOptions.d.ts
Labels: Product: Highcharts, Status: Pending review

#14743 samples/xmas-demo-details
  samples/highcharts/blog/xmas-card-2020/demo.details
Labels: Status: Pending review

#14715 Docs: Update chart-types.md
  docs/chart-and-series-types/chart-types.md
Labels: Status: Pending review

#14726 bugfix/tema-dema-indicator-linkedTo
  js/Stock/Indicators/DEMA/DEMAIndicator.js
  js/Stock/Indicators/TEMA/TEMAIndicator.js
  samples/unit-tests/indicator-dema/recalculations/demo.js
  samples/unit-tests/indicator-tema/recalculations/demo.js
  ts/Stock/Indicators/DEMA/DEMAIndicator.ts
  ts/Stock/Indicators/TEMA/TEMAIndicator.ts
Labels: Changelog: Bugfix, Product: Highcharts Stock, Status: Pending review

#14734 bugfix/13804-3d-pie-inactive-animation
  js/Core/Renderer/SVG/SVGElement.js
  samples/unit-tests/3d/series-pie/demo.js
  ts/Core/Renderer/SVG/SVGElement.ts
Labels: Changelog: Bugfix, Status: Pending review

#14737 bugfix/13490-polar-update-hover
  js/Extensions/Pane.js
  samples/unit-tests/polar/update/demo.details
  samples/unit-tests/polar/update/demo.html
  samples/unit-tests/polar/update/demo.js
  ts/Extensions/Pane.ts
Labels: Changelog: Bugfix, Status: Pending review

#14739 bugfix/13948-offline-pdf-lineargradient
  js/Extensions/OfflineExporting.js
  ts/Extensions/OfflineExporting.ts
Labels: Product: Highcharts, Status: Pending review

#14744 Refactor series.update, use setPrototypeOf to cast series type
  js/Core/Dynamics.js
  samples/unit-tests/series/update/demo.js
  ts/Core/Dynamics.ts
  ts/Core/Globals.ts
Labels: Status: Pending review

#14708 ts/sunburst-series
  js/Series/Sunburst/SunburstPoint.js
  js/Series/Sunburst/SunburstSeries.js
  js/Series/Sunburst/SunburstUtilities.js
  js/Series/Treemap/TreemapPoint.js
  js/masters/modules/sunburst.src.js
  ts/Series/Sunburst/SunburstDataLabelOptions.d.ts
  ts/Series/Sunburst/SunburstPoint.ts
  ts/Series/Sunburst/SunburstPointOptions.d.ts
  ts/Series/Sunburst/SunburstSeries.ts
  ts/Series/Sunburst/SunburstSeriesOptions.d.ts
  ts/Series/Sunburst/SunburstUtilities.ts
  ts/Series/SunburstSeries.ts
  ts/Series/Treemap/TreemapPoint.ts
  ts/Series/Treemap/TreemapSeries.ts
Labels: Product: Highcharts, Status: Pending review

#14650 ts/MACD-indicator
  js/Stock/Indicators/MACD/MACDIndicator.js
  js/masters/indicators/indicators-all.src.js
  js/masters/indicators/macd.src.js
  samples/unit-tests/series-xrange/xrange/demo.js
  ts/Stock/Indicators/MACD/MACDIndicator.ts
  ts/Stock/Indicators/MACD/MACDOptions.d.ts
  ts/Stock/Indicators/MACD/MACDPoint.d.ts
  ts/Stock/Indicators/MACDIndicator.ts
Labels: Product: Highcharts Stock, Status: Pending review

#14754 ts/tracker-mixout
  js/Core/Interaction.js
  js/Series/Column/ColumnSeries.js
  js/Series/Dumbbell/DumbbellSeries.js
  js/Series/Flags/FlagsSeries.js
  js/Series/Gauge/GaugeSeries.js
  js/Series/Line/LineSeries.js
  js/Series/Networkgraph/Networkgraph.js
  js/Series/PackedBubble/PackedBubbleSeries.js
  js/Series/Pie/PieSeries.js
  js/Series/Scatter/ScatterSeries.js
  js/Series/Timeline/TimelineSeries.js
  ts/Core/Interaction.ts
  ts/Series/Area/AreaSeries.ts
  ts/Series/AreaRange/AreaRangePoint.ts
  ts/Series/AreaRange/AreaRangeSeries.ts
  ts/Series/AreaRange/AreaRangeSeriesOptions.d.ts
  ts/Series/Column/ColumnSeries.ts
  ts/Series/Dumbbell/DumbbellSeries.ts
  ts/Series/Flags/FlagsSeries.ts
  ts/Series/Gauge/GaugeSeries.ts
  ts/Series/Line/LineSeries.ts
  ts/Series/Networkgraph/Networkgraph.ts
  ts/Series/PackedBubble/PackedBubbleSeries.ts
  ts/Series/Pie/PieSeries.ts
  ts/Series/Scatter/ScatterSeries.ts
  ts/Series/Timeline/TimelineSeries.ts
Labels: Product: Highcharts, Status: Pending review

#14741 ts/ikh-indicator
  js/Stock/Indicators/IKH/IKHIndicator.js
  js/masters/indicators/ichimoku-kinko-hyo.src.js
  js/masters/indicators/indicators-all.src.js
  ts/Stock/Indicators/IKH/IKHIndicator.ts
  ts/Stock/Indicators/IKH/IKHOptions.d.ts
  ts/Stock/Indicators/IKH/IKHPoint.d.ts
  ts/Stock/Indicators/IKHIndicator.ts
Labels: Product: Highcharts Stock, Status: Pending review

#14759 ts/animationoptions
  ts/Core/Animation/AnimationOptions.d.ts
  ts/Core/Animation/AnimationUtilities.ts
  ts/Core/Animation/Fx.ts
  ts/Core/Axis/Axis.ts
  ts/Core/Axis/BrokenAxis.ts
  ts/Core/Axis/ColorAxis.ts
  ts/Core/Chart/Chart.ts
  ts/Core/Interaction.ts
  ts/Core/Legend.ts
  ts/Core/Options.ts
  ts/Core/Renderer/SVG/SVGElement.ts
  ts/Core/Renderer/SVG/SVGElement3D.ts
  ts/Core/Renderer/SVG/SVGElement3DLike.d.ts
  ts/Core/Renderer/SVG/SVGRenderer.ts
  ts/Core/Renderer/SVG/SVGRenderer3D.ts
  ts/Core/Series/DataLabelOptions.d.ts
  ts/Core/Series/Point.ts
  ts/Core/Series/PointOptions.d.ts
  ts/Core/Series/SeriesOptions.d.ts
  ts/Extensions/Annotations/Annotations.ts
  ts/Extensions/DraggablePoints.ts
  ts/Extensions/Drilldown.ts
  ts/Extensions/Exporting.ts
  ts/Extensions/MarkerClusters.ts
  ts/Extensions/PatternFill.ts
  ts/Extensions/SeriesLabel.ts
  ts/Extensions/Stacking.ts
  ts/Gantt/Connection.ts
  ts/Mixins/Nodes.ts
  ts/Series/Gantt/GanttSeriesOptions.d.ts
  ts/Series/Heatmap/HeatmapSeries.ts
  ts/Series/Line/LineSeries.ts
  ts/Series/Line/LineSeriesOptions.d.ts
  ts/Series/Map/MapSeries.ts
  ts/Series/Networkgraph/Networkgraph.ts
  ts/Series/Pie/PiePoint.ts
  ts/Series/Treemap/TreemapSeries.ts
Labels: Status: Pending review

#14770 tests/demos-accessibility
  samples/highcharts/accessibility/accessible-avg-temp/demo.html
  samples/highcharts/accessibility/accessible-bar/demo.html
Labels: Status: Pending review

#14756 ts/tema-dema
  ts/Stock/Indicators/DEMA/DEMAIndicator.ts
  ts/Stock/Indicators/TEMA/TEMAIndicator.ts
Labels: Product: Highcharts Stock, Status: Pending review

#14767 bugfix/14765-global-patterns
  js/Extensions/PatternFill.js
  samples/unit-tests/color/pattern-fill/demo.js
  ts/Extensions/PatternFill.ts
Labels: Changelog: Bugfix, Status: Pending review

#14764 tools/jsdoc-series
  tools/gulptasks/jsdoc-classes.js
Labels: Priority: High, Product: Highcharts, Status: Pending review

#14777 bugfix/14773-pie-styled-second-update-incorrect)
  js/Series/Pie/PieSeries.js
  samples/unit-tests/series-pie/pie/demo.js
  ts/Series/Pie/PieSeries.ts
Labels: Changelog: Bugfix, Product: Highcharts, Status: Pending review

#14768 bugfix/13996-pointer-position-scroll
  js/Core/Pointer.js
  ts/Core/Pointer.ts
Labels: Changelog: Bugfix, Product: Highcharts, Status: Pending review

#14783 Added feature chart.zoomBySingleTouch
  js/Core/Options.js
  js/Core/Pointer.js
  samples/highcharts/chart/zoombysingletouch/demo.css
  samples/highcharts/chart/zoombysingletouch/demo.details
  samples/highcharts/chart/zoombysingletouch/demo.html
  samples/highcharts/chart/zoombysingletouch/demo.js
  samples/unit-tests/interaction/pinchtype/demo.js
  ts/Core/Options.ts
  ts/Core/Pointer.ts
Labels: Changelog: Feature, Status: Pending review

#14790 bugfix/14788-input-type-ie
  js/Extensions/RangeSelector.js
  ts/Extensions/RangeSelector.ts
Labels: Product: Highcharts Stock, Status: Pending review

#14794 bugfix/8795-zoom-setData-hover
  js/Core/Pointer.js
  samples/unit-tests/series/setdata/demo.js
  ts/Core/Pointer.ts
Labels: Changelog: Bugfix, Status: Pending review

#14800 Correct spelling for verify
  tools/compare-api.js
  ts/Extensions/Math3D.ts
Labels: Status: Pending review

#14717 enhancement/rangeselector-dropdown
  docs/stock/range-selector.md
  js/Core/Renderer/HTML/HTMLRenderer.js
  js/Core/Renderer/SVG/SVGLabel.js
  js/Extensions/Exporting.js
  js/Extensions/RangeSelector.js
  samples/stock/rangeselector/button-click/demo.html
  samples/stock/rangeselector/dropdown/demo.css
  samples/stock/rangeselector/dropdown/demo.details
  samples/stock/rangeselector/dropdown/demo.html
  samples/stock/rangeselector/dropdown/demo.js
  samples/unit-tests/datalabels/usehtml/demo.js
  samples/unit-tests/rangeselector/dropdown/demo.details
  samples/unit-tests/rangeselector/dropdown/demo.html
  samples/unit-tests/rangeselector/dropdown/demo.js
  samples/unit-tests/rangeselector/position-antycollision/demo.js
  samples/unit-tests/svgrenderer/label/demo.js
  ts/Core/Renderer/HTML/HTMLRenderer.ts
  ts/Core/Renderer/SVG/SVGLabel.ts
  ts/Extensions/Exporting.ts
  ts/Extensions/RangeSelector.ts
Labels: Changelog: Feature, Product: Highcharts Stock, Status: Pending review

#14823 tools/karma-bs
  package.json
Labels: Status: Pending review
