Repository highcharts/highcharts, pull requests merged in 2021-11, with the labels that each got.

#16558 Updated colors and fonts for new design
  samples/highcharts/accessibility/accessible-venn/demo.css
  samples/highcharts/accessibility/accessible-venn/demo.html
  samples/highcharts/accessibility/accessible-venn/demo.js
Labels: Status: Review in progress

#16573 Tools: CircleCI upgrade
  .circleci/config.yml
  package-lock.json
  package.json
Labels: Status: Review in progress

#16546 bugfix/16532-ordinal-regression
  ts/Core/Axis/OrdinalAxis.ts
Labels: Product: Highcharts Stock, Changelog: Bugfix, Status: Review in progress

#16606 Removed title and subtitle
  samples/highcharts/website/icon-stock/demo.js
Labels: Status: Review in progress

#16599 Migration: ZoomComponent
  ts/Accessibility/Accessibility.ts
  ts/Accessibility/Components/SeriesComponent/SeriesComponent.ts
  ts/Accessibility/Components/ZoomComponent.ts
  ts/masters/modules/accessibility.src.ts
Labels: Status: Review in progress

#16597 Bugfix #16549: Keyboard navigation in heatmap
  ts/Extensions/Boost/WGLRenderer.ts
  ts/Series/ColorMapComposition.ts
  ts/Series/ColorMapMixin.ts
  ts/Series/Heatmap/HeatmapPoint.ts
  ts/Series/Heatmap/HeatmapSeries.ts
  ts/Series/Map/MapPoint.ts
  ts/Series/Map/MapSeries.ts
  ts/Series/Treemap/TreemapSeries.ts
Labels: Changelog: Bugfix, Status: Review in progress, a11y

#16518 Feature/15653-bb-background-color
  samples/stock/indicators/indicator-area-fill/demo.details
  samples/stock/indicators/indicator-area-fill/demo.html
  samples/stock/indicators/indicator-area-fill/demo.js
  ts/Stock/Indicators/ABands/ABandsIndicator.ts
  ts/Stock/Indicators/Aroon/AroonIndicator.ts
  ts/Stock/Indicators/BB/BBIndicator.ts
  ts/Stock/Indicators/DMI/DMIIndicator.ts
  ts/Stock/Indicators/IKH/IKHIndicator.ts
  ts/Stock/Indicators/KeltnerChannels/KeltnerChannelsIndicator.ts
  ts/Stock/Indicators/Klinger/KlingerIndicator.ts
  ts/Stock/Indicators/MultipleLinesComposition.ts
  ts/Stock/Indicators/PC/PCIndicator.ts
  ts/Stock/Indicators/Stochastic/StochasticIndicator.ts
Labels: Changelog: Feature, Status: Review in progress

#16595 Created an icon for the editor page
  samples/highcharts/website/icon-editor/demo.css
  samples/highcharts/website/icon-editor/demo.details
  samples/highcharts/website/icon-editor/demo.html
  samples/highcharts/website/icon-editor/demo.js
Labels: Status: Review in progress

#16577 Demo: updated custom labels gantt demo
  samples/gantt/demo/custom-labels/demo.js
Labels: Status: Review in progress

#16523 Migration: LegendComponent
  package-lock.json
  samples/static/highslide.css
  ts/Accessibility/Accessibility.ts
  ts/Accessibility/Components/LegendComponent.ts
  ts/masters/modules/accessibility.src.ts
Labels: Status: Review in progress

#16653 Tools: Added chrome setup to CI nightly jobs.
  .circleci/config.yml
Labels: Status: Review in progress

#16642 Fixed #16562, Windows high contrast mode keyboard nav issues.
  ts/Accessibility/Accessibility.ts
Labels: Changelog: Bugfix

#16669 Fixed #16665, updating dataLabels.useHTML did not work
  samples/unit-tests/series-treemap/datalabels/demo.js
  ts/Core/Series/DataLabel.ts
Labels: Changelog: Bugfix

#16678 Linted, max-len below 95
  package-lock.json
  ts/.eslintrc
  ts/Accessibility/Components/LegendComponent.ts
  ts/Accessibility/Components/SeriesComponent/NewDataAnnouncer.ts
  ts/Accessibility/Components/ZoomComponent.ts
  ts/Accessibility/Options/DeprecatedOptions.ts
  ts/Accessibility/ProxyElement.ts
  ts/Accessibility/Utils/Announcer.ts
  ts/Core/Animation/Fx.ts
  ts/Core/Axis/GridAxis.ts
  ts/Core/Axis/OrdinalAxis.ts
  ts/Core/Axis/RadialAxis.ts
  ts/Core/Axis/ScrollbarAxis.ts
  ts/Core/Axis/StackingAxis.ts
  ts/Core/Axis/TreeGridAxis.ts
  ts/Core/Navigator.ts
  ts/Extensions/Annotations/ControlPoint.ts
  ts/Extensions/Annotations/Mixins/ControllableMixin.ts
  ts/Extensions/Annotations/NavigationBindings.ts
  ts/Extensions/Annotations/Popup.ts
  ts/Extensions/Annotations/Types/BasicAnnotation.ts
  ts/Extensions/Annotations/Types/Fibonacci.ts
  ts/Extensions/Annotations/Types/TimeCycles.ts
  ts/Extensions/Annotations/Types/Tunnel.ts
  ts/Extensions/Boost/BoostOverrides.ts
  ts/Extensions/DataGrouping.ts
  ts/Extensions/DownloadURL.ts
  ts/Extensions/Exporting/Exporting.ts
  ts/Extensions/OfflineExporting/OfflineExporting.ts
  ts/Extensions/Oldie/Oldie.ts
  ts/Extensions/RangeSelector.ts
  ts/Extensions/Sonification/SeriesSonify.ts
  ts/Series/Area/AreaSeries.ts
  ts/Series/Flags/FlagsSeries.ts
  ts/Series/HollowCandlestick/HollowCandlestickSeries.ts
  ts/Series/Map/MapSeries.ts
  ts/Series/Organization/OrganizationSeries.ts
  ts/Series/Sunburst/SunburstSeries.ts
  ts/Series/Treemap/TreemapSeries.ts
  ts/Series/Treemap/TreemapSeriesOptions.d.ts
  ts/Stock/Indicators/MultipleLinesComposition.ts
  ts/Stock/Indicators/PivotPoints/PivotPointsIndicator.ts
  ts/Stock/StockToolsBindings.ts
  ts/masters/modules/accessibility.src.ts
Labels: Status: Review in progress

#16683 Update demo.css
  samples/highcharts/website/static-candlestick/demo.css
Labels: Status: Review in progress

#16654 docs/maps-series-link
  docs/maps/map-series.md
Labels: Status: Review in progress

#16688 docs/annotations-images
  docs/advanced-chart-features/annotations-and-fibonacci-retracements.md
  docs/advanced-chart-features/annotations-module.md
  docs/advanced-chart-features/annotations-simple-label.png
  docs/advanced-chart-features/fibonacci-step-2.png
  docs/advanced-chart-features/fibonacci-step-3.png
  docs/advanced-chart-features/fibonacci-step-4.png
Labels: Product: Docs, Status: Review in progress

#16689 Update demo.css
  samples/highcharts/website/static-editor/demo.css
Labels: Status: Review in progress

#16693 docs/newdesign-changelog
  changelog/generate-html.js
Labels: Status: Review in progress

#16692 Added/removed data
  samples/highcharts/website/highcharts-timeline/demo.css
  samples/highcharts/website/highcharts-timeline/demo.html
  samples/highcharts/website/highcharts-timeline/demo.js
Labels: Status: Review in progress

#16695 Revert "Added/removed data"
  samples/highcharts/website/highcharts-timeline/demo.css
  samples/highcharts/website/highcharts-timeline/demo.html
  samples/highcharts/website/highcharts-timeline/demo.js
Labels: Status: Review in progress

#16700 Fixed #16679, hidden lists from a11y visible with global css.
  css/highcharts.scss
  ts/Accessibility/ProxyElement.ts
  ts/Accessibility/ProxyProvider.ts
Labels: Changelog: Bugfix

#16694 Added support for Trusted Types, #16667
  docs/chart-concepts/security.md
  package-lock.json
  package.json
  ts/Accessibility/Utils/Announcer.ts
  ts/Core/Chart/Chart.ts
  ts/Core/Renderer/HTML/AST.ts
  ts/Core/Utilities.ts
  ts/Extensions/Annotations/Popup.ts
  ts/Extensions/ExportData.ts
  ts/Extensions/OfflineExporting/OfflineExporting.ts
  ts/Maps/Projection.ts
  ts/tsconfig.json
Labels: Status: Review in progress

#16703 Docs: Fixed #16572, circular extends in OHLC/CandleStick options.
  test/typescript-dts/highstock/highstock.ts
  ts/Series/OHLC/OHLCSeries.ts
Labels: Product: Docs, Product: TypeScript

#16702 Fixed issue with data module updates with firstRowAsNames enabled.
  samples/unit-tests/data/general/demo.js
  ts/Extensions/Data.ts
Labels: Changelog: Bugfix, Status: Review in progress

#16711 Updated jingle bells sonification demo.
  samples/highcharts/studies/jingle-bells/demo.html
  samples/highcharts/studies/jingle-bells/demo.js
  samples/highcharts/studies/jingle-bells/readme.md
Labels: Status: Review in progress
