Repository highcharts/highcharts, pull requests merged in 2021-12, with the labels that each got.

#16726 Update demo.js
  samples/highcharts/website/homepage-2021/demo.js
Labels: Status: Review in progress

#16719 bugfix/16596-drag-column-category
  samples/unit-tests/dragdrop/dynamic/demo.js
  ts/Extensions/DraggablePoints.ts
Labels: Product: Highcharts, Changelog: Bugfix, Status: Review in progress

#16717 Fixed #16307, export menu button missing tooltip with a11y module.
  ts/Accessibility/Components/MenuComponent.ts
  ts/Accessibility/ProxyElement.ts
  ts/Accessibility/ProxyProvider.ts
Labels: Changelog: Bugfix

#16724 bugfix/16492-getbaseseriesmin-empty-xdata
  samples/unit-tests/navigator/navigator/demo.js
  ts/Core/Navigator.ts
Labels: Product: Highcharts Stock, Changelog: Bugfix, Status: Review in progress

#16748 Update the max-width: 800px;
  samples/highcharts/blog/simple-linear-graph/demo.css
  samples/highcharts/blog/simple-logarithmic-graph/demo.css
  samples/highcharts/blog/simple-logarithmic-linear-graph/demo.css
Labels: Status: Review in progress

#16745 Update demo.js
  samples/highcharts/website/homepage-2021/demo.js
Labels: Status: Review in progress

#16746 fix missing documentation for ToolTip.defaultFormater
  ts/Core/Tooltip.ts
Labels: Status: Review in progress

#16743 Fixed #16497, legend kbd nav cause page scroll with container scaling.
  ts/Accessibility/ProxyElement.ts
Labels: Changelog: Bugfix, Status: Review in progress

#16741 Fixed #16624, markers showing after hover after disabling a11y.
  samples/unit-tests/accessibility/forced-markers/demo.js
  ts/Accessibility/Components/SeriesComponent/ForcedMarkers.ts
  ts/Accessibility/Components/SeriesComponent/SeriesComponent.ts
Labels: Changelog: Bugfix

#16736 Fixed legend kbd issues #16520, #16545, #16467.
  ts/Accessibility/Components/LegendComponent.ts
  ts/Accessibility/ProxyProvider.ts
Labels: Changelog: Bugfix, Status: Review in progress

#16732 Fixed kbd nav issues #16633, #16634, #16625.
  ts/Accessibility/Components/RangeSelectorComponent.ts
  ts/Accessibility/Components/SeriesComponent/SeriesKeyboardNavigation.ts
  ts/Accessibility/KeyboardNavigation.ts
Labels: Changelog: Bugfix, Status: Review in progress

#16755 Docs/jsdoc cleanup
  ts/Core/Tooltip.ts
Labels: Product: Docs, Status: Review in progress

#16739 Fixed #16731, correct TS type for PlotAreasplineOptions.compare.
  ts/Series/DataModifyComposition.ts
Labels: Status: Review in progress

#16593 docs/maps-mapBubble
  docs/maps/mapbubble-series.md
  docs/sidebars.js
Labels: Product: Highcharts Maps, Status: Review in progress

#16763 bugfix/15203-symbol-hover-state
  ts/Core/Series/SeriesDefaults.ts
Labels: Product: Highcharts, Product: Docs, Status: Review in progress

#16761 Fixed issue with a11y module and drilldown on mobile.
  ts/Accessibility/Components/SeriesComponent/SeriesKeyboardNavigation.ts
Labels: Changelog: Bugfix, Status: Review in progress

#16766 Fixed #16589, SVG export broken with a11y module.
  samples/highcharts/exporting/offline-download/demo.html
  samples/unit-tests/accessibility/accessibility-exporting/demo.js
  ts/Accessibility/ProxyProvider.ts
Labels: Changelog: Bugfix, Status: Review in progress

#16771 feature/map-collection-1.1.4
  samples/mapdata/countries/no/no-all-all/demo.js
  samples/mapdata/countries/no/no-tf-all/demo.js
Labels: Product: Highcharts Maps, Status: Review in progress

#16770 bugfix/16439-grid-axis-missing-ticks
  ts/Core/Axis/GridAxis.ts
Labels: Product: Highcharts Gantt, Changelog: Bugfix

#15767 enhancement/12528-breadcrumbs-v2
  css/highcharts.scss
  samples/highcharts/3d/column-drilldown/demo.js
  samples/highcharts/accessibility/accessible-drilldown/demo.js
  samples/highcharts/breadcrumbs/format/demo.details
  samples/highcharts/breadcrumbs/format/demo.html
  samples/highcharts/breadcrumbs/format/demo.js
  samples/highcharts/breadcrumbs/single-button/demo.details
  samples/highcharts/breadcrumbs/single-button/demo.html
  samples/highcharts/breadcrumbs/single-button/demo.js
  samples/highcharts/breadcrumbs/standalone/demo.details
  samples/highcharts/breadcrumbs/standalone/demo.html
  samples/highcharts/breadcrumbs/standalone/demo.js
  samples/highcharts/chartchooser/categorical-comparison-sunburst-monochrome/demo.js
  samples/highcharts/chartchooser/categorical-comparison-sunburst/demo.js
  samples/highcharts/css/sunburst/demo.js
  samples/highcharts/css/treemap/demo.js
  samples/highcharts/demo/column-drilldown/demo.js
  samples/highcharts/demo/sunburst/demo.js
  samples/highcharts/demo/treemap-large-dataset/demo.js
  samples/highcharts/drilldown/drillupbutton/demo.js
  samples/highcharts/plotoptions/sunburst-datalabels-rotationmode-circular/demo.js
  samples/highcharts/plotoptions/sunburst-levelsize/demo.js
  samples/highcharts/plotoptions/sunburst-sliced/demo.js
  samples/highcharts/series-organization/drilldown/demo.js
  samples/maps/demo/map-drilldown/demo.js
  samples/unit-tests/breadcrumbs/breadcrumbs-in-treemap/demo.details
  samples/unit-tests/breadcrumbs/breadcrumbs-in-treemap/demo.html
  samples/unit-tests/breadcrumbs/breadcrumbs-in-treemap/demo.js
  samples/unit-tests/breadcrumbs/buttons/demo.details
  samples/unit-tests/breadcrumbs/buttons/demo.html
  samples/unit-tests/breadcrumbs/buttons/demo.js
  samples/unit-tests/breadcrumbs/events/demo.details
  samples/unit-tests/breadcrumbs/events/demo.html
  samples/unit-tests/breadcrumbs/events/demo.js
  samples/unit-tests/breadcrumbs/reserve-space/demo.details
  samples/unit-tests/breadcrumbs/reserve-space/demo.html
  samples/unit-tests/breadcrumbs/reserve-space/demo.js
  samples/unit-tests/drilldown/drillup/demo.js
  samples/unit-tests/drilldown/drillupbutton/demo.js
  samples/unit-tests/drilldown/resetzoom/demo.js
  samples/unit-tests/series-treemap/members/demo.js
  samples/unit-tests/series-treemap/zooming/demo.js
  test/typescript-dts/modules/drilldown.ts
  tools/gulptasks/jsdoc-classes.js
  ts/Accessibility/Accessibility.ts
  ts/Accessibility/Components/SeriesComponent/NewDataAnnouncer.ts
  ts/Accessibility/Components/SeriesComponent/SeriesKeyboardNavigation.ts
  ts/Accessibility/Components/ZoomComponent.ts
  ts/Core/Series/Series.ts
  ts/Extensions/Breadcrumbs.ts
  ts/Extensions/Drilldown.ts
  ts/Extensions/ScrollablePlotArea.ts
  ts/Maps/MapNavigationOptions.d.ts
  ts/Series/Sunburst/SunburstSeries.ts
  ts/Series/Treemap/TreemapSeries.ts
  ts/masters/modules/drilldown.src.ts
  ts/masters/modules/treemap.src.ts
Labels: Changelog: Feature, Status: Review in progress

#16774 bugfix/16448-anotations-events-api
  ts/Extensions/Annotations/Annotations.ts
Labels: Product: Highcharts, Product: Docs, Status: Review in progress

#16773 bugfix/16673-treeGrid-destroy-icon
  samples/unit-tests/gantt/treegrid/demo.js
  ts/Core/Axis/TreeGridTick.ts
Labels: Product: Highcharts Gantt, Changelog: Bugfix, Status: Review in progress

#16781 Fixed html error for xmas card
  samples/highcharts/website/xmas-2021/demo.html
Labels: Status: Review in progress

#16636 Fixed: #15782, export hamburger icon hiding behind mapNavButtons.
  samples/unit-tests/chart/chart-update-mapnavigation/demo.js
  samples/unit-tests/maps/map-navigation/demo.js
  samples/unit-tests/maps/setdata/demo.js
  ts/Accessibility/Components/ZoomComponent.ts
  ts/Maps/MapNavigation.ts
Labels: Product: Highcharts Maps, Changelog: Bugfix, Status: Review in progress

#16802 Added back to Highcharts link
  samples/highcharts/website/xmas-2021/demo.css
  samples/highcharts/website/xmas-2021/demo.html
  samples/highcharts/website/xmas-2021/demo.js
Labels: Status: Review in progress

#16803 bugfix/16800-breadcrumbs-not-showing-names
  ts/Extensions/Breadcrumbs.ts
  ts/Extensions/Drilldown.ts
Labels: Status: Review in progress

#16811 Map projection clipBounds
  samples/highcharts/studies/projection/demo.js
  ts/Maps/MapViewOptionsDefault.ts
  ts/Maps/Projection.ts
  ts/Maps/ProjectionOptions.d.ts
  ts/Maps/Projections/LambertConformalConic.ts
Labels: Status: Review in progress

#16812 website/font fix for xmas card
  samples/highcharts/website/xmas-2021/demo.css
Labels: Status: Review in progress
