Repository highcharts/highcharts, pull requests merged in 2021-09, with the labels that each got.

#16005 bugfix/16004-shared-tooltip-multiple-axes
  samples/unit-tests/tooltip/shared/demo.js
  ts/Core/Tooltip.ts
Labels: Changelog: Bugfix, Status: Review in progress

#16182 Migration: ChartUtilities
  ts/Accessibility/Accessibility.ts
  ts/Accessibility/Utils/ChartUtilities.ts
Labels: Status: Review in progress

#16281 Update render-charts-serverside.md
  docs/export-module/legacy-export-servers.md
  docs/export-module/render-charts-serverside.md
Labels: Status: Review in progress

#16280 feature/change-new-until-in-hlc
  samples/stock/demo/hlc/demo.details
Labels: Product: Highcharts Stock, Changelog: Feature, Status: Review in progress

#16294 bugfix/15656-wheel
  ts/Maps/MapPointer.ts
Labels: Changelog: Bugfix, Status: Review in progress

#16156 enhancement/15696-indicator-on-indicator
  test/cypress/integration/Highcharts/stock-tools.spec.js
  test/cypress/support/index.js
  ts/Extensions/Annotations/Popup.ts
Labels: Type: Enhancement, Product: Highcharts Stock, Status: Review in progress

#16290 docs/fix-demo-link
  docs/advanced-chart-features/annotations-module.md
Labels: Product: Docs, Status: Review in progress

#16302 Migration: NelderMead
  samples/unit-tests/series-venn/members/demo.js
  ts/Mixins/NelderMead.ts
  ts/Series/Venn/VennSeries.ts
  ts/Series/Venn/VennUtils.ts
Labels: Status: Review in progress

#15580 Fixed #12537, packedBubble incorrect color/linewidth after dehover.
  samples/unit-tests/series-packedbubble/positions/demo.js
  ts/Series/PackedBubble/PackedBubblePoint.ts
  ts/Series/PackedBubble/PackedBubbleSeries.ts
Labels: Type: Bug, Product: Highcharts, Status: Review in progress

#15770 bugfix/15727-annotation-popup-input-selection
  test/cypress/integration/Highcharts/stock-tools.spec.js
  ts/Extensions/Annotations/Popup.ts
Labels: Product: Highcharts Stock, Changelog: Bugfix, Status: Review in progress

#16097 enhancement/15497-gui-pivot-points-dropdown
  test/cypress/integration/Highcharts/stock-tools.spec.js
  test/cypress/support/index.js
  ts/Extensions/Annotations/Popup.ts
Labels: Type: Enhancement, Product: Highcharts Stock, Status: Review in progress

#16303 bugfix/15931-docs-dataFormat-link
  docs/chart-concepts/axes.md
  docs/chart-concepts/labels-and-string-formatting.md
  ts/Accessibility/Options/Options.ts
  ts/Core/Axis/AxisDefaults.ts
  ts/Core/DefaultOptions.ts
  ts/Extensions/CurrentDateIndication.ts
Labels: Product: Docs, Status: Review in progress

#16304 Migration: PointSonify
  package-lock.json
  ts/Extensions/Sonification/ChartSonify.ts
  ts/Extensions/Sonification/PointSonify.ts
  ts/Extensions/Sonification/SeriesSonify.ts
  ts/Extensions/Sonification/Sonification.ts
  ts/Extensions/Sonification/SonificationOptions.d.ts
  ts/Extensions/Sonification/SonificationUtilities.ts
  ts/Extensions/Sonification/Timeline.ts
  ts/masters/modules/sonification.src.ts
Labels: Status: Review in progress

#16305 Tools: Extended CI filesize monitoring
  tools/gulptasks/pr-size-table.js
Labels: Status: Review in progress

#16317 Samples: Nicer HTML tooltip demo
  samples/highcharts/tooltip/footerformat/demo.css
  samples/highcharts/tooltip/footerformat/demo.html
  samples/highcharts/tooltip/footerformat/demo.js
Labels: Status: Review in progress

#15872 bugfix/13868-hovering-pie-in-stock
  samples/unit-tests/series-flags/tooltip/demo.js
  samples/unit-tests/series-pie/pie/demo.html
  samples/unit-tests/series-pie/pie/demo.js
  samples/unit-tests/tooltip/split/demo.js
  ts/Core/Chart/StockChart.ts
  ts/Core/Series/Point.ts
  ts/Core/Series/Series.ts
  ts/Core/Tooltip.ts
  ts/Series/Sankey/SankeySeries.ts
Labels: Product: Highcharts Stock, Changelog: Bugfix, Status: Review in progress

#16321 bugfix/13683-legend-nav-pages
  samples/unit-tests/legend/navigation/demo.details
  samples/unit-tests/legend/navigation/demo.html
  samples/unit-tests/legend/navigation/demo.js
  ts/Core/Legend/Legend.ts
Labels: Changelog: Bugfix, Status: Review in progress

#16326 Stock Tools: corrected "langKey" for crooked5 annotation
  ts/Stock/StockToolsBindings.ts
Labels: Product: Highcharts Stock, Changelog: Bugfix, Status: Review in progress

#16330 Fixed #16329, unable to deep-merge treemap levels
  samples/highcharts/demo/treemap-large-dataset/demo.js
  ts/Mixins/TreeSeries.ts
Labels: Status: Review in progress

#16325 New feature: crop for annotation
  samples/highcharts/annotations/label-crop-overflow/demo.js
  ts/Extensions/Annotations/Annotations.ts
Labels: Changelog: Feature, Status: Review in progress

#16338 Fixed #12169, allow Blob offline export in Firefox.
  ts/Extensions/OfflineExporting/OfflineExporting.ts
Labels: Changelog: Bugfix, Status: Review in progress

#16340 docs/16296-iframe-dataGrouping
  docs/stock/data-grouping.md
Labels: Product: Highcharts Stock, Product: Docs, Status: Review in progress

#16348 bugfix/16139-arrow-infinity-line-lang
  ts/Stock/StockToolsGui.ts
Labels: Product: Highcharts Stock, Changelog: Bugfix, Status: Review in progress

#16364 Migration: Wordcloud polygons
  ts/Core/Renderer/PolygonBoxObject.d.ts
  ts/Mixins/Polygon.ts
  ts/Series/Venn/VennSeries.ts
  ts/Series/Wordcloud/WordcloudPoint.ts
  ts/Series/Wordcloud/WordcloudSeries.ts
  ts/Series/Wordcloud/WordcloudUtils.ts
Labels: Status: Review in progress

#16375 origin hotfix/cypress-test
  test/cypress/integration/Highcharts/stock-tools.spec.js
Labels: Status: Review in progress

#16374 Tools: fixed filesize script eating stash and added TS compilation
  tools/gulptasks/unsorted/filesize.js
Labels: Status: Review in progress

#16020 feature/15361-stock-cumulative-sum
  samples/stock/demo/cumulative-sum/demo.details
  samples/stock/demo/cumulative-sum/demo.html
  samples/stock/demo/cumulative-sum/demo.js
  samples/stock/members/axis-setcumulative/demo.details
  samples/stock/members/axis-setcumulative/demo.html
  samples/stock/members/axis-setcumulative/demo.js
  samples/stock/plotoptions/series-cumulative-sum/demo.details
  samples/stock/plotoptions/series-cumulative-sum/demo.html
  samples/stock/plotoptions/series-cumulative-sum/demo.js
  samples/unit-tests/series/compare/demo.js
  samples/unit-tests/series/cumulative/demo.details
  samples/unit-tests/series/cumulative/demo.html
  samples/unit-tests/series/cumulative/demo.js
  ts/Core/Chart/StockChart.ts
  ts/Core/DefaultOptions.ts
  ts/Core/Series/DataExtremesObject.d.ts
  ts/Core/Series/Series.ts
  ts/Series/AreaRange/AreaRangeSeries.ts
  ts/Series/DataModifyComposition.ts
  ts/Series/HLC/HLCSeries.ts
  ts/Stock/Indicators/MultipleLinesComposition.ts
  ts/Stock/Indicators/SMA/SMAIndicator.ts
  ts/masters/modules/stock.src.ts
Labels: Product: Highcharts Stock, Changelog: Feature, Status: Review in progress

#16394 Samples: Fixed crashing test on studies
  samples/highcharts/studies/parliament-improved/demo.js
Labels: Status: Review in progress

#16407 Migration: A11y FocusBorder
  ts/Accessibility/Accessibility.ts
  ts/Accessibility/FocusBorder.ts
  ts/masters/modules/accessibility.src.ts
Labels: Status: Review in progress

#16396 Migration: A11yI18n
  ts/Accessibility/A11yI18n.ts
  ts/Accessibility/Accessibility.ts
  ts/Accessibility/Components/InfoRegionsComponent.ts
  ts/Accessibility/Utils/HTMLUtilities.ts
  ts/masters/modules/accessibility.src.ts
Labels: Status: Review in progress

#16416 bugfix/meteogram-tooltip
  samples/highcharts/demo/combo-meteogram/demo.js
Labels: Product: Highcharts, Status: Review in progress

#16419 Tools: removed demos deploy from nightly
  .circleci/scripts/check_and_trigger_samples_deploy.sh
Labels: Status: Review in progress

#16406 Docs/revise understanding highcharts
  docs/chart-concepts/understanding-highcharts.md
Labels: Status: Review in progress

#14432 bugfix/13780-tooltip-reversed-y
  samples/unit-tests/axis/reversed/demo.js
  ts/Core/Tooltip.ts
  ts/Series/MapBubble/MapBubblePoint.ts
  ts/Series/XRange/XRangePoint.ts
Labels: Status: Pending review, Changelog: Bugfix

#16413 Migration: AccessibilityComponent
  ts/Accessibility/Accessibility.ts
  ts/Accessibility/AccessibilityComponent.ts
  ts/masters/modules/accessibility.src.ts
Labels: Status: Review in progress

#16207 feature/15008-ellipse-annotation
  samples/highcharts/annotations-advanced/controllable/demo.js
  samples/highcharts/annotations/ellipse/demo.css
  samples/highcharts/annotations/ellipse/demo.details
  samples/highcharts/annotations/ellipse/demo.html
  samples/highcharts/annotations/ellipse/demo.js
  samples/highcharts/annotations/gui-buttons/demo.css
  samples/highcharts/annotations/gui-buttons/demo.html
  samples/highcharts/annotations/gui/demo.css
  samples/highcharts/annotations/gui/demo.html
  samples/stock/demo/stock-tools-custom-gui/demo.css
  samples/stock/demo/stock-tools-custom-gui/demo.html
  samples/unit-tests/stock-tools/bindings/demo.js
  test/cypress/integration/Highcharts/annotations/ellipse/ellipse.spec.js
  ts/Extensions/Annotations/Annotations.ts
  ts/Extensions/Annotations/Controllables/ControllableEllipse.ts
  ts/Extensions/Annotations/Mixins/ControllableMixin.ts
  ts/Extensions/Annotations/NavigationBindings.ts
  ts/Extensions/Annotations/Types/BasicAnnotation.ts
  ts/Series/HeikinAshi/HeikinAshiSeries.ts
  ts/Stock/StockToolsGui.ts
Labels: Product: Highcharts Stock, Changelog: Feature, Status: Review in progress
