Repository highcharts/highcharts, pull requests merged in 2021-08, with the labels that each got.

#16186 Tools: Fixed path to PlotLineOrBand in jsdoc-classes.
  tools/gulptasks/jsdoc-classes.js
Labels: Status: Review in progress

#15748 bugfix/15729-annotation-drag-selected
  test/cypress/integration/Highcharts/stock-tools.spec.js
  test/cypress/support/index.js
  ts/Extensions/Annotations/Mixins/EventEmitterMixin.ts
  ts/Extensions/Annotations/NavigationBindings.ts
Labels: Product: Highcharts Stock, Changelog: Bugfix, Status: Review in progress

#16028 Fixed #15229, avoid duplicate a11y region labels.
  ts/Accessibility/Components/InfoRegionsComponent.ts
  ts/Accessibility/Components/LegendComponent.ts
  ts/Accessibility/Components/MenuComponent.ts
  ts/Accessibility/Options/LangOptions.ts
Labels: Changelog: Bugfix, Status: Review in progress

#16039 bugfix/16036-vbp-indicator-volumeDivision-graphic
  samples/unit-tests/indicator-volume-by-price/recalculations/demo.js
  ts/Stock/Indicators/VBP/VBPIndicator.ts
Labels: Product: Highcharts Stock, Changelog: Bugfix, Status: Review in progress

#16046 bugfix/16042-xrange-gaps
  ts/Series/XRange/XRangeSeries.ts
Labels: Changelog: Bugfix, Status: Review in progress

#16051 bugfix/16044-draggable-guide-size
  ts/Extensions/DraggablePoints.ts
Labels: Changelog: Bugfix, Status: Review in progress

#15965 Migration: DataLabel
  ts/Core/Legend.ts
  ts/Core/Renderer/RendererUtilities.ts
  ts/Core/Series/DataLabel.ts
  ts/Core/Series/DataLabels.ts
  ts/Core/Tooltip.ts
  ts/Mixins/LegendSymbol.ts
  ts/Series/Column/ColumnDataLabel.ts
  ts/Series/Column/ColumnSeries.ts
  ts/Series/Flags/FlagsSeries.ts
  ts/Series/Pie/PieDataLabel.ts
  ts/masters/highcharts.src.ts
Labels: Product: Highcharts, Status: Review in progress

#16056 Feature template typo.
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: Status: Review in progress

#16057 bugfix/16053-colorAxis-show-hide-legend
  samples/unit-tests/coloraxis/coloraxis-update/demo.js
  ts/Core/Axis/Color/ColorAxis.ts
Labels: Changelog: Bugfix, Status: Review in progress

#16063 bugfix/16062-useHTML-line-break-align
  samples/unit-tests/svgrenderer/text/demo.js
  ts/Core/Renderer/SVG/SVGRenderer.ts
Labels: Changelog: Bugfix, Status: Review in progress

#16061 bugfix/15453-gantt-scroll-ticks
  ts/Core/Axis/GridAxis.ts
Labels: Product: Highcharts Gantt, Changelog: Bugfix, Status: Review in progress

#16073 bugfix/15334-waterfall-negative-dataLabels
  samples/unit-tests/series-waterfall/waterfall/demo.js
  ts/Series/Waterfall/WaterfallSeries.ts
Labels: Changelog: Bugfix, Status: Review in progress

#16109 bugfix/16104-category-update-warning
  ts/Core/Series/Series.ts
Labels: Changelog: Bugfix, Status: Review in progress

#16113 bugfix/16112-polar-axis-array-setOptions
  samples/unit-tests/series-solidgauge/solidgauge/demo.js
  ts/Core/Axis/RadialAxis.ts
Labels: Changelog: Bugfix, Status: Review in progress

#16117 docs/15596-sunburst-rotation-api-path
  ts/Series/Sunburst/SunburstSeries.ts
Labels: Product: Docs, Status: Review in progress

#16123 Docs: TypeScript examples
  docs/advanced-chart-features/highcharts-typescript-declarations.md
Labels: Status: Review in progress

#16128 bugfix/16126-a11y-full-screen-print-error
  ts/Accessibility/Utils/ChartUtilities.ts
Labels: Changelog: Bugfix, Status: Review in progress

#15987 bugfix/15970-ordinal-annotation
  samples/unit-tests/axis/ordinal/demo.js
  samples/unit-tests/series/datagrouping/demo.js
  ts/Core/Axis/OrdinalAxis.ts
  ts/Extensions/DataGrouping.ts
Labels: Product: Highcharts Stock, Changelog: Bugfix, Status: Review in progress

#16133 bugfix/16055-panning-mobile-extendedOrdinalPositions
  samples/unit-tests/axis/ordinal/demo.js
  ts/Core/Axis/OrdinalAxis.ts
Labels: Product: Highcharts Stock, Changelog: Bugfix, Status: Review in progress

#16154 bugfix/16153-chart-update-style-fontFamily-reset
  samples/unit-tests/chart/chart-update/demo.js
  ts/Core/Chart/Chart.ts
Labels: Changelog: Bugfix, Status: Review in progress

#16157 bugfix/16146-sunburst-negative
  ts/Mixins/TreeSeries.ts
Labels: Changelog: Bugfix, Status: Review in progress

#16170 docs/14552/treemap-pointPadding-docs-error
  ts/Series/Treemap/TreemapSeries.ts
Labels: Product: Docs, Status: Review in progress

#16178 Migration: Announcer
  ts/Accessibility/Utils/Announcer.ts
Labels: Status: Review in progress

#16120 bugfix/16119-touch-zoom-scroll-blocking
  ts/Core/Pointer.ts
Labels: Changelog: Bugfix, Status: Review in progress

#16196 hotfix/16195-article-demo-fix
  samples/stock/indicators/custom-regression-multiple-lines/demo.js
Labels: Product: Highcharts Stock, Priority: Blocker, Status: Review in progress

#15944 enhancement/15347-hollow-candlestick
  css/highcharts.scss
  docs/chart-design-and-style/style-by-css.md
  docs/sidebars.js
  docs/stock/hollow-candlestick-chart.md
  docs/stock/hollow-candlestick.png
  samples/highcharts/css/hollow-candlestick/demo.css
  samples/highcharts/css/hollow-candlestick/demo.details
  samples/highcharts/css/hollow-candlestick/demo.html
  samples/highcharts/css/hollow-candlestick/demo.js
  samples/stock/demo/hollow-candlestick/demo.details
  samples/stock/demo/hollow-candlestick/demo.html
  samples/stock/demo/hollow-candlestick/demo.js
  samples/stock/plotoptions/hollow-candlestick-color/demo.details
  samples/stock/plotoptions/hollow-candlestick-color/demo.html
  samples/stock/plotoptions/hollow-candlestick-color/demo.js
  test/karma-files.json
  ts/Series/HollowCandlestick/HollowCandlestickPoint.ts
  ts/Series/HollowCandlestick/HollowCandlestickPointOptions.d.ts
  ts/Series/HollowCandlestick/HollowCandlestickSeries.ts
  ts/Series/HollowCandlestick/HollowCandlestickSeriesOptions.d.ts
  ts/Series/Line/LinePoint.d.ts
  ts/Stock/StockToolsBindings.ts
  ts/Stock/StockToolsGui.ts
  ts/masters/modules/hollowcandlestick.src.ts
  ts/masters/modules/stock.src.ts
Labels: Product: Highcharts Stock, Status: Review in progress

#16199 bugfix/missing-series-in-demo
  samples/stock/demo/stock-tools-gui/demo.html
Labels: Type: Pre-release, Product: Highcharts Stock, Priority: Blocker, Changelog: Bugfix, Status: Review in progress

#16197 Fixed composition dependencies of datalabels.
  ts/Core/Series/DataLabel.ts
  ts/Series/Column/ColumnDataLabel.ts
  ts/Series/Pie/PieDataLabel.ts
Labels: Priority: Blocker

#16204 Tools: Fixed file list of JSDoc classes.
  tools/gulptasks/jsdoc-classes.js
Labels: Product: Docs

#16205 bugfix/candlestick-point-up-color
  css/highcharts.scss
Labels: Type: Pre-release, Product: Highcharts Stock, Priority: Blocker, Changelog: Bugfix, Status: Review in progress

#16206 bugfix/ordinal-grouping-visual-differences
  ts/Core/Axis/OrdinalAxis.ts
Labels: Type: Pre-release, Product: Highcharts Stock, Priority: Blocker, Changelog: Bugfix, Status: Review in progress

#16209 regression/point-update-pie
  ts/Core/Series/Point.ts
  ts/Series/OHLC/OHLCPoint.ts
Labels: Priority: Blocker, Status: Review in progress

#16221 bugfix/hollowcandlestick-line-color
  ts/Series/HollowCandlestick/HollowCandlestickPoint.ts
  ts/Series/HollowCandlestick/HollowCandlestickSeries.ts
Labels: Product: Highcharts Stock, Priority: Blocker, Changelog: Bugfix, Status: Review in progress

#16223 Samples: Fixed JSON source
  samples/maps/chart/topojson/demo.js
Labels: Priority: Blocker, Status: Review in progress

#16225 Fixed nested whitespace in HTML
  samples/unit-tests/svgrenderer/label/demo.js
  ts/Core/Renderer/HTML/AST.ts
  ts/Core/Renderer/SVG/TextBuilder.ts
Labels: Changelog: Bugfix, Status: Review in progress

#16240 hotfix/docs-config-compare-cumulative
  docs/sidebars.js
Labels: Priority: Blocker, Status: Review in progress

#16242 bugfix/16231-export-styledMode
  samples/unit-tests/exporting/styled-mode/demo.js
  ts/Extensions/Exporting/Exporting.ts
  ts/Extensions/OfflineExporting/OfflineExporting.ts
Labels: Changelog: Bugfix, Status: Review in progress

#16252 bugfix/16176-funnel-dataLabel-rotation
  samples/unit-tests/series-funnel/funnel/demo.js
  ts/Series/Funnel/FunnelSeries.ts
Labels: Changelog: Bugfix, Status: Review in progress

#16145 bugfix/16143-hidden-boost-local-export
  ts/Extensions/OfflineExporting/OfflineExporting.ts
Labels: Changelog: Bugfix, Status: Review in progress

#16273 Docs: renamed image extension
  docs/stock/compare-percent.png
  docs/stock/cumulative-sum.png
Labels: Status: Review in progress

#16227 Migration: ColorAxisComposition
  ts/Core/Axis/Color/ColorAxis.ts
  ts/Core/Axis/Color/ColorAxisComposition.ts
  ts/Mixins/ColorSeries.ts
  ts/Series/ColorMapComposition.ts
  ts/Series/Map/MapSeriesOptions.d.ts
  ts/Series/Tilemap/TilemapPoint.ts
  ts/Series/Treemap/TreemapSeries.ts
Labels: Status: Review in progress

#16269 Improvements to series keyboard navigation.
  ts/Accessibility/AccessibilityComponent.ts
  ts/Accessibility/Components/SeriesComponent/SeriesKeyboardNavigation.ts
Labels: Changelog: Feature, Status: Review in progress

#15910 Feature/15346-new-series-hlc
  docs/sidebars.js
  docs/stock/hlc-chart.md
  docs/stock/hlc-chart.png
  docs/stock/ohlc-chart.md
  samples/stock/demo/hlc/demo.details
  samples/stock/demo/hlc/demo.html
  samples/stock/demo/hlc/demo.js
  samples/stock/plotoptions/hlc-linewidth/demo.details
  samples/stock/plotoptions/hlc-linewidth/demo.html
  samples/stock/plotoptions/hlc-linewidth/demo.js
  samples/stock/plotoptions/hlc-pointvalkey/demo.details
  samples/stock/plotoptions/hlc-pointvalkey/demo.html
  samples/stock/plotoptions/hlc-pointvalkey/demo.js
  samples/unit-tests/series-ohlc/points/demo.js
  test/ts-node-unit-tests/tests/modules.test.ts
  ts/Extensions/DataGrouping.ts
  ts/Series/Candlestick/CandlestickSeries.ts
  ts/Series/HLC/HLCPoint.ts
  ts/Series/HLC/HLCPointOptions.d.ts
  ts/Series/HLC/HLCSeries.ts
  ts/Series/HLC/HLCSeriesOptions.d.ts
  ts/Series/OHLC/OHLCPoint.ts
  ts/Series/OHLC/OHLCPointOptions.d.ts
  ts/Series/OHLC/OHLCSeries.ts
  ts/Series/OHLC/OHLCSeriesOptions.d.ts
  ts/Stock/Indicators/SMA/SMAComposition.ts
  ts/Stock/StockToolsBindings.ts
  ts/Stock/StockToolsGui.ts
  ts/masters/modules/stock.src.ts
Labels: Product: Highcharts Stock, Changelog: Feature, Status: Review in progress
