Repository highcharts/highcharts, pull requests merged in 2021-07, with the labels that each got.

#15990 bugfix/15235-ast-whitespace
  samples/unit-tests/svgrenderer/label/demo.js
  ts/Core/Renderer/HTML/AST.ts
Labels: Changelog: Bugfix, Status: Review in progress

#15954 bugfix/15952-annotation-control-point-afterUpdate
  samples/unit-tests/annotations/annotations-events/demo.html
  samples/unit-tests/annotations/annotations-events/demo.js
  ts/Extensions/Annotations/Mixins/EventEmitterMixin.ts
Labels: Changelog: Bugfix, Product: Highcharts Stock, Status: Review in progress

#15985 bugfix/15983-update-remove-event
  samples/unit-tests/axis/events/demo.js
  ts/Core/Foundation.ts
Labels: Changelog: Bugfix, Status: Review in progress

#15972 bugfix/13840-3d-column-scroll-corner
  ts/Series/Column3D/Column3DComposition.ts
Labels: Changelog: Bugfix, Status: Review in progress

#15988 bugfix/15986-exit-anchor-chart-update
  samples/unit-tests/accessibility/accessibility-options/demo.js
  ts/Accessibility/Components/InfoRegionsComponent.ts
Labels: Changelog: Bugfix, Status: Review in progress

#15738 bugfix/15730-popup-toolbar-hide-annotation
  samples/unit-tests/annotations/annotations-events/demo.js
  test/cypress/integration/Highcharts/stock-tools.spec.js
  test/cypress/support/index.js
  ts/Extensions/Annotations/Annotations.ts
  ts/Extensions/Annotations/Popup.ts
  ts/Stock/StockToolsGui.ts
Labels: Changelog: Bugfix, Product: Highcharts Stock, Status: Review in progress

#15837 bugfix/15777-plotLine-label-clip
  ts/Core/Axis/PlotLineOrBand.ts
Labels: Changelog: Bugfix, Status: Review in progress

#15750 bugfix/15726-annotation-rect-clip
  samples/unit-tests/annotations/annotations-dynamic/demo.js
  ts/Extensions/Annotations/Annotations.ts
Labels: Changelog: Bugfix, Product: Highcharts Stock, Status: Review in progress

#15981 bugfix/1441-dateTime-tickPositions-format
  samples/unit-tests/tooltip/sub-millisec-tooltip/demo.js
  ts/Accessibility/Components/SeriesComponent/SeriesDescriber.ts
  ts/Core/Axis/DateTimeAxis.ts
  ts/Core/Axis/Tick.ts
  ts/Core/Series/Point.ts
  ts/Core/Time.ts
  ts/Core/Tooltip.ts
  ts/Extensions/DataGrouping.ts
  ts/Series/Gantt/GanttSeries.ts
Labels: Changelog: Bugfix, Status: Review in progress

#16013 Migration: Responsive
  package-lock.json
  ts/Core/Responsive.ts
Labels: Product: Highcharts, Status: Review in progress

#15993 Migration: DefaultOptions
  ts/Core/DefaultOptions.ts
Labels: Status: Review in progress

#15995 Migration: LangOptions
  ts/Core/LangOptions.d.ts
Labels: Product: Highcharts, Status: Review in progress

#15996 Migration: Time
  ts/Core/Time.ts
Labels: Status: Review in progress

#15997 Migration: Tooltip
  ts/Core/Tooltip.ts
  ts/Core/TooltipOptions.d.ts
Labels: Status: Review in progress
