Repository highcharts/highcharts, pull requests merged in 2021-06, with the labels that each got.

#15813 Migration: Axis3D
  ts/Core/Axis/Axis3D.ts
  ts/Extensions/Oldie/Oldie.ts
  ts/Extensions/Oldie/VMLAxis3D.ts
Labels: Product: Highcharts, Status: Review in progress

#15493 Tools: Updated readme of TS sources.
  ts/README.md
Labels: Product: TypeScript, Status: Review in progress

#15822 tools/watch-css
  tools/gulptasks/scripts-watch.js
Labels: Status: Review in progress

#15823 Docs: styled mode geometrics
  docs/chart-design-and-style/style-by-css.md
Labels: Product: Docs, Status: Review in progress

#15830 Tools: Fixed ESLint rule no-highcharts-object
  package-lock.json
  package.json
  ts/Extensions/Debugger/Debugger.ts
Labels: Status: Review in progress

#15831 Fixed serif font in demos on a11y portal.
  samples/highcharts/accessibility/accessible-line/demo.css
  samples/highcharts/accessibility/art-grants/demo.css
  samples/highcharts/sonification/chart-earcon/demo.css
Labels: Status: Review in progress

#15834 Better legend a11y by placing elements in a list.
  ts/Accessibility/Components/LegendComponent.ts
Labels: Changelog: Feature, Status: Review in progress

#15824 Fixed issue with extraneous table caption HTML encoding.
  ts/Extensions/ExportData.ts
Labels: Changelog: Bugfix, Status: Review in progress

#15707 bugfix/15701-tooltip-fontSize
  ts/Core/Renderer/SVG/SVGElement.ts
  ts/Core/Renderer/SVG/SVGLabel.ts
  ts/Core/Renderer/SVG/TextBuilder.ts
Labels: Changelog: Bugfix, Status: Review in progress

#15704 bugfix/13238-panning-ordinal-lin2val-refactoring
  samples/unit-tests/axis/breaks/demo.js
  samples/unit-tests/axis/ordinal/demo.js
  ts/Core/Axis/Axis.ts
  ts/Core/Axis/OrdinalAxis.ts
Labels: Changelog: Bugfix, Product: Highcharts Stock, Status: Review in progress

#15858 bugfix/15843-tooltip-shared-stickOnContact
  samples/unit-tests/tooltip/shared/demo.js
  ts/Core/Tooltip.ts
Labels: Changelog: Bugfix, Status: Review in progress

#15850 bugfix/15845-selection-marker-export
  ts/Core/Globals.ts
Labels: Changelog: Bugfix, Status: Review in progress

#15856 Expose Point.doDrilldown
  samples/highcharts/drilldown/programmatic/demo.css
  samples/highcharts/drilldown/programmatic/demo.details
  samples/highcharts/drilldown/programmatic/demo.html
  samples/highcharts/drilldown/programmatic/demo.js
  ts/Extensions/Drilldown.ts
Labels: Changelog: Feature, Status: Review in progress

#15875 Update labels-and-string-formatting.md
  docs/chart-concepts/labels-and-string-formatting.md
Labels: Status: Review in progress

#15857 Fixed #6173, CSP errors on tooltip drop shadow in styled mode
  ts/Core/Renderer/SVG/SVGAttributes.d.ts
  ts/Core/Tooltip.ts
Labels: Status: Review in progress

#15860 bugfix/15841-Intl-missing
  ts/Core/Time.ts
Labels: Changelog: Bugfix, Status: Review in progress

#15832 bugfix/15728-indicator-popup-scroll
  css/annotations/popup.scss
  ts/Extensions/Annotations/Popup.ts
Labels: Changelog: Bugfix, Product: Highcharts Stock, Status: Review in progress

#15871 bugfix/15869-boost-multiple-types
  ts/Extensions/Boost/WGLRenderer.ts
Labels: Changelog: Bugfix, Status: Review in progress

#15693 tools/cypress-setup
  .circleci/config.yml
  .eslintignore
  .gitignore
  cypress.json
  package-lock.json
  package.json
  test/cypress/integration/Highcharts/example.spec.js
  test/cypress/jsconfig.json
  test/cypress/readme.md
  test/cypress/support/index.js
Labels: Status: Review in progress

#15879 Expose Series.searchPoint
  ts/Core/Series/Series.ts
Labels: Status: Review in progress

#15905 Removed nightly trigger for demo deploy from ci config
  .circleci/config.yml
Labels: Status: Review in progress

#15916 test/15845
  samples/unit-tests/exporting/getsvg/demo.js
Labels: Status: Review in progress

#15914 Migration: LineSeries
  ts/Extensions/DataGrouping.ts
  ts/Series/Line/LinePoint.d.ts
  ts/Series/Line/LineSeries.ts
Labels: Product: Highcharts, Status: Review in progress

#15917 Migration: ColumnSeries
  ts/Series/Column/ColumnPoint.d.ts
  ts/Series/Column/ColumnSeries.ts
Labels: Status: Review in progress

#15912 bugfix/15909-pie-dataLabel-useHTML-visible
  samples/unit-tests/series-pie/datalabel/demo.js
  ts/Core/Renderer/HTML/HTMLRenderer.ts
Labels: Changelog: Bugfix, Status: Review in progress

#15893 bugfix/5430-state-marker-zone-color
  samples/unit-tests/series/marker/demo.js
  ts/Core/Series/Point.ts
Labels: Changelog: Bugfix, Status: Review in progress

#15923 bugfix/9047-boost-primcount-zero
  ts/Extensions/Boost/WGLRenderer.ts
  ts/Extensions/Boost/WGLVBuffer.ts
Labels: Changelog: Bugfix, Status: Review in progress

#15927 Refactored Chart.getSelectedPoints
  ts/Core/Chart/Chart.ts
Labels: Status: Review in progress

#15887 Migration: Tooltip
  ts/Core/Tooltip.ts
  ts/Core/TooltipOptions.d.ts
  ts/Extensions/DataGrouping.ts
  ts/masters/highcharts.src.ts
Labels: Product: Highcharts, Status: Review in progress

#15924 Migration: DateTimeAxis
  package-lock.json
  package.json
  ts/Core/Axis/DateTimeAxis.ts
  ts/Core/Axis/OrdinalAxis.ts
  ts/Core/Axis/StackingAxis.ts
  ts/Core/Renderer/SVG/ButtonThemeObject.d.ts
  ts/Extensions/DataGrouping.ts
  ts/masters/highcharts.src.ts
Labels: Product: Highcharts, Status: Review in progress

#15932 Migration: PieSeries
  package-lock.json
  ts/Series/Pie/PieSeries.ts
Labels: Product: Highcharts, Status: Review in progress

#15935 bugfix/zAxis-double-update
  samples/unit-tests/3d/zaxis-update/demo.js
  ts/Core/Chart/Chart.ts
Labels: Changelog: Bugfix, Status: Review in progress

#15943 bugfix/15449-exporting-menu-html
  ts/Extensions/Exporting.ts
Labels: Changelog: Bugfix, Status: Review in progress

#15947 bugfix/15946-marker-symbol-update-animate
  samples/unit-tests/series/update/demo.js
  ts/Core/Series/Series.ts
Labels: Changelog: Bugfix, Status: Review in progress

#15940 bugfix/15938-Intl-missing-2
  ts/Core/Time.ts
Labels: Changelog: Bugfix, Status: Review in progress

#15957 Update series.md
  docs/chart-concepts/series.md
Labels: Status: Review in progress

#15836 New feature: relativeXValue
  docs/chart-concepts/series.md
  docs/sidebars.js
  docs/working-with-data/data-compression.md
  docs/working-with-data/data-intro.md
  samples/highcharts/plotoptions/series-relativexvalue/demo.css
  samples/highcharts/plotoptions/series-relativexvalue/demo.details
  samples/highcharts/plotoptions/series-relativexvalue/demo.html
  samples/highcharts/plotoptions/series-relativexvalue/demo.js
  samples/stock/plotoptions/relativexvalue/demo.details
  samples/stock/plotoptions/relativexvalue/demo.html
  samples/stock/plotoptions/relativexvalue/demo.js
  samples/unit-tests/series/datagrouping/demo.js
  samples/unit-tests/series/pointintervalunit/demo.js
  samples/unit-tests/series/relativexvalue/demo.details
  samples/unit-tests/series/relativexvalue/demo.html
  samples/unit-tests/series/relativexvalue/demo.js
  ts/Core/Series/Point.ts
  ts/Core/Series/Series.ts
  ts/Core/Series/SeriesOptions.d.ts
Labels: Status: Review in progress

#15942 Migration: RadialAxis (and HiddenAxis)
  test/ts-node-unit-tests/tests/modules.test.ts
  ts/Core/Axis/Axis.ts
  ts/Core/Axis/HiddenAxis.ts
  ts/Core/Axis/PlotBandOptions.d.ts
  ts/Core/Axis/PlotLineOptions.d.ts
  ts/Core/Axis/PlotLineOrBand.ts
  ts/Core/Axis/RadialAxis.ts
  ts/Core/Axis/SolidGaugeAxis.ts
  ts/Core/Globals.ts
  ts/Extensions/CurrentDateIndication.ts
  ts/Extensions/Pane.ts
  ts/Extensions/ParallelCoordinates.ts
  ts/Extensions/Polar.ts
  ts/Series/AreaRange/AreaRangeSeries.ts
  ts/Series/Gauge/GaugeSeries.ts
  ts/masters/highcharts-more.src.ts
Labels: Product: Highcharts, Status: Review in progress
