Repository highcharts/highcharts, pull requests merged in 2022-05, with the labels that each got.

#17231 Docs: Made Point.shapeArgs property public.
  ts/Core/Series/Point.ts
Labels: Product: Docs

#17228 bugfix/17227-wordcloud-data-docs
  ts/Core/Legend/Legend.ts
Labels: Product: Highcharts

#17230 docs/17229-borderColor-borderWidth-in-mapPoint
  ts/Series/MapPoint/MapPointSeries.ts
Labels: Product: Docs, Product: Highcharts Maps

#17158 Fixed: #16810, inverted images.
  samples/unit-tests/accessibility/accessible-highmaps/demo.js
  ts/Extensions/PatternFill.ts
Labels: Type: Bug, Product: Highcharts Maps

#17306 Fixed #17013, map view fit to bounds after setData
  samples/unit-tests/maps/setdata/demo.js
  ts/Series/Map/MapSeries.ts
Labels: Product: Highcharts Maps, Changelog: Bugfix

#16783 Feature: series on point composition
  samples/highcharts/series-on-point/series-on-point/demo.css
  samples/highcharts/series-on-point/series-on-point/demo.details
  samples/highcharts/series-on-point/series-on-point/demo.html
  samples/highcharts/series-on-point/series-on-point/demo.js
  samples/maps/demo/map-pies/demo.html
  samples/maps/demo/map-pies/demo.js
  samples/unit-tests/series-on-point/series-on-point/demo.css
  samples/unit-tests/series-on-point/series-on-point/demo.details
  samples/unit-tests/series-on-point/series-on-point/demo.html
  samples/unit-tests/series-on-point/series-on-point/demo.js
  test/karma-files.json
  ts/Core/Axis/Color/ColorAxis.ts
  ts/Series/Bubble/BubbleSeries.ts
  ts/Series/CenteredUtilities.ts
  ts/Series/Pie/PieSeries.ts
  ts/Series/SeriesOnPointComposition.ts
  ts/Series/Sunburst/SunburstSeries.ts
  ts/masters/modules/series-on-point.src.ts
Labels: Changelog: Feature, Status: Review in progress

#17330 bugfix/17281-bubble-marker-symbol
  samples/unit-tests/series-bubble/marker/demo.js
  ts/Series/Bubble/BubbleSeries.ts
Labels: Changelog: Bugfix

#17327 bugfix/17322-flags-reversed-axis-tooltip
  ts/Series/Flags/FlagsPoint.ts
Labels: Product: Highcharts Stock, Changelog: Bugfix
