Repository highcharts/highcharts, pull requests merged in 2022-02, with the labels that each got.

#16922 Added map option, affectsMapView
  samples/maps/series/affectsmapview/demo.css
  samples/maps/series/affectsmapview/demo.details
  samples/maps/series/affectsmapview/demo.html
  samples/maps/series/affectsmapview/demo.js
  samples/maps/series/mapdata-multiple/demo.js
  ts/Maps/MapView.ts
  ts/Series/Map/MapSeries.ts
  ts/Series/Map/MapSeriesOptions.d.ts
Labels: Product: Highcharts Maps, Changelog: Feature, Status: Review in progress

#16949 bugfix/14175-datalabels-rotation-update
  samples/unit-tests/datalabels/update/demo.details
  samples/unit-tests/datalabels/update/demo.html
  samples/unit-tests/datalabels/update/demo.js
  ts/Core/Series/DataLabel.ts
Labels: Changelog: Bugfix, Status: Review in progress

#16787 Org chart: Improve mixed layouts, touch #13915.
  samples/highcharts/series-organization/hanging-cumulative/demo.css
  samples/highcharts/series-organization/hanging-cumulative/demo.details
  samples/highcharts/series-organization/hanging-cumulative/demo.html
  samples/highcharts/series-organization/hanging-cumulative/demo.js
  samples/highcharts/series-organization/hanging-shrink/demo.css
  samples/highcharts/series-organization/hanging-shrink/demo.details
  samples/highcharts/series-organization/hanging-shrink/demo.html
  samples/highcharts/series-organization/hanging-shrink/demo.js
  samples/unit-tests/svgrenderer/xss/demo.js
  tools/gulptasks/scripts-messages.js
  ts/Series/Organization/OrganizationPoint.ts
  ts/Series/Organization/OrganizationSeries.ts
  ts/Series/Organization/OrganizationSeriesOptions.d.ts
  ts/Series/Sankey/SankeyPoint.ts
  ts/Series/Sankey/SankeySeries.ts
Labels: Status: In progress, Changelog: Feature

#16957 Fixed MapView update of insets
  samples/unit-tests/maps/mapview-inset/demo.js
  ts/Maps/MapView.ts
  ts/Series/Map/MapSeries.ts
Labels: Type: Pre-release, Status: Review in progress

#16939 Website/icon editor
  samples/highcharts/website/icon-editor/demo.css
  samples/highcharts/website/icon-editor/demo.html
  samples/highcharts/website/icon-editor/demo.js
  samples/highcharts/website/static-editor/demo.css
  samples/highcharts/website/static-editor/demo.details
  samples/highcharts/website/static-editor/demo.html
  samples/highcharts/website/static-editor/demo.js
Labels: Status: Review in progress

#16962 Fixed missing images and mobile issues
  samples/highcharts/website/icon-editor/demo.css
  samples/highcharts/website/icon-editor/demo.js
  samples/highcharts/website/static-editor/demo.css
  samples/highcharts/website/static-editor/demo.js
Labels: Status: Review in progress

#16977 Feature/node-series-refactor
  ts/Series/NodesComposition.ts
  ts/Series/Treegraph/TreegraphSeries.ts
Labels: Status: Review in progress

#16973 docs/security
  docs/chart-concepts/security.md
Labels: Product: Docs, Status: Review in progress

#16954 bugfix/14167-setVisible-docs
  ts/Series/Pie/PiePoint.ts
Labels: Product: Docs, Status: Review in progress

#16983 Docs: alignThresholds
  docs/chart-concepts/axes.md
  ts/Core/Chart/ChartDefaults.ts
Labels: Status: Review in progress

#16980 Themes/high contrast themes
  ts/Extensions/Themes/HighContrastDark.ts
  ts/Extensions/Themes/HighContrastLight.ts
Labels: Status: Review in progress

#17003 Fixed #16974, esc keypress kbd focus issue.
  ts/Accessibility/Components/MenuComponent.ts
Labels: Changelog: Bugfix

#16998 16970-rectangle-control-point
  ts/Extensions/Annotations/Types/BasicAnnotation.ts
Labels: Product: Highcharts Stock, Changelog: Bugfix
