Repository highcharts/highcharts, pull requests merged in 2022-01, with the labels that each got.

#16360 Migration: Global win to window, restricted strict mode
  package-lock.json
  package.json
  tools/compile.js
  ts/Core/Globals.ts
Labels: Changelog: Feature, Status: Review in progress

#16825 Fixed #16818, issue with kbd nav and legend.labelFormatter.
  ts/Accessibility/Components/LegendComponent.ts
Labels: Changelog: Bugfix, Status: Review in progress

#16817 bugfix/16479-resetZoomButton-drillup
  samples/unit-tests/drilldown/resetzoom/demo.js
  ts/Extensions/Drilldown.ts
Labels: Product: Highcharts, Changelog: Bugfix, Status: Review in progress

#16834 bugfix/16169-centerInCategory-reverses-stack
  samples/unit-tests/series/stacking/demo.js
  ts/Series/Column/ColumnSeries.ts
Labels: Product: Highcharts, Changelog: Bugfix, Status: Review in progress

#16852 Fixed doclet
  ts/Series/Lollipop/LollipopSeries.ts
Labels: Status: Review in progress

#16854 Fixed round errors on windows.
  samples/unit-tests/series/datalabels/demo.js
Labels: Status: Review in progress

#16862 Updated package-lock.json
  package-lock.json
Labels: Status: Review in progress

#16869 Fixed issue with data module updates and dataGrouping options.
  samples/unit-tests/data/general/demo.js
  ts/Extensions/Data.ts
Labels: Changelog: Bugfix, Status: Review in progress

#16876 demo/tooltip-extra-information
  samples/highcharts/tooltip/pointformat-extra-information/demo.details
  samples/highcharts/tooltip/pointformat-extra-information/demo.html
  samples/highcharts/tooltip/pointformat-extra-information/demo.js
  ts/Core/DefaultOptions.ts
Labels: Product: Docs, Status: Review in progress

#16891 bugfix/16045-resetzoom-tooltip-opacity
  samples/unit-tests/pointer/touch/demo.js
  samples/unit-tests/svgrenderer/animate/demo.js
  ts/Core/Renderer/SVG/SVGElement.ts
Labels: Changelog: Bugfix, Status: Review in progress

#16887 Fixed #16884, smarter defaults for a11y point descriptions.
  ts/Accessibility/Components/SeriesComponent/SeriesDescriber.ts
Labels: Changelog: Bugfix, Status: Review in progress

#16892 Fixed #16339, kbd focus management issues with fullscreen change.
  ts/Accessibility/Components/MenuComponent.ts
Labels: Changelog: Bugfix, Status: Review in progress

#16895 bugfix/11712-update-node
  samples/unit-tests/series-sankey/sankey/demo.js
  ts/Extensions/Annotations/MockPoint.ts
  ts/Series/DataModifyComposition.ts
  ts/Series/DependencyWheel/DependencyWheelSeries.ts
  ts/Series/Networkgraph/Layouts.ts
  ts/Series/NodesComposition.ts
Labels: Changelog: Bugfix, Status: Review in progress

#16883 Fixed #16873, WHCM not detected in other browsers.
  ts/Accessibility/HighContrastMode.ts
Labels: Changelog: Bugfix, Status: Review in progress

#16902 bugfix/16791-safari-exporting
  ts/Extensions/Exporting/Exporting.ts
Labels: Changelog: Bugfix, Status: Review in progress

#16898 Fixed #16893, findNearestPointBy not working well with Boost
  ts/Extensions/Boost/BoostInit.ts
Labels: Changelog: Bugfix, Status: Review in progress

#16918 Docs: Add correct @since jsdoc notation in ScrollablePlotArea
  ts/Extensions/ScrollablePlotArea.ts
Labels: Status: Review in progress

#16916 bugfix/16474-pie-3d-click
  samples/unit-tests/3d/series-pie/demo.js
  ts/Series/Pie3D/Pie3DSeries.ts
Labels: Changelog: Bugfix, Status: Review in progress

#16801 Fixed #16722, container size preventing map rotation.
  samples/unit-tests/maps/map-navigation/demo.js
  ts/Maps/MapView.ts
Labels: Product: Highcharts Maps, Changelog: Bugfix, Status: Review in progress

#16933 Projection best guess from series.mapData
  ts/Maps/MapView.ts
Labels: Status: Review in progress

#16907 Fixed failing test on master.
  samples/unit-tests/tooltip/stickoncontact/demo.js
Labels: Status: Review in progress
