Repository highcharts/highcharts, pull requests merged in 2022-09, with the labels that each got.

#17680 Better default value for legend.valueDecimals
  ts/Core/Axis/Color/ColorAxis.ts
  ts/Core/DefaultOptions.ts
  ts/Core/Legend/LegendOptions.d.ts
Labels: Changelog: Bugfix

#17688 Fixed #17677, text and outline not aligned for sunburst data labels
  samples/unit-tests/series-sunburst/datalabels/demo.js
  ts/Core/Renderer/SVG/SVGElement.ts
Labels: Changelog: Bugfix

#17650 bugfix/17189-mapbubble-joinby-type
  ts/Series/MapBubble/MapBubbleSeries.ts
Labels: Product: Docs, Changelog: Bugfix

#17691 docs/17351-animation-limit
  samples/highcharts/plotoptions/series-animationlimit/demo.css
  samples/highcharts/plotoptions/series-animationlimit/demo.details
  samples/highcharts/plotoptions/series-animationlimit/demo.html
  samples/highcharts/plotoptions/series-animationlimit/demo.js
  ts/Core/Series/SeriesDefaults.ts
Labels: Product: Docs

#17682 Fixed #17610, centerInCategory and duplicated x's.
  package-lock.json
  samples/unit-tests/series/centerincategory/demo.js
  ts/Series/Column/ColumnSeries.ts
Labels: Changelog: Bugfix

#17681 Docs: Clarified data label formatters in DependencyWheel.
  ts/Series/DependencyWheel/DependencyWheelSeries.ts
  ts/Series/DependencyWheel/DependencyWheelSeriesDefaults.ts
Labels: Product: Docs

#17669 Docs: Fixed typing of PatternOptionsObject.
  ts/Extensions/PatternFill.ts
Labels: Product: Docs, Product: TypeScript

#17662 Docs: Fixed timeline.lineWidth option.
  ts/Series/Timeline/TimelineSeries.ts
Labels: Product: Docs, Product: TypeScript

#17661 Docs: Fixed parameter of print callbacks in exporting module.
  ts/Extensions/Exporting/Exporting.ts
Labels: Product: Docs, Product: TypeScript

#17647 Docs: Fixed doclet of bollinger fillColor and params.
  ts/Stock/Indicators/BB/BBIndicator.ts
Labels: Product: Docs, Product: TypeScript

#17715 Docs: Made lineWidth option of timeline series public.
  ts/Series/Timeline/TimelineSeries.ts
  ts/Series/Timeline/TimelineSeriesDefaults.ts
Labels: Product: Docs

#17722 bugfix/17288-shadow-group-not-preserved
  samples/unit-tests/svgrenderer/shadows/demo.js
  ts/Core/Series/Series.ts
Labels: Product: Highcharts, Changelog: Bugfix

#17749 Docs: Removed align defaults because of opposite dynamic.
  ts/Core/Axis/AxisDefaults.ts
Labels: Product: Docs

#17748 Docs: Synchronized name of PlotLineOrBand.svgElem.
  ts/Core/Axis/PlotLineOrBand/PlotLineOrBand.ts
Labels: Product: Docs, Product: TypeScript

#17745 Docs: Improved sample description of yAxis.stops.
  ts/Core/Axis/AxisDefaults.ts
Labels: Product: Docs

#17744 Docs: Updated API generator to merge see-tag for series options.
  package-lock.json
  package.json
Labels: Product: Docs

#17697 enhancement/17270-flowmap-series-docs-demos
  samples/maps/demo/flowmap-ship-route/demo.css
  samples/maps/demo/flowmap-ship-route/demo.details
  samples/maps/demo/flowmap-ship-route/demo.html
  samples/maps/demo/flowmap-ship-route/demo.js
  samples/maps/demo/flowmap/demo.js
  ts/Series/FlowMap/FlowMapSeries.ts
Labels: Product: Docs, Product: Highcharts Maps

#17768 bugfix/17759-demo-typo
  samples/highcharts/demo/column-basic/demo.js
Labels: Product: Docs

#17762 Docs: Fixed link to legend-plugin for chart resize.
  ts/Core/DefaultOptions.ts
Labels: Product: Docs

#17787 Feature/17630 boost stacking tooltip pointpercentage value
  ts/Extensions/Boost/BoostSeries.ts
Labels: Changelog: Bugfix

#17766 enhancement/13394-temperaturemap-series-main-demo
  samples/data/busiest-europe-airports-2021.json
  samples/maps/demo/blend-colors/demo.html
  samples/maps/demo/blend-colors/demo.js
Labels: Product: Docs, Product: Highcharts Maps

#17793 Fixed drag and drop of packed bubbles.
  ts/Series/PackedBubble/PackedBubbleSeries.ts
Labels: Changelog: Bugfix
