Repository highcharts/highcharts, pull requests merged in 2022-12, with the labels that each got.

#17987 enhancement-DataGridComponent
  css/datagrid.scss
  samples/.eslintrc
  samples/cypress/dashboard/chart-interaction-selection/demo.mjs
  samples/cypress/dashboard/chart-interaction/demo.mjs
  samples/dashboard/demos/dashboard-component/demo.mjs
  samples/dashboard/demos/dashboard-datagrid-component/demo.css
  samples/dashboard/demos/dashboard-datagrid-component/demo.details
  samples/dashboard/demos/dashboard-datagrid-component/demo.html
  samples/dashboard/demos/dashboard-datagrid-component/demo.mjs
  samples/dashboard/demos/dashboard-layout/demo.mjs
  samples/dashboard/demos/dashboard-minimal/demo.html
  samples/dashboard/demos/dashboard-minimal/demo.mjs
  samples/dashboard/demos/dashboard-strava-csv/demo.mjs
  test/cypress/integration/Dashboard/Components/DataGridComponent.spec.js
  test/typescript-karma/Extensions/DashboardPlugin/tests.js
  ts/Dashboard/Actions/Bindings.ts
  ts/Dashboard/Component/ComponentType.d.ts
  ts/Dashboard/Component/SharedComponentState.ts
  ts/DataGrid/DataGrid.ts
  ts/Extensions/DashboardPlugins/DataGridComponent.ts
  ts/Extensions/DashboardPlugins/DataGridPlugin.ts
  ts/Extensions/DashboardPlugins/DataGridSyncHandlers.ts
  ts/Extensions/DashboardPlugins/HighchartsComponent.ts
  ts/Extensions/DashboardPlugins/HighchartsPlugin.ts
  ts/Extensions/DashboardPlugins/HighchartsSyncHandlers.ts
  ts/masters/modules/dashboard-plugin.src.ts
Labels: Db

#18064 Db/csv assets
  samples/dashboard/demos/climate/demo.js
  ts/Data/DataOnDemand.ts
Labels: Db

#18067 db/container content
  test/typescript-karma/Dashboard/Layout/tests.js
  ts/Dashboard/Dashboard.ts
Labels: Db

#18061 Db/simpler events
  ts/Dashboard/Component/Component.ts
  ts/Dashboard/Component/HTMLComponent.ts
  ts/Dashboard/Component/SharedComponentState.ts
  ts/Data/DataEvent.ts
  ts/Data/DataEventEmitter.d.ts
  ts/Data/DataOnDemand.ts
  ts/Data/DataSeriesConverter.ts
  ts/Data/DataTable.ts
  ts/Data/Modifiers/ChainModifier.ts
  ts/Data/Modifiers/DataModifier.ts
  ts/Data/Modifiers/GroupModifier.ts
  ts/Data/Modifiers/InvertModifier.ts
  ts/Data/Modifiers/RangeModifier.ts
  ts/Data/Modifiers/SeriesPointsModifier.ts
  ts/Data/Modifiers/SortModifier.ts
  ts/Data/Parsers/CSVParser.ts
  ts/Data/Parsers/DataParser.ts
  ts/Data/Parsers/GoogleSheetsParser.ts
  ts/Data/Parsers/HTMLTableParser.ts
  ts/Data/Stores/CSVStore.ts
  ts/Data/Stores/DataStore.ts
  ts/Data/Stores/GoogleSheetsStore.ts
  ts/Data/Stores/HTMLTableStore.ts
  ts/DataGrid/DataGrid.ts
Labels: Db

#18005 Db/one direction sync
  docs/dashboards/sync.md
  samples/cypress/dashboard/chart-interaction-one-way/demo.details
  samples/cypress/dashboard/chart-interaction-one-way/demo.html
  samples/cypress/dashboard/chart-interaction-one-way/demo.mjs
  samples/cypress/dashboard/chart-interaction-selection/demo.mjs
  samples/cypress/dashboard/chart-interaction/demo.mjs
  samples/dashboard/demos/dashboard-component/demo.mjs
  samples/dashboard/demos/dashboard-datagrid-component/demo.mjs
  samples/dashboard/demos/dashboard-minimal/demo.mjs
  samples/dashboard/demos/dashboard-strava-csv/demo.mjs
  test/typescript-karma/Extensions/DashboardPlugin/tests.js
  ts/Dashboard/Component/Component.ts
  ts/Dashboard/Component/HTMLComponent.ts
  ts/Dashboard/Component/KPIComponent.ts
  ts/Dashboard/Component/Sync/Sync.ts
  ts/Dashboard/Component/ThresholdComponent.ts
  ts/Extensions/DashboardPlugins/DataGridComponent.ts
  ts/Extensions/DashboardPlugins/HighchartsComponent.ts
Labels: Db

#18029 DB datagrid store sync
  ts/Dashboard/Component/Component.ts
  ts/DataGrid/DataGrid.ts
  ts/Extensions/DashboardPlugins/DataGridComponent.ts
Labels: Db

#18020 Samples: Map demo of lightning strikes
  samples/maps/demo/lightning/demo.css
  samples/maps/demo/lightning/demo.html
  samples/maps/demo/lightning/demo.js
  samples/maps/demo/lightning/readme.md
Labels: Product: Website

#18092 DB: Fixed error when syncing using global scripts
  ts/DataGrid/DataGrid.ts
  ts/Extensions/DashboardPlugins/HighchartsComponent.ts
Labels: Db

#17896 bugfix/17856-heatmap-default-linecolor
  samples/unit-tests/series-heatmap/members/demo.js
  ts/Series/Heatmap/HeatmapSeries.ts
Labels: Changelog: Bugfix

#18129 db/cypress
  test/cypress/integration/Dashboard/layout-edit.cy.js
Labels: Db

#18033 Db/enable layout adding
  samples/dashboard/cypress/add-layout/demo.css
  samples/dashboard/cypress/add-layout/demo.details
  samples/dashboard/cypress/add-layout/demo.html
  samples/dashboard/cypress/add-layout/demo.mjs
  test/cypress/integration/Dashboard/component-add.spec.js
  test/cypress/support/index.js
  ts/Dashboard/Actions/Bindings.ts
  ts/Dashboard/Actions/DragDrop.ts
  ts/Dashboard/Actions/Resizer.ts
  ts/Dashboard/Dashboard.ts
  ts/Dashboard/EditMode/Sidebar.ts
Labels: Db

#18112 Db/component content size
  samples/cypress/dashboard/component-loading/demo.details
  samples/cypress/dashboard/component-loading/demo.html
  samples/cypress/dashboard/component-loading/demo.mjs
  test/cypress/integration/Dashboard/Components/loading.cy.js
  ts/Dashboard/Component/Component.ts
Labels: Db

#18141 bugfix/18127-datalabels-default-border
  samples/unit-tests/datalabels/members/demo.js
  ts/Core/Series/SeriesDefaults.ts
Labels: Changelog: Bugfix

#18079 Db/datagridcomponent-bindings
  samples/dashboard/demos/climate/demo.html
  samples/dashboard/demos/climate/demo.js
  ts/Dashboard/Actions/Bindings.ts
  ts/Data/DataOnDemand.ts
  ts/Data/DataOnDemandDefaults.ts
  ts/Data/DataOnDemandOptions.ts
  ts/masters/modules/dashboard-plugin.src.ts
Labels: Db

#18135 bugfix/17925-mobile-zooming
  samples/unit-tests/maps/topojson/demo.js
  ts/Maps/MapView.ts
Labels: Product: Highcharts Maps, Changelog: Bugfix

#18150 bugfix/18145-grey-series-boost
  ts/Extensions/Boost/NamedColors.ts
Labels: Changelog: Bugfix

#18161 db/save-localy
  samples/cypress/dashboard/layout-resize/demo.mjs
  samples/dashboard/demos/dashboard-layout/demo.mjs
  samples/dashboard/demos/dashboard-strava-csv/demo.mjs
  ts/Dashboard/EditMode/EditContextMenu.ts
  ts/Dashboard/EditMode/EditGlobals.ts
Labels: Db

#18164 db/dashboard-component
  samples/dashboard/demos/dashboard-component/demo.mjs
Labels: Db

#18165 db/data series converter
  ts/Core/Series/DataSeriesConverter.ts
Labels: Db

#18138 bugfix/18116-sunburst-central-dl-width
  ts/Series/Sunburst/SunburstSeries.ts
Labels: Changelog: Bugfix

#18173 Db/data converter helper
  samples/cypress/dashboard/dashboard-layout/demo.css
  samples/cypress/dashboard/dashboard-layout/demo.details
  samples/cypress/dashboard/dashboard-layout/demo.html
  samples/cypress/dashboard/dashboard-layout/demo.mjs
  test/cypress/integration/Dashboard/json-serialization.cy.js
  test/typescript-karma/Dashboard/SerializeHelpers/DataConverterHelper.test.js
  ts/Dashboard/Actions/Bindings.ts
  ts/Dashboard/JSON.d.ts
  ts/Dashboard/Layout/Cell.ts
  ts/Dashboard/Serializable.ts
  ts/Dashboard/SerializeHelper/DataConverterHelper.ts
  ts/Dashboard/SerializeHelper/HTMLTableStoreHelper.ts
  ts/Data/Converters/DataConverter.ts
Labels: Db

#18146 Db/optimal data store
  samples/dashboard/demos/climate/demo.js
  test/typescript-karma/Data/DataPromise.test.js
  test/typescript-karma/Data/Stores/CSVStore.test.js
  test/typescript-karma/Data/Stores/GoogleSheetsStore.test.js
  test/typescript-karma/Data/Stores/HTMLTableStore.test.js
  test/typescript-karma/Data/Stores/utils.js
  test/typescript-karma/karma-conf.js
  test/typescript-karma/karma-fetch.js
  test/typescript-karma/karma-setup.js
  ts/Core/HttpUtilities.ts
  ts/Data/Converters/CSVConverter.ts
  ts/Data/Converters/DataConverter.ts
  ts/Data/Converters/GoogleSheetsConverter.ts
  ts/Data/Converters/HTMLTableConverter.ts
  ts/Data/DataPromise.ts
  ts/Data/DataTable.ts
  ts/Data/Modifiers/DataModifier.ts
  ts/Data/Stores/CSVStore.ts
  ts/Data/Stores/DataStore.ts
  ts/Data/Stores/GoogleSheetsStore.ts
  ts/Data/Stores/HTMLTableStore.ts
  ts/Series/Heatmap/HeatmapPoint.ts
  ts/masters/dashboard.src.ts
Labels: Db

#18188 bugfix/18168-legend-proximate-layout
  ts/Core/Legend/Legend.ts
Labels: Changelog: Bugfix

#16956 bugfix/16944-tooltip-outside-pos
  package-lock.json
  samples/unit-tests/tooltip/outside/demo.js
  ts/Core/Tooltip.ts
Labels: Flow: In progress, Changelog: Bugfix

#18190 Fixed handling of non-columns in DataTable.
  test/typescript-karma/Data/DataTable.test.js
  ts/Data/DataTable.ts
Labels: Db

#18191 Db/csv conveter helper
  samples/highcharts/data/delimiters/demo.js
  test/typescript-karma/Dashboard/SerializeHelpers/CSVConverterHelper.test.js
  ts/Dashboard/SerializeHelper/CSVConverterHelper.ts
Labels: Db

#18204 db/sidebar-editable-options-error
  ts/Dashboard/Component/EditableOptions.ts
  ts/Extensions/DashboardPlugins/DataGridComponent.ts
Labels: Db
