Repository highcharts/highcharts, pull requests merged in 2022-03, with the labels that each got.

#17050 bugfix/17042-panning-ordinal
  ts/Core/Axis/OrdinalAxis.ts
Labels: Product: Highcharts Stock

#16963 bugfix/16921-heatmap-marker-hover-zoom
  samples/unit-tests/series-heatmap/members/demo.js
  ts/Series/Heatmap/HeatmapSeries.ts
Labels: Changelog: Bugfix, Status: Review in progress

#17110 Fixed #17100 excessive padding with tickAmount
  ts/Core/Axis/Axis.ts
  ts/Core/Axis/LogarithmicAxis.ts
  ts/Core/Utilities.ts
Labels: Changelog: Bugfix

#17121 Corrected breadcrumbs URL in docs.
  docs/advanced-chart-features/breadcrumbs.md
Labels: Product: Docs

#17126 bugfix/15863-remove-hide-by-translation
  ts/Core/Scrollbar.ts
Labels: Changelog: Bugfix
