Repository highcharts/highcharts, pull requests merged in 2022-07, with the labels that each got.

#17461 bugfix/17438-point-update-categories
  samples/unit-tests/axis/category/demo.js
  ts/Core/Axis/Axis.ts
Labels: Product: Highcharts, Changelog: Bugfix

#17471 Fixed #17401, console error with numeric point id.
  ts/Accessibility/Components/SeriesComponent/SeriesDescriber.ts
Labels: Changelog: Bugfix

#17464 Fixed #17442, data classes not kbd navigable.
  samples/maps/accessibility/accessible-data-classes/demo.css
  samples/maps/accessibility/accessible-data-classes/demo.details
  samples/maps/accessibility/accessible-data-classes/demo.html
  samples/maps/accessibility/accessible-data-classes/demo.js
  samples/maps/accessibility/accessible-data-classes/test-notes.md
  ts/Accessibility/Components/LegendComponent.ts
Labels: Changelog: Bugfix

#17479 bugfix/17423-stock-tools-wrap
  ts/Extensions/Annotations/NavigationBindings.ts
Labels: Product: Highcharts Stock, Changelog: Bugfix

#17493 docs/17468-jsdoc-config
  tools/gulptasks/jsdoc-classes.js
Labels: Type: Bug, Product: Docs
