Repository highcharts/highcharts, pull requests merged in 2022-11, with the labels that each got.

#17858 Fixed gantts connection lines not clearing/redrawing properly
  ts/Gantt/Pathfinder.ts
Labels: Changelog: Bugfix

#17834 bugfix/17734-pdf-offline-exporting
  samples/highcharts/exporting/offline-download-map-to-pdf/demo.css
  samples/highcharts/exporting/offline-download-map-to-pdf/demo.details
  samples/highcharts/exporting/offline-download-map-to-pdf/demo.html
  samples/highcharts/exporting/offline-download-map-to-pdf/demo.js
  samples/highcharts/exporting/offline-download-map-to-pdf/test-notes.html
  ts/Series/Map/MapSeries.ts
Labels: Product: Highcharts Maps, Changelog: Bugfix

#17958 Tools: Added DTS distribution for ESM masters
  tools/gulptasks/jsdoc-dts.js
Labels: Changelog: Bugfix

#17964 bugfix/17957-dataLabels-hover
  samples/unit-tests/series/datalabels/demo.html
  samples/unit-tests/series/datalabels/demo.js
  ts/Core/Series/Point.ts
Labels: Changelog: Bugfix

#16002 bugfix/12416-scrollablePlotArea-tooltip-update
  ts/Core/Pointer.ts
  ts/Extensions/ScrollablePlotArea.ts
Labels: Changelog: Bugfix, Flow: Review in progress

#17984 X-property of stackLabels now functions
  ts/Core/Axis/WaterfallAxis.ts
Labels: Changelog: Bugfix

#17996 bugfix/17918-inset-points-zoom
  samples/unit-tests/maps/topojson/demo.js
  ts/Series/Map/MapPoint.ts
Labels: Product: Highcharts Maps, Changelog: Bugfix

#17997 Fixed exiting fullscreen with added invisible series, when pattern-fill is active
  ts/Extensions/PatternFill.ts
Labels: Changelog: Bugfix

#18023 Regression in tooltip class names for color index
  samples/unit-tests/tooltip/custom-classnames/demo.js
  ts/Core/Tooltip.ts
Labels: Priority: Blocker

#17990 Fixed HTMLComponent overflow
  css/dashboard/gui.scss
  ts/Dashboard/Component/HTMLComponent.ts
Labels: Db

#18035 db/dashboard-icons
  gfx/dashboard-icons/add.svg
  gfx/dashboard-icons/close.svg
  gfx/dashboard-icons/computer.svg
  gfx/dashboard-icons/destroy.svg
  gfx/dashboard-icons/drag.svg
  gfx/dashboard-icons/menu.svg
  gfx/dashboard-icons/settings.svg
  gfx/dashboard-icons/smartphone.svg
  gfx/dashboard-icons/tablet.svg
Labels: Db

#18036 Db/move demos to dashboard dir
  samples/dashboard/demos/dashboard-component-kpi/demo.css
  samples/dashboard/demos/dashboard-component-kpi/demo.details
  samples/dashboard/demos/dashboard-component-kpi/demo.html
  samples/dashboard/demos/dashboard-component-kpi/demo.mjs
  samples/dashboard/demos/dashboard-component/demo.css
  samples/dashboard/demos/dashboard-component/demo.details
  samples/dashboard/demos/dashboard-component/demo.html
  samples/dashboard/demos/dashboard-component/demo.mjs
  samples/dashboard/demos/dashboard-layout/demo.css
  samples/dashboard/demos/dashboard-layout/demo.details
  samples/dashboard/demos/dashboard-layout/demo.html
  samples/dashboard/demos/dashboard-layout/demo.mjs
  samples/dashboard/demos/dashboard-minimal/demo.css
  samples/dashboard/demos/dashboard-minimal/demo.details
  samples/dashboard/demos/dashboard-minimal/demo.html
  samples/dashboard/demos/dashboard-minimal/demo.mjs
  samples/dashboard/demos/dashboard-strava-csv/demo.details
  samples/dashboard/demos/dashboard-strava-csv/demo.html
  samples/dashboard/demos/dashboard-strava-csv/demo.mjs
Labels: Db

#17992 Climate demo loading
  package.json
  samples/dashboard/demos/climate/demo.details
  samples/dashboard/demos/climate/demo.html
  samples/dashboard/demos/climate/demo.js
  samples/tsglobal.d.ts
  ts/Data/DataOnDemand.ts
  ts/Data/DataOnDemandDefaults.ts
  ts/masters/dashboard.src.ts
Labels: Db

#18032 bugfix/17970-heatmap-update-point-wrong-color
  samples/unit-tests/series-heatmap/datalabel/demo.js
  ts/Series/Heatmap/HeatmapPoint.ts
Labels: Product: Highcharts, Changelog: Bugfix

#18028 bugfix/17995-measure-control-points-position
  samples/unit-tests/annotations/annotations-measure/demo.js
  ts/Extensions/Annotations/Types/Measure.ts
Labels: Product: Highcharts Stock, Changelog: Bugfix

#18027 bugfix/17963-breadcrumbs-scrollablePlotArea
  samples/unit-tests/breadcrumbs/buttons/demo.js
  ts/Extensions/ScrollablePlotArea.ts
Labels: Changelog: Bugfix

#18024 db/default-menu-icon
  samples/dashboard/demos/dashboard-layout/demo.css
  samples/dashboard/demos/dashboard-layout/demo.html
  samples/dashboard/demos/dashboard-layout/demo.mjs
  samples/dashboard/demos/dashboard-minimal/demo.css
  samples/dashboard/demos/dashboard-minimal/demo.html
  ts/Dashboard/EditMode/EditMode.ts
Labels: Db

#18048 Docs: Fixed options inheritence of funnel3d and pyramid3d.
  ts/Series/Funnel3D/Funnel3DSeries.ts
  ts/Series/Pyramid3D/Pyramid3DSeries.ts
Labels: Product: Docs
