Repository highcharts/highcharts, pull requests merged in 2022-08, with the labels that each got.

#17573 bugfix/17569-linlogswitch-demo-bug
  samples/highcharts/blog/lin-log-switch/demo.js
Labels: Product: Docs, Changelog: Bugfix

#17490 bugfix/17484-organization-link-opacity
  ts/Series/Organization/OrganizationSeries.ts
Labels: Product: Highcharts, Changelog: Bugfix

#17502 bugfix/17486-bubbleZExtremes-remove
  samples/unit-tests/bubble-legend/styles/demo.js
  samples/unit-tests/series-bubble/minmaxsize/demo.js
Labels: Product: Highcharts, Changelog: Bugfix

#17494 docs/15216-datalabels-zindex
  ts/Core/Series/SeriesDefaults.ts
Labels: Product: Highcharts, Product: Docs

#17588 Fixed #17551; added Series.types and Series.registerType.
  test/typescript-dts/classes/Series.ts
  ts/Core/Series/Series.ts
  ts/Core/Series/SeriesRegistry.ts
Labels: Changelog: Feature, Changelog: Bugfix

#17596 Docs: Fixed API options and declarations.
  package-lock.json
  package.json
  test/typescript-dts/highcharts/highcharts.ts
  tools/gulptasks/jsdoc-dts.js
  ts/Core/Renderer/SVG/SVGElement.ts
  ts/Series/DependencyWheel/DependencyWheelSeries.ts
  ts/Series/Map/MapSeries.ts
Labels: Product: Docs, Product: TypeScript

#17607 Docs: Added Tooltip.getPosition to public API.
  ts/Core/Tooltip.ts
Labels: Product: Docs, Product: TypeScript

#17604 Docs: Fixed typing of tooltip.clusterFormat option.
  ts/Extensions/MarkerClusters.ts
Labels: Product: Docs

#17620 Fixed #16958, differences in mapbubble API docs.
  ts/Series/MapBubble/MapBubbleSeries.ts
  ts/Series/Scatter/ScatterSeries.ts
Labels: Product: Docs, Product: Highcharts Maps

#17634 bugfix/17627-quotation-marks
  samples/unit-tests/ast/ast/demo.js
  ts/Core/Renderer/HTML/AST.ts
Labels: Product: Highcharts, Changelog: Bugfix

#17640 Tools: Updated generators to fix defaults reflection.
  package-lock.json
  package.json
Labels: Product: Docs, Product: TypeScript
