Repository highcharts/highcharts, pull requests merged in 2023-02, with the labels that each got.

#18407 db/initial-cell-height
  samples/dashboards/demos/climate/demo.js
  samples/dashboards/demos/layout/demo.js
  ts/Dashboards/Layout/Cell.ts
Labels: Db

#18413 db/fix-kpi-sizing-bug
  ts/Dashboards/Component/KPIComponent.ts
Labels: Db

#18399 enhancement/16569-priceEnvelope-multiple-lines-composition
  ts/Stock/Indicators/PriceEnvelopes/PriceEnvelopesIndicator.ts
  ts/Stock/Indicators/PriceEnvelopes/PriceEnvelopesOptions.d.ts
Labels: Type: Enhancement, Product: Highcharts Stock

#18364 Db/add datagrid gui
  samples/dashboards/cypress/add-layout/demo.css
  samples/dashboards/cypress/add-layout/demo.mjs
  samples/dashboards/demos/layout-nested/demo.css
  samples/dashboards/demos/layout/demo.css
  test/cypress/integration/Dashboards/component-add.cy.js
  test/cypress/support/index.js
  ts/Dashboards/Actions/Bindings.ts
  ts/Dashboards/EditMode/Sidebar.ts
Labels: Db

#18401 db/fix-climate
  samples/dashboards/demos/climate/demo.js
Labels: Db

#18419 db/dark-mode-climate
  samples/dashboards/demos/climate/demo.css
Labels: Db

#18439 db/climate-darkmode
  samples/dashboards/demos/climate/demo.css
Labels: Db

#18446 bugfix/18443-guidebox-classname-property
  ts/Extensions/DraggablePoints.ts
Labels: Changelog: Bugfix

#18452 bd/climate-animation
  samples/dashboards/demos/climate/demo.js
Labels: Db

#18467 db/remove-dimensions-property
  samples/cypress/dashboards/layout-resize/demo.mjs
  samples/dashboards/cypress/add-layout/demo.mjs
  samples/dashboards/demos/climate/demo.js
  samples/dashboards/demos/component-html/demo.js
  samples/dashboards/demos/layout/demo.js
  ts/Dashboards/Component/Component.ts
  ts/Dashboards/EditMode/Sidebar.ts
Labels: Db

#18472 db/editableOptions-serialization
  ts/Dashboards/Component/Component.ts
Labels: Db

#18480 db/dashboardWrapper-fullscreen
  ts/Dashboards/Dashboard.ts
Labels: Db

#18453 db/resizer-height-datagrid
  ts/DataGrid/DataGrid.ts
  ts/Extensions/DashboardPlugins/DataGridComponent.ts
Labels: Db

#18483 db/remove-dashboard
  test/cypress/integration/Dashboards/Dashboard-core-interactions/remove.cy.js
  ts/Dashboards/Dashboard.ts
  ts/Dashboards/Layout/Layout.ts
  ts/Dashboards/Layout/Row.ts
Labels: Db

#18495 bugfix/18245-map-zoom-buttons-style-v11
  css/highcharts.css
Labels: Type: Bug, Product: Highcharts Maps

#18481 bd/board-factory
  docs/dashboards/your-first-dashboard.md
  samples/cypress/dashboards/chart-interaction-one-way/demo.mjs
  samples/cypress/dashboards/chart-interaction-selection/demo.mjs
  samples/cypress/dashboards/chart-interaction/demo.mjs
  samples/cypress/dashboards/component-loading/demo.mjs
  samples/cypress/dashboards/dashboard-layout/demo.mjs
  samples/cypress/dashboards/layout-resize/demo.mjs
  samples/dashboards/cypress/add-layout/demo.mjs
  samples/dashboards/cypress/component-datagrid/demo.mjs
  samples/dashboards/demos/axes-sync/demo.js
  samples/dashboards/demos/climate/demo.js
  samples/dashboards/demos/component-highcharts/demo.js
  samples/dashboards/demos/component-html/demo.js
  samples/dashboards/demos/component-kpi/demo.js
  samples/dashboards/demos/datagrid-sync/demo.js
  samples/dashboards/demos/layout-nested/demo.js
  samples/dashboards/demos/layout/demo.js
  samples/dashboards/demos/light-dark-theme/demo.js
  samples/dashboards/demos/minimal/demo.js
  samples/dashboards/demos/your-first-dashboard/demo.js
  samples/highcharts/studies/dashboard-strava-csv/demo.mjs
  test/cypress/integration/Dashboards/Dashboard-core-interactions/remove.cy.js
  test/cypress/integration/Dashboards/component-add.cy.js
  test/cypress/support/index.js
  test/typescript-karma/Dashboards/Layout/tests.js
  tools/gulptasks/jsdoc-classes.js
  ts/Dashboards/Accessibility/DashboardsAccessibility.ts
  ts/Dashboards/Actions/Bindings.ts
  ts/Dashboards/Actions/DragDrop.ts
  ts/Dashboards/Actions/Resizer.ts
  ts/Dashboards/Board.ts
  ts/Dashboards/Component/Component.ts
  ts/Dashboards/EditMode/EditContextMenu.ts
  ts/Dashboards/EditMode/EditMode.ts
  ts/Dashboards/EditMode/Fullscreen.ts
  ts/Dashboards/EditMode/Menu/MenuItemBindings.ts
  ts/Dashboards/EditMode/Sidebar.ts
  ts/Dashboards/EditMode/Toolbar/CellEditToolbar.ts
  ts/Dashboards/EditMode/Toolbar/EditToolbar.ts
  ts/Dashboards/EditMode/Toolbar/RowEditToolbar.ts
  ts/Dashboards/Globals.ts
  ts/Dashboards/Layout/Cell.ts
  ts/Dashboards/Layout/Layout.ts
  ts/Dashboards/Layout/Row.ts
  ts/Dashboards/PluginHandler.ts
  ts/Dashboards/README.md
  ts/masters.off/dashboards.src.ts
  ts/masters/dashboards.src.ts
Labels: Db

#18492 Improved KPI component HTML structure.
  samples/dashboards/demos/climate/demo.css
  samples/dashboards/demos/component-kpi/demo.css
  ts/Dashboards/Component/KPIComponent.ts
Labels: Db

#18500 bugfix/18444-polar-bar-datalabels-error
  samples/unit-tests/chart/polar/demo.js
  ts/Series/PolarComposition.ts
Labels: Product: Highcharts, Changelog: Bugfix

#18506 Release: v0.0.2
  css/dashboards/gui.scss
  css/dashboards/lightDarkTheme.scss
  ts/masters/dashboards.src.ts
  ts/masters/datagrid.src.ts
  ts/masters/modules/dashboards-plugin.src.ts
Labels: Db

#18507 Db/chartOptions-update
  test/typescript-karma/Dashboards/Component/tests.js
  ts/Dashboards/EditMode/Sidebar.ts
  ts/Extensions/DashboardPlugins/HighchartsComponent.ts
Labels: Db

#18510 bugfix/18502-heatmap-pointpadding-yaxis-reversed
  samples/unit-tests/series-heatmap/members/demo.js
  ts/Series/Heatmap/HeatmapPoint.ts
Labels: Product: Highcharts, Changelog: Bugfix

#18499 db/css-variables-gui
  css/dashboards/gui.scss
  css/dashboards/lightDarkTheme.scss
Labels: Db

#18454 db/datagrid-import
  docs/dashboards/types-of-components.md
  ts/masters/dashboards.src.ts
Labels: Db

#18514 Tools: Removed leftovers to succeed on new repository clone.
  test/typescript-karma/DataGrid/DataGrid/tests.js
  test/typescript-karma/Extensions/DashboardPlugin/tests.js
Labels: Priority: High

#18518 db/climate-demo-formatters
  samples/dashboards/demos/climate/demo.js
Labels: Db

#18537 db/datagrid-name
  .eslintignore
  samples/.eslintignore
  samples/data-grid/basic/simple/demo.css
  samples/datagrid/basic/simple/demo.css
  samples/datagrid/basic/simple/demo.html
  samples/datagrid/basic/simple/demo.js
Labels: Db

#18555 db/sidebar-overflow
  css/dashboards/gui.scss
  samples/dashboards/demos/component-highcharts/demo.js
Labels: Db

#18561 db/responsive-buttons
  test/cypress/integration/Dashboards/EditMode/responsive-buttons.cy.js
  test/cypress/integration/Dashboards/edit-component.cy.js
  test/cypress/support/index.js
  ts/Dashboards/EditMode/EditMode.ts
Labels: Db

#18543 db/native-css
  .stylelintrc.json
  css/.stylelintrc.json
  css/annotations/popup.css
  css/annotations/popup.scss
  css/dashboards/gui.css
  css/dashboards/lightDarkTheme.scss
  css/datagrid.css
  samples/dashboards/demos/light-dark-theme/demo.css
  samples/dashboards/demos/light-dark-theme/readme.md
Labels: Db

#18566 demo/tooltip-follow-pointer
  samples/highcharts/tooltip/followpointer/demo.css
  samples/highcharts/tooltip/followpointer/demo.details
  samples/highcharts/tooltip/followpointer/demo.html
  samples/highcharts/tooltip/followpointer/demo.js
  ts/Core/Defaults.ts
Labels: Product: Docs

#18552 Db/custom component
  docs/dashboards/custom-component.md
  docs/doc-config.js
  samples/dashboards/demos/custom-component/demo.css
  samples/dashboards/demos/custom-component/demo.details
  samples/dashboards/demos/custom-component/demo.html
  samples/dashboards/demos/custom-component/demo.js
  ts/Dashboards/Actions/Bindings.ts
  ts/Dashboards/Component/Component.ts
  ts/masters/dashboards.src.ts
Labels: Db

#18557 db/dashboard-icons
  gfx/dashboard-icons/drowdown-pointer.svg
  gfx/dashboard-icons/series-types/icon-column.svg
  gfx/dashboard-icons/series-types/icon-gauge.svg
  gfx/dashboard-icons/series-types/icon-line.svg
  gfx/dashboard-icons/series-types/icon-pie.svg
  gfx/dashboard-icons/series-types/icon-scatter.svg
Labels: Db

#18511 KPI Serialization.
  ts/Dashboards/Actions/Bindings.ts
  ts/Dashboards/Component/KPIComponent.ts
  ts/Dashboards/Layout/Cell.ts
  ts/Dashboards/Layout/Layout.ts
  ts/Dashboards/Layout/Row.ts
  ts/Extensions/DashboardPlugins/HighchartsComponent.ts
Labels: Db

#18113 bugfix/16601-map-drilldown-animation
  samples/maps/demo/map-drilldown-preloaded/demo.css
  samples/maps/demo/map-drilldown-preloaded/demo.details
  samples/maps/demo/map-drilldown-preloaded/demo.html
  samples/maps/demo/map-drilldown-preloaded/demo.js
  samples/maps/demo/map-drilldown-preloaded/test-notes.html
  samples/maps/demo/map-drilldown/demo.js
  samples/unit-tests/maps/drilldown/demo.css
  samples/unit-tests/maps/drilldown/demo.details
  samples/unit-tests/maps/drilldown/demo.html
  samples/unit-tests/maps/drilldown/demo.js
  ts/Core/Chart/MapChart.ts
  ts/Extensions/Drilldown.ts
  ts/Maps/MapView.ts
  ts/Series/Map/MapPoint.ts
  ts/Series/Map/MapSeries.ts
Labels: Product: Highcharts Maps

#18568 db/light-dark-theme-docs
  css/dashboards/gui.css
  docs/dashboards/light-dark-theme.md
  docs/doc-config.js
Labels: Db

#18526 db/api-setup
  gulpfile.js
  package-lock.json
  package.json
  tools/gulptasks/dashboards/api-docs.js
  tools/gulptasks/dashboards/api-docs.json
  tools/gulptasks/dashboards/api-docs/api.js
  tools/gulptasks/dashboards/api-docs/highcharts.svg
  tools/gulptasks/dashboards/api-docs/images/apple-touch-icon-114x114.png
  tools/gulptasks/dashboards/api-docs/images/apple-touch-icon-120x120.png
  tools/gulptasks/dashboards/api-docs/images/apple-touch-icon-144x144.png
  tools/gulptasks/dashboards/api-docs/images/apple-touch-icon-152x152.png
  tools/gulptasks/dashboards/api-docs/images/apple-touch-icon-180x180.png
  tools/gulptasks/dashboards/api-docs/images/apple-touch-icon-57x57.png
  tools/gulptasks/dashboards/api-docs/images/apple-touch-icon-60x60.png
  tools/gulptasks/dashboards/api-docs/images/apple-touch-icon-72x72.png
  tools/gulptasks/dashboards/api-docs/images/apple-touch-icon-76x76.png
  tools/gulptasks/dashboards/api-docs/images/apple-touch-icon.png
  tools/gulptasks/dashboards/api-docs/images/favicon-160x160.png
  tools/gulptasks/dashboards/api-docs/images/favicon-16x16.png
  tools/gulptasks/dashboards/api-docs/images/favicon-192x192.png
  tools/gulptasks/dashboards/api-docs/images/favicon-32x32.png
  tools/gulptasks/dashboards/api-docs/images/favicon-96x96.png
  tools/gulptasks/dashboards/api-docs/index.html
  tools/gulptasks/dashboards/api-docs/stylesheet.css
Labels: Db

#18577 db/gui-cleanup
  css/dashboards/gui.css
  samples/dashboards/demos/climate/demo.css
  samples/highcharts/studies/dashboard-threshold/demo.css
  test/cypress/integration/Dashboards/Dashboard-core-interactions/remove.cy.js
  test/cypress/integration/Dashboards/EditMode/responsive-buttons.cy.js
  test/cypress/integration/Dashboards/component-add.cy.js
  test/cypress/integration/Dashboards/edit-component.cy.js
  test/cypress/integration/Dashboards/json-serialization.cy.js
  test/cypress/integration/Dashboards/layout-edit.cy.js
  test/cypress/integration/Dashboards/layout.cy.js
  test/cypress/support/index.js
  ts/Dashboards/EditMode/Fullscreen.ts
  ts/Dashboards/Globals.ts
Labels: Db
