Repository highcharts/highcharts, pull requests merged in 2023-06, with the labels that each got.

#19072 bugfix/19053-item-series-update
  ts/Series/Item/ItemSeries.ts
Labels: Changelog: Bugfix

#19074 db/hc-component-columnKeyMap
  docs/dashboards/frequently-asked-questions.md
  docs/dashboards/types-of-components.md
  samples/dashboards/cypress/component-datagrid/demo.mjs
  samples/dashboards/demos/axes-sync/demo.js
  samples/dashboards/demos/climate/demo.js
  samples/dashboards/demos/datagrid-sync/demo.js
  samples/dashboards/demos/light-dark-theme/demo.js
  samples/dashboards/demos/minimal/demo.js
  samples/highcharts/studies/dashboard-strava-csv/demo.mjs
  ts/Extensions/DashboardPlugins/DataGridComponent.ts
  ts/Extensions/DashboardPlugins/HighchartsComponent.ts
Labels: Db

#19082 Tooltip not showing up for boosted interpolated heatmap
  ts/Series/Heatmap/HeatmapSeries.ts
Labels: Changelog: Bugfix

#19081 db/fix-import-dashboard
  samples/dashboards/demos/layout/demo.js
Labels: Db

#19088 db/drag-html-component
  samples/cypress/dashboards/component-loading/demo.mjs
  samples/dashboards/cypress/add-layout/demo.mjs
  test/cypress/integration/Dashboards/Components/loading.cy.js
  test/cypress/integration/Dashboards/component-add.cy.js
  ts/Dashboards/Components/Component.ts
Labels: Db

#19100 db/docs-review-improvements
  docs/dashboards/edit-mode.md
  docs/dashboards/installation.md
  docs/dashboards/layout-description.md
  docs/dashboards/types-of-components.md
  docs/dashboards/your-first-dashboard.md
  ts/Dashboards/README.md
  ts/Data/README.md
Labels: Db

#19109 Added option gantt.connectors.radius
  ts/Gantt/Connection.ts
  ts/Gantt/Pathfinder.ts
  ts/Gantt/PathfinderAlgorithms.ts
  ts/Series/Gantt/GanttSeries.ts
Labels: Product: Highcharts Gantt, Changelog: Feature

#18936 db/climate-api-update
  samples/dashboards/demos/climate/demo.html
  samples/dashboards/demos/climate/demo.js
  samples/dashboards/demos/component-error-handler/demo.css
  test/typescript-karma/Dashboards/Layout/tests.js
Labels: Db

#19005 db/typo-dropdown-icon
  ts/Dashboards/EditMode/EditRenderer.ts
Labels: Db

#19115 db/updated-faq-docs
  docs/dashboards/frequently-asked-questions.md
Labels: Db

#19102 db/extremes-column-name
  ts/Extensions/DashboardPlugins/HighchartsSyncHandlers.ts
Labels: Db

#19116 Fixed DTS for mouse-wheel-zoom bundles
  test/typescript-lint/tsconfig.json
Labels: Product: TypeScript

#19142 Db/datapool connector rename
  docs/dashboards/frequently-asked-questions.md
  samples/cypress/dashboards/chart-interaction/demo.mjs
  samples/cypress/dashboards/chart-series-visibility/demo.js
  samples/cypress/dashboards/sync/chart-extremes/demo.js
  samples/dashboards/cypress/component-datagrid/demo.mjs
  samples/dashboards/demos/axes-sync/demo.js
  samples/dashboards/demos/climate/demo.js
  samples/dashboards/demos/datagrid-sync/demo.js
  samples/dashboards/demos/light-dark-theme/demo.js
  samples/dashboards/demos/minimal/demo.js
  test/typescript-karma/Dashboards/Component/tests.js
  test/typescript-karma/Data/DataPool.test.js
  ts/Dashboards/Components/Component.ts
  ts/Dashboards/Components/ComponentOptions.ts
  ts/Dashboards/Components/EditableOptions.ts
  ts/Data/DataPool.ts
  ts/Data/DataPoolOptions.ts
  ts/Data/README.md
  ts/Extensions/DashboardPlugins/DataGridComponent.ts
Labels: Db

#19147 Db/climate dg columns hidden
  samples/dashboards/demos/climate/demo.js
Labels: Db

#19146 Db/cell options reponsive docs
  ts/Dashboards/Layout/Cell.ts
Labels: Db

#19165 Docs: Improved API to support URL history.
  package-lock.json
  package.json
  tools/gulptasks/dashboards/api-docs.json
  tools/gulptasks/dashboards/api-docs/index.html
  tools/gulptasks/dashboards/api-docs/stylesheet.css
Labels: Db

#19136 bugfix/19002-a11y-stripped-signs
  samples/unit-tests/accessibility/accessibility-exporting/demo.js
  samples/unit-tests/title/title/demo.js
  ts/Accessibility/Components/AnnotationsA11y.ts
  ts/Accessibility/Components/ContainerComponent.ts
  ts/Accessibility/Components/InfoRegionsComponent.ts
  ts/Accessibility/Components/LegendComponent.ts
  ts/Accessibility/Components/SeriesComponent/SeriesDescriber.ts
  ts/Accessibility/Utils/ChartUtilities.ts
  ts/Accessibility/Utils/HTMLUtilities.ts
Labels: Changelog: Bugfix, a11y

#19172 feature/a11y-aria-atomic
  ts/Accessibility/Utils/Announcer.ts
  ts/Core/Renderer/HTML/HTMLAttributes.d.ts
Labels: a11y

#19196 bugfix/19143-incorrect-series-name-csv
  samples/unit-tests/data/general/demo.js
  ts/Extensions/Data.ts
Labels: Product: Highcharts, Changelog: Bugfix

#19218 db/climate-layout-cleanup
  samples/dashboards/demos/climate/demo.js
Labels: Db

#19220 Fixed how components are loaded.
  ts/Dashboards/Board.ts
Labels: Db

#19219 Removed custom positioner from map component in climate demo.
  samples/dashboards/demo/climate/demo.js
Labels: Db

#19177 db/climate-update
  samples/dashboards/demo/climate/demo.js
Labels: Product: Highcharts Dashboards

#18937 db/demo-editmode
  samples/dashboards/edit-mode/change-close-icon/demo.css
  samples/dashboards/edit-mode/change-close-icon/demo.details
  samples/dashboards/edit-mode/change-close-icon/demo.html
  samples/dashboards/edit-mode/change-close-icon/demo.js
  samples/dashboards/edit-mode/change-ctx-icon/demo.css
  samples/dashboards/edit-mode/change-ctx-icon/demo.details
  samples/dashboards/edit-mode/change-ctx-icon/demo.html
  samples/dashboards/edit-mode/change-ctx-icon/demo.js
  samples/dashboards/edit-mode/ctx-enabled/demo.css
  samples/dashboards/edit-mode/ctx-enabled/demo.details
  samples/dashboards/edit-mode/ctx-enabled/demo.html
  samples/dashboards/edit-mode/ctx-enabled/demo.js
  samples/dashboards/edit-mode/ctx-menu-width/demo.css
  samples/dashboards/edit-mode/ctx-menu-width/demo.details
  samples/dashboards/edit-mode/ctx-menu-width/demo.html
  samples/dashboards/edit-mode/ctx-menu-width/demo.js
  samples/dashboards/edit-mode/dragdrop-disabled/demo.css
  samples/dashboards/edit-mode/dragdrop-disabled/demo.details
  samples/dashboards/edit-mode/dragdrop-disabled/demo.html
  samples/dashboards/edit-mode/dragdrop-disabled/demo.js
  samples/dashboards/edit-mode/lang/demo.css
  samples/dashboards/edit-mode/lang/demo.details
  samples/dashboards/edit-mode/lang/demo.html
  samples/dashboards/edit-mode/lang/demo.js
  samples/dashboards/edit-mode/resize-disabled/demo.css
  samples/dashboards/edit-mode/resize-disabled/demo.details
  samples/dashboards/edit-mode/resize-disabled/demo.html
  samples/dashboards/edit-mode/resize-disabled/demo.js
  ts/Dashboards/Actions/DragDrop.ts
  ts/Dashboards/Actions/Resizer.ts
  ts/Dashboards/EditMode/ConfirmationPopup.ts
  ts/Dashboards/EditMode/EditContextMenu.ts
  ts/Dashboards/EditMode/EditMode.ts
Labels: Product: Highcharts Dashboards

#19037 Db/demo componentoptions
  samples/dashboards/component-options/caption/demo.css
  samples/dashboards/component-options/caption/demo.details
  samples/dashboards/component-options/caption/demo.html
  samples/dashboards/component-options/caption/demo.js
  samples/dashboards/component-options/events/demo.css
  samples/dashboards/component-options/events/demo.details
  samples/dashboards/component-options/events/demo.html
  samples/dashboards/component-options/events/demo.js
  samples/dashboards/component-options/sync-highlight/demo.css
  samples/dashboards/component-options/sync-highlight/demo.details
  samples/dashboards/component-options/sync-highlight/demo.html
  samples/dashboards/component-options/sync-highlight/demo.js
  samples/dashboards/component-options/sync-visibility/demo.css
  samples/dashboards/component-options/sync-visibility/demo.details
  samples/dashboards/component-options/sync-visibility/demo.html
  samples/dashboards/component-options/sync-visibility/demo.js
  samples/dashboards/component-options/title/demo.css
  samples/dashboards/component-options/title/demo.details
  samples/dashboards/component-options/title/demo.html
  samples/dashboards/component-options/title/demo.js
  samples/dashboards/demo/sync-extremes/demo.css
  samples/dashboards/demo/sync-extremes/demo.details
  samples/dashboards/demo/sync-extremes/demo.html
  samples/dashboards/demo/sync-extremes/demo.js
  ts/Dashboards/Components/Component.ts
Labels: Product: Highcharts Dashboards

#19191 GUI demos
  samples/dashboards/gui/cell-class-name/demo.css
  samples/dashboards/gui/cell-class-name/demo.details
  samples/dashboards/gui/cell-class-name/demo.html
  samples/dashboards/gui/cell-class-name/demo.js
  samples/dashboards/gui/dimensions/demo.css
  samples/dashboards/gui/dimensions/demo.details
  samples/dashboards/gui/dimensions/demo.html
  samples/dashboards/gui/dimensions/demo.js
  samples/dashboards/gui/nested-layout/demo.css
  samples/dashboards/gui/nested-layout/demo.details
  samples/dashboards/gui/nested-layout/demo.html
  samples/dashboards/gui/nested-layout/demo.js
  samples/dashboards/gui/responsive/demo.css
  samples/dashboards/gui/responsive/demo.details
  samples/dashboards/gui/responsive/demo.html
  samples/dashboards/gui/responsive/demo.js
  ts/Dashboards/Layout/Cell.ts
  ts/Dashboards/Layout/Layout.ts
Labels: Product: Highcharts Dashboards

#19227 Responsive breakpoints demo
  samples/dashboards/responsive/responsive-breakpoints/demo.css
  samples/dashboards/responsive/responsive-breakpoints/demo.details
  samples/dashboards/responsive/responsive-breakpoints/demo.html
  samples/dashboards/responsive/responsive-breakpoints/demo.js
  ts/Dashboards/Board.ts
Labels: Product: Highcharts Dashboards

#19241 dash/resizer-update-state
  samples/cypress/dashboards/dashboard-layout/demo.mjs
  test/cypress/integration/Dashboards/json-serialization.cy.js
  ts/Dashboards/Actions/Resizer.ts
  ts/Dashboards/Layout/Cell.ts
Labels: Product: Highcharts Dashboards

#19207 db/edit-mode-drag-drop-enabled
  samples/dashboards/cypress/add-layout/demo.mjs
  samples/dashboards/cypress/edit-mode-options/demo.css
  samples/dashboards/cypress/edit-mode-options/demo.details
  samples/dashboards/cypress/edit-mode-options/demo.html
  samples/dashboards/cypress/edit-mode-options/demo.mjs
  test/cypress/integration/Dashboards/EditMode/dragdrop.cy.js
  ts/Dashboards/EditMode/EditMode.ts
  ts/Dashboards/EditMode/Toolbar/CellEditToolbar.ts
  ts/Dashboards/EditMode/Toolbar/RowEditToolbar.ts
Labels: Product: Highcharts Dashboards

#19244 Fixed minify-compatibility of component registry.
  samples/dashboards/components/custom-component/demo.js
  tools/gulptasks/pr-size-table.js
  ts/Dashboards/Actions/Bindings.ts
  ts/Dashboards/Board.ts
  ts/Dashboards/Components/Component.ts
  ts/Dashboards/Components/ComponentRegistry.ts
  ts/Dashboards/Plugins/DataGridPlugin.ts
  ts/Dashboards/Plugins/HighchartsPlugin.ts
Labels: Product: Highcharts Dashboards

#19239 dash/serialization-dragging
  test/cypress/integration/Dashboards/json-serialization.cy.js
Labels: Product: Highcharts Dashboards

#19256 dash/css-tweaks
  css/dashboards/gui.css
  css/datagrid.css
  samples/dashboards/demo/climate/demo.css
  test/cypress/integration/Dashboards/Components/DataGridComponent.cy.js
  test/cypress/integration/DataGrid/cell-header-format.cy.js
  ts/Dashboards/Plugins/DataGridComponent.ts
  ts/Dashboards/Plugins/DataGridSyncHandlers.ts
  ts/DataGrid/DataGrid.ts
  ts/DataGrid/Globals.ts
Labels: Product: Highcharts Dashboards
