Repository highcharts/highcharts, pull requests merged in 2023-03, with the labels that each got.

#18553 db/documentaion
  docs/dashboards/components.md
  docs/dashboards/sync.md
  docs/dashboards/types-of-components.md
  ts/Dashboards/Component/Component.ts
Labels: Db

#18592 db/api-contributing
  ts/Dashboards/CONTRIBUTING.md
  ts/Dashboards/README.md
Labels: Db

#18585 db/datastates-json
  test/typescript-karma/Dashboards/SerializeHelpers/DataStatesHelper.js
  ts/Dashboards/Board.ts
  ts/Dashboards/SerializeHelper/DataStatesHelper.ts
  ts/Data/DataStates.ts
Labels: Db

#18603 db/eslint-dashboards
  ts/Dashboards/.eslintrc
Labels: Db

#18596 docs/16096-api-panning-type-details
  ts/Core/Chart/ChartDefaults.ts
Labels: Product: Docs

#18604 bugfix/17280-zero-z-bubbles-disappear
  samples/unit-tests/series-bubble/extremes/demo.js
  samples/unit-tests/series-bubble/options/demo.js
Labels: Product: Highcharts, Changelog: Bugfix

#18569 Added custom selector for dashboards.
  css/dashboards/gui.css
  ts/Dashboards/EditMode/EditMode.ts
  ts/Dashboards/EditMode/EditRenderer.ts
  ts/Dashboards/EditMode/Menu/Menu.ts
  ts/Dashboards/EditMode/Menu/MenuItem.ts
  ts/Dashboards/EditMode/Sidebar.ts
  ts/Dashboards/Globals.ts
Labels: Db

#18651 bugfix/18636-waterfall-missing-lines
  samples/unit-tests/series-waterfall/null-value/demo.js
  ts/Series/Waterfall/WaterfallSeries.ts
Labels: Product: Highcharts, Changelog: Bugfix

#18671 db/confirmation-popup-refactor
  css/dashboards/gui.css
  ts/Dashboards/EditMode/ConfirmationPopup.ts
  ts/Dashboards/EditMode/EditGlobals.ts
  ts/Dashboards/EditMode/EditMode.ts
  ts/Shared/BaseForm.ts
Labels: Db

#18687 db/board-datapool
  ts/Dashboards/Board.ts
Labels: Db

#18606 db/board-api
  samples/dashboards/demos/climate/demo.js
  samples/dashboards/demos/component-html/demo.js
  samples/dashboards/demos/component-kpi/demo.js
  samples/dashboards/demos/layout-nested/demo.js
  samples/dashboards/demos/layout/demo.js
  samples/dashboards/demos/minimal/demo.js
  tools/gulptasks/dashboards/api-docs.json
  tools/gulptasks/dashboards/api-docs/typedoc/assets/custom.css
  ts/Dashboards/Board.ts
  ts/Dashboards/EditMode/EditMode.ts
  ts/Dashboards/Globals.ts
  ts/Dashboards/Layout/Cell.ts
  ts/Dashboards/Layout/Layout.ts
  ts/Dashboards/Layout/Row.ts
Labels: Db

#18663 db/rename-table-axis-map
  docs/dashboards/frequently-asked-questions.md
  docs/dashboards/types-of-components.md
  samples/dashboards/cypress/component-datagrid/demo.mjs
  samples/dashboards/demos/axes-sync/demo.js
  samples/dashboards/demos/climate/demo.js
  samples/dashboards/demos/datagrid-sync/demo.js
  samples/dashboards/demos/light-dark-theme/demo.js
  samples/dashboards/demos/minimal/demo.js
  samples/highcharts/studies/dashboard-strava-csv/demo.mjs
  ts/Extensions/DashboardPlugins/DataGridComponent.ts
  ts/Extensions/DashboardPlugins/HighchartsComponent.ts
  ts/Extensions/DashboardPlugins/HighchartsSyncHandlers.ts
Labels: Db

#18685 Db/demos-resize-flag
  docs/dashboards/frequently-asked-questions.md
  samples/cypress/dashboards/chart-interaction-one-way/demo.mjs
  samples/cypress/dashboards/chart-interaction-selection/demo.mjs
  samples/cypress/dashboards/chart-interaction/demo.mjs
  samples/cypress/dashboards/component-loading/demo.mjs
  samples/cypress/dashboards/layout-resize/demo.mjs
  samples/dashboards/demos/layout/demo.js
  samples/dashboards/demos/minimal/demo.js
  samples/highcharts/studies/dashboard-strava-csv/demo.mjs
  test/typescript-karma/Dashboards/Layout/tests.js
  ts/Dashboards/Actions/Bindings.ts
  ts/Dashboards/Board.ts
  ts/Dashboards/EditMode/Sidebar.ts
Labels: Db

#18598 Db/accordeon
  css/dashboards/gui.css
  gfx/dashboard-icons/dropdown-pointer.svg
  test/cypress/integration/Dashboards/edit-component.cy.js
  ts/Dashboards/EditMode/EditGlobals.ts
  ts/Dashboards/EditMode/EditRenderer.ts
  ts/Dashboards/EditMode/Menu/Menu.ts
  ts/Dashboards/EditMode/Menu/MenuItem.ts
  ts/Dashboards/EditMode/Menu/MenuItemBindings.ts
  ts/Dashboards/EditMode/Sidebar.ts
  ts/Extensions/DashboardPlugins/HighchartsComponent.ts
Labels: Db

#18681 bugfix/18635-outside-tooltip-inverted-scrollable
  ts/Core/Tooltip.ts
Labels: Product: Highcharts, Changelog: Bugfix

#18631 Db/datastates sync poc
  ts/Dashboards/Actions/Bindings.ts
  ts/Dashboards/Board.ts
  ts/Dashboards/Components/Component.ts
  ts/Dashboards/Components/Sync/Handler.ts
  ts/Dashboards/Components/Sync/Sync.ts
  ts/Data/Modifiers/RangeModifier.ts
  ts/Extensions/DashboardPlugins/DataGridSyncHandlers.ts
  ts/Extensions/DashboardPlugins/HighchartsComponent.ts
  ts/Extensions/DashboardPlugins/HighchartsSyncHandlers.ts
Labels: Db

#18582 Added Cypress visual tests
  .circleci/config.yml
  cypress.config.ts
  gulpfile.js
  package-lock.json
  package.json
  test/cypress/integration/Dashboards/Components/loading.cy.js
  test/cypress/support/index.js
  test/cypress/visual/Dashboards.cy.js
  test/cypress/visual/readme.md
  tools/gulptasks/update-pr-testresults-cypress.js
Labels: Db

#18719 db/JSON-api
  ts/Dashboards/Actions/Bindings.ts
  ts/Dashboards/Actions/Resizer.ts
  ts/Dashboards/Board.ts
  ts/Dashboards/CallbackRegistry.ts
  ts/Dashboards/Components/Component.ts
  ts/Dashboards/Components/HTMLComponent.ts
  ts/Dashboards/Components/SharedComponentState.ts
  ts/Dashboards/Layout/Cell.ts
  ts/Dashboards/Layout/Layout.ts
  ts/Dashboards/Layout/Row.ts
  ts/Dashboards/Serializable.ts
Labels: Db

#18703 db/iconURLPrefix
  ts/Dashboards/EditMode/EditContextMenu.ts
  ts/Dashboards/EditMode/EditMode.ts
  ts/Dashboards/EditMode/Sidebar.ts
  ts/Dashboards/EditMode/Toolbar/CellEditToolbar.ts
  ts/Dashboards/EditMode/Toolbar/EditToolbar.ts
  ts/Dashboards/EditMode/Toolbar/RowEditToolbar.ts
Labels: Db

#18728 db/component-width-unify
  samples/dashboards/demos/layout/demo.js
  ts/Dashboards/EditMode/Sidebar.ts
  ts/Dashboards/Layout/Cell.ts
Labels: Db

#18722 db/doclets-component-options-namespace
  ts/Dashboards/Actions/Bindings.ts
  ts/Dashboards/Components/Component.ts
  ts/Dashboards/Components/HTMLComponent.ts
  ts/Dashboards/Components/KPIComponent.ts
  ts/Extensions/DashboardPlugins/DataGridComponent.ts
  ts/Extensions/DashboardPlugins/HighchartsComponent.ts
Labels: Db

#18747 db/sidebar-switcher
  css/dashboards/gui.css
  samples/dashboards/demos/climate/demo.css
  ts/Dashboards/EditMode/EditGlobals.ts
  ts/Dashboards/EditMode/EditRenderer.ts
Labels: Db

#18661 db/sync-class-docs
  ts/Dashboards/Components/Sync/Sync.ts
Labels: Db

#18690 db/refactor-component-options
  css/dashboards/gui.css
  docs/dashboards/custom-component.md
  samples/cypress/dashboards/component-loading/demo.mjs
  samples/dashboards/cypress/add-layout/demo.mjs
  samples/dashboards/demos/climate/demo.css
  samples/dashboards/demos/component-html/demo.js
  samples/dashboards/demos/custom-component/demo.js
  samples/dashboards/demos/layout/demo.js
  samples/dashboards/demos/your-first-dashboard/demo.js
  test/typescript-karma/Dashboards/Layout/tests.js
  ts/Dashboards/Actions/Bindings.ts
  ts/Dashboards/Board.ts
  ts/Dashboards/Components/Component.ts
  ts/Dashboards/Components/ComponentGroup.ts
  ts/Dashboards/Components/ComponentRegistry.ts
  ts/Dashboards/Components/ComponentType.d.ts
  ts/Dashboards/Components/EditableOptions.ts
  ts/Dashboards/Components/HTMLComponent.ts
  ts/Dashboards/Components/KPIComponent.ts
  ts/Dashboards/Components/Sync/Emitter.ts
  ts/Dashboards/Components/Sync/Handler.ts
  ts/Dashboards/Components/Sync/Sync.ts
  ts/Dashboards/Components/ThresholdComponent.ts
  ts/Dashboards/EditMode/EditRenderer.ts
  ts/Dashboards/EditMode/Sidebar.ts
  ts/Dashboards/PluginHandler.ts
  ts/Extensions/DashboardPlugins/DataGridComponent.ts
  ts/Extensions/DashboardPlugins/DataGridPlugin.ts
  ts/Extensions/DashboardPlugins/DataGridSyncHandlers.ts
  ts/Extensions/DashboardPlugins/HighchartsComponent.ts
  ts/Extensions/DashboardPlugins/HighchartsPlugin.ts
  ts/Extensions/DashboardPlugins/HighchartsSyncHandlers.ts
  ts/masters/modules/dashboards-plugin.src.ts
Labels: Db

#18666 bugfix/18542-map-panning-update-zoom
  samples/unit-tests/maps/map-navigation/demo.js
  samples/unit-tests/maps/setdata/demo.js
  ts/Maps/MapView.ts
  ts/Series/Map/MapSeries.ts
Labels: Product: Highcharts Maps, Changelog: Bugfix

#18735 db/sync-tooltip-highlight
  docs/dashboards/frequently-asked-questions.md
  samples/cypress/dashboards/chart-interaction-one-way/demo.mjs
  samples/cypress/dashboards/chart-interaction/demo.mjs
  samples/dashboards/cypress/component-datagrid/demo.mjs
  samples/dashboards/demos/axes-sync/demo.js
  samples/dashboards/demos/climate/demo.js
  samples/dashboards/demos/datagrid-sync/demo.js
  samples/dashboards/demos/light-dark-theme/demo.js
  samples/dashboards/demos/minimal/demo.js
  ts/Dashboards/Components/Component.ts
  ts/Dashboards/Components/Sync/Sync.ts
  ts/Extensions/DashboardPlugins/DataGridSyncHandlers.ts
  ts/Extensions/DashboardPlugins/HighchartsSyncHandlers.ts
Labels: Db

#18746 db/cy-board-fix
  test/cypress/support/index.js
  test/cypress/visual/Dashboards.cy.js
Labels: Db

#18758 bugfix/18584-vertical-line-local-storage-update
  samples/unit-tests/stock-tools/bindings/demo.js
  ts/Extensions/Annotations/Types/VerticalLine.ts
Labels: Product: Highcharts Stock, Changelog: Bugfix

#18765 bugfix/14080-bubblelegend-prevent-default-click
  samples/unit-tests/bubble-legend/layout/demo.js
  ts/Core/Foundation.ts
  ts/Series/Bubble/BubbleLegendComposition.ts
Labels: Product: Highcharts, Changelog: Bugfix

#18759 db/kpi-drag-sidebar
  test/cypress/integration/Dashboards/component-add.cy.js
  ts/Dashboards/EditMode/Sidebar.ts
Labels: Db

#18772 db/dashboards-compile-minify
  ts/Dashboards/Layout/GUIElement.ts
  ts/Data/Connectors/DataConnector.ts
  ts/Data/Converters/CSVConverter.ts
  ts/Data/Converters/DataConverter.ts
Labels: Db
