Repository highcharts/highcharts, pull requests merged in 2023-01, with the labels that each got.

#18218 db/climate-cities
  samples/dashboard/demos/climate/demo.js
Labels: Db

#18221 db/climate-map
  samples/.eslintignore
  samples/dashboard/demos/climate/demo.css
  samples/dashboard/demos/climate/demo.js
Labels: Db

#18223 db/navigator-climate-demo
  samples/dashboard/demos/climate/demo.css
  samples/dashboard/demos/climate/demo.html
  samples/dashboard/demos/climate/demo.js
Labels: Db

#18201 bugfix/16753-number-in-parameter-name
  ts/Extensions/Annotations/Popup/Popup.ts
Labels: Product: Highcharts Stock, Changelog: Bugfix

#18200 bugfix/indicators-with-empty-dataset
  samples/unit-tests/indicator-cmf/recalculations/demo.js
  ts/Stock/Indicators/SMA/SMAIndicator.ts
Labels: Product: Highcharts Stock, Changelog: Bugfix

#18105 Docs: Deactivated dataAsColumns option.
  ts/Data/DataSeriesComposition.ts
Labels: Product: Docs

#18225 bugfix/17114-datagrouping-error-plotsize-zero
  samples/unit-tests/series/datagrouping/demo.js
  ts/Extensions/DataGrouping/DataGroupingSeriesComposition.ts
Labels: Product: Highcharts Stock, Changelog: Bugfix

#18199 db/HTMLTableConverterHelper
  package-lock.json
  test/typescript-karma/Dashboard/SerializeHelpers/CSVConverterHelper.test.js
  test/typescript-karma/Dashboard/SerializeHelpers/HTMLTableConverterHelper.test.js
  test/typescript-karma/DataGrid/DataGrid/tests.js
  ts/Dashboard/SerializeHelper/HTMLTableConverterHelper.ts
  ts/Dashboard/SerializeHelper/HTMLTableStoreHelper.ts
Labels: Db

#18232 db/climate-city
  samples/dashboard/demos/climate/demo.css
  samples/dashboard/demos/climate/demo.js
Labels: Db

#18240 db/loading
  samples/dashboard/demos/climate/demo.js
Labels: Db

#18250 db/dataGrid-update
  samples/dashboard/demos/climate/demo.js
Labels: Db

#18254 db/bugfix-worlddate
  samples/dashboard/demos/climate/demo.js
Labels: Db

#18206 Db/redraw title caption
  test/typescript-karma/Dashboard/Component/tests.js
  ts/Dashboard/Component/Component.ts
  ts/Dashboard/Component/HTMLComponent.ts
  ts/Dashboard/Component/KPIComponent.ts
  ts/Extensions/DashboardPlugins/DataGridComponent.ts
  ts/Extensions/DashboardPlugins/HighchartsComponent.ts
Labels: Db

#18230 db/climate-marker
  samples/dashboard/demos/climate/demo.css
  samples/dashboard/demos/climate/demo.js
Labels: Db

#18226 db/climate-demo-kpi
  samples/dashboard/demos/climate/demo.css
  samples/dashboard/demos/climate/demo.js
  ts/Dashboard/Actions/Bindings.ts
  ts/Dashboard/Globals.ts
  ts/Dashboard/Layout/Cell.ts
Labels: Db

#18277 Fixed recursive call to resize in KPIComponent
  ts/Dashboard/Component/KPIComponent.ts
Labels: Db

#18274 db/city-data
  samples/dashboard/demos/climate/demo.js
  samples/data/climate-cities.csv
Labels: Db

#18228 bugfix/18137-map-border-width-hover
  ts/Core/Renderer/SVG/SVGElement.ts
  ts/Series/Map/MapSeries.ts
Labels: Product: Highcharts Maps, Changelog: Bugfix

#18283 bugfix/18246-mapline-colorbypoint-api
  samples/maps/plotoptions/mapline-colorbypoint-false/demo.css
  samples/maps/plotoptions/mapline-colorbypoint-false/demo.details
  samples/maps/plotoptions/mapline-colorbypoint-false/demo.html
  samples/maps/plotoptions/mapline-colorbypoint-false/demo.js
  samples/maps/plotoptions/mapline-colorbypoint-true/demo.css
  samples/maps/plotoptions/mapline-colorbypoint-true/demo.details
  samples/maps/plotoptions/mapline-colorbypoint-true/demo.html
  samples/maps/plotoptions/mapline-colorbypoint-true/demo.js
  ts/Series/Map/MapSeries.ts
Labels: Product: Docs, Product: Highcharts Maps

#18270 db/chart-update-store
  samples/dashboard/demos/dashboard-datagrid-component/demo.mjs
  test/cypress/integration/Dashboard/Components/DataGridComponent.cy.js
  ts/Extensions/DashboardPlugins/DataGridComponent.ts
  ts/Extensions/DashboardPlugins/HighchartsComponent.ts
Labels: Db

#18285 Db/fix default editable options
  ts/Dashboard/Component/Component.ts
  ts/Dashboard/Component/HTMLComponent.ts
  ts/Extensions/DashboardPlugins/HighchartsComponent.ts
Labels: Db

#18287 Db demo: Reduced lag within navigator
  samples/dashboard/demos/climate/demo.js
Labels: Db

#18271 db/a11y
  css/dashboard/gui.scss
  samples/dashboard/demos/climate/demo.html
  samples/dashboard/demos/dashboard-minimal/demo.html
  ts/Dashboard/EditMode/EditRenderer.ts
  ts/Dashboard/Layout/Cell.ts
Labels: Db

#18280 db/climate-hamburger
  samples/dashboard/demos/climate/demo.css
  samples/dashboard/demos/climate/demo.js
Labels: Db

#18294 db/instanceof-HighchartsComponent
  samples/dashboard/cypress/dashboard-datagrid-component/demo.css
  samples/dashboard/cypress/dashboard-datagrid-component/demo.html
  samples/dashboard/cypress/dashboard-datagrid-component/demo.mjs
  samples/dashboard/demos/dashboard-datagrid-component/demo.html
  samples/dashboard/demos/dashboard-datagrid-component/demo.js
  test/cypress/integration/Dashboard/Components/DataGridComponent.cy.js
  ts/Extensions/DashboardPlugins/DataGridPlugin.ts
  ts/Extensions/DashboardPlugins/DataGridSyncHandlers.ts
  ts/Extensions/DashboardPlugins/HighchartsSyncHandlers.ts
  ts/masters/modules/dashboard-plugin.src.ts
Labels: Db

#18315 db/resizer-zindex-icons
  css/dashboard/gui.scss
Labels: Db

#18289 db/navigator-colors
  samples/dashboard/demos/climate/demo.css
  samples/dashboard/demos/climate/demo.js
Labels: Db

#18041 Fixed #17998, linecap not being applied to legend and dashed series
  ts/Core/Legend/LegendSymbol.ts
  ts/Series/Line/LineSeries.ts
Labels: Changelog: Bugfix

#18307 db/docs-first-dashboard
  docs/dashboards/your-first-dashboard.md
  docs/doc-config.js
  samples/dashboard/demos/your-first-dashboard/demo.css
  samples/dashboard/demos/your-first-dashboard/demo.details
  samples/dashboard/demos/your-first-dashboard/demo.html
  samples/dashboard/demos/your-first-dashboard/demo.js
Labels: Db

#18224 db/climate-demo-datagrid
  css/dashboard/gui.scss
  samples/dashboard/demos/climate/demo.js
  ts/DataGrid/DataGrid.ts
  ts/Extensions/DashboardPlugins/DataGridSyncHandlers.ts
  ts/Extensions/DashboardPlugins/HighchartsSyncHandlers.ts
Labels: Db

#18310 Db/docs installation
  docs/dashboards/installation.md
  docs/doc-config.js
Labels: Db

#18322 Db/edit mode design
  samples/dashboard/demos/climate/demo.css
  ts/Dashboard/EditMode/EditMode.ts
Labels: Db

#18341 db/map-boundings
  samples/dashboard/demos/climate/demo.js
Labels: Db

#18333 Db/docs edit mode
  docs/dashboards/edit-mode-context-menu.png
  docs/dashboards/edit-mode-sidebar.png
  docs/dashboards/edit-mode-tooltip.png
  docs/dashboards/edit-mode.md
  docs/doc-config.js
Labels: Db

#18325 db/climate-colors
  samples/dashboard/demos/climate/demo.css
  samples/dashboard/demos/climate/demo.js
Labels: Db

#17600 Treegraph series type completion
  docs/chart-and-series-types/treegraph-chart.md
  docs/doc-config.js
  docs/sidebars.js
  samples/highcharts/demo/treegraph-boxes/demo.css
  samples/highcharts/demo/treegraph-boxes/demo.details
  samples/highcharts/demo/treegraph-boxes/demo.html
  samples/highcharts/demo/treegraph-boxes/demo.js
  samples/highcharts/demo/treegraph-chart/demo.css
  samples/highcharts/demo/treegraph-chart/demo.details
  samples/highcharts/demo/treegraph-chart/demo.html
  samples/highcharts/demo/treegraph-chart/demo.js
  samples/highcharts/demo/treegraph-inverted/demo.css
  samples/highcharts/demo/treegraph-inverted/demo.details
  samples/highcharts/demo/treegraph-inverted/demo.html
  samples/highcharts/demo/treegraph-inverted/demo.js
  samples/highcharts/series-treegraph/collapse-button-options/demo.js
  samples/highcharts/series-treegraph/collapsed-node/demo.details
  samples/highcharts/series-treegraph/collapsed-node/demo.js
  samples/highcharts/series-treegraph/color-variation/demo.css
  samples/highcharts/series-treegraph/color-variation/demo.details
  samples/highcharts/series-treegraph/color-variation/demo.html
  samples/highcharts/series-treegraph/color-variation/demo.js
  samples/highcharts/series-treegraph/dot-and-label/demo.css
  samples/highcharts/series-treegraph/dot-and-label/demo.details
  samples/highcharts/series-treegraph/dot-and-label/demo.html
  samples/highcharts/series-treegraph/dot-and-label/demo.js
  samples/highcharts/series-treegraph/level-options/demo.details
  samples/highcharts/series-treegraph/level-options/demo.js
  samples/highcharts/series-treegraph/link-text-path/demo.details
  samples/highcharts/series-treegraph/link-text-path/demo.js
  samples/highcharts/series-treegraph/link-types/demo.details
  samples/highcharts/series-treegraph/link-types/demo.js
  samples/highcharts/series-treegraph/node-level/demo.details
  samples/highcharts/series-treegraph/node-level/demo.js
  samples/highcharts/series-treegraph/reversed-nodes/demo.details
  samples/highcharts/series-treegraph/reversed-nodes/demo.js
  samples/highcharts/series-treegraph/treegraph-phylogenetic/demo.css
  samples/highcharts/studies/tree-toggle/demo.css
  samples/highcharts/studies/tree-toggle/demo.details
  samples/highcharts/studies/tree-toggle/demo.html
  samples/highcharts/studies/tree-toggle/demo.js
  samples/highcharts/studies/tree-toggle/readme.md
  samples/highcharts/studies/treegraph-chart/demo.css
  samples/highcharts/studies/treegraph-chart/demo.details
  samples/highcharts/studies/treegraph-chart/demo.html
  samples/highcharts/studies/treegraph-chart/demo.js
  ts/Core/Defaults.ts
  ts/Core/Renderer/SVG/SVGLabel.ts
  ts/Core/Series/DataLabel.ts
  ts/Series/Organization/OrganizationSeries.ts
  ts/Series/PathUtilities.ts
  ts/Series/Treegraph/TreegraphPoint.ts
  ts/Series/Treegraph/TreegraphSeries.ts
  ts/Series/Treegraph/TreegraphSeriesDefaults.ts
  ts/Series/Treegraph/TreegraphSeriesOptions.d.ts
  ts/Series/Treemap/TreemapSeries.ts
Labels: Changelog: Feature

#18357 db/climate-source
  samples/dashboard/demos/climate/demo.html
  samples/dashboard/demos/climate/demo.js
Labels: Db

#18352 db/kpi-plugin
  samples/dashboard/demos/dashboard-component-kpi/demo.html
  samples/dashboard/demos/dashboard-component-kpi/demo.js
  ts/Dashboard/Actions/Bindings.ts
  ts/Dashboard/Component/KPIComponent.ts
  ts/Extensions/DashboardPlugins/HighchartsPlugin.ts
Labels: Db

#18350 db/kpi-navigator-series-type
  samples/dashboard/demos/climate/demo.css
  samples/dashboard/demos/climate/demo.js
Labels: Db

#18331 db/docs-types-of-components
  docs/dashboards/types-of-components.md
  docs/doc-config.js
  samples/dashboard/demos/component-highcharts/demo.css
  samples/dashboard/demos/component-highcharts/demo.details
  samples/dashboard/demos/component-highcharts/demo.html
  samples/dashboard/demos/component-highcharts/demo.js
  samples/dashboard/demos/component-html/demo.css
  samples/dashboard/demos/component-html/demo.details
  samples/dashboard/demos/component-html/demo.html
  samples/dashboard/demos/component-html/demo.js
Labels: Db

#18368 db/resizer-bug
  samples/dashboard/demos/dashboard-layout-nested/demo.js
  ts/Dashboard/Actions/Resizer.ts
Labels: Db

#18365 db/main-readme
  docs/dashboards/installation.md
  ts/Dashboard/README.md
  ts/Data/README.md
Labels: Db

#18376 bugfix/18312-tooltip-split
  ts/Core/Defaults.ts
Labels: Product: Docs

#18358 db/climate-silhouette
  samples/dashboards/demos/climate/demo.css
Labels: Db

#18353 db/climate-loading
  samples/dashboards/demos/climate/demo.js
Labels: Db

#18385 db/climate-css-class
  samples/dashboards/demos/climate/demo.css
Labels: Db

#18388 db/kpi-design
  samples/dashboards/demos/climate/demo.css
  samples/dashboards/demos/climate/demo.html
  samples/dashboards/demos/climate/demo.js
Labels: Db

#18386 db/datagrid-focus
  ts/Extensions/DashboardPlugins/DataGridComponent.ts
Labels: Db

#18402 db/linted-modules
  ts/Dashboards/Actions/Bindings.ts
  ts/Dashboards/Layout/Cell.ts
  ts/Dashboards/Layout/Layout.ts
  ts/Dashboards/Layout/Row.ts
Labels: Db

#18393 db/click-selected-city
  samples/dashboards/demos/climate/demo.js
Labels: Db

#18404 db/lint-quick-fix
  ts/Dashboards/Component/Component.ts
  ts/Dashboards/Component/ComponentUtilities.ts
  ts/Dashboards/Component/EditableOptions.ts
  ts/Dashboards/Component/ThresholdComponent.ts
Labels: Db

#18391 db/fullscreen-incorrect-offsets
  css/dashboards/gui.scss
  docs/dashboards/edit-mode.md
  docs/dashboards/your-first-dashboard.md
  samples/cypress/dashboards/dashboard-layout/demo.html
  samples/cypress/dashboards/layout-resize/demo.html
  samples/dashboards/cypress/add-layout/demo.html
  samples/dashboards/cypress/component-datagrid/demo.html
  samples/dashboards/demos/climate/demo.html
  samples/dashboards/demos/datagrid-sync/demo.html
  samples/dashboards/demos/layout-nested/demo.html
  samples/dashboards/demos/layout/demo.html
  samples/dashboards/demos/light-dark-theme/demo.html
  samples/dashboards/demos/minimal/demo.html
  samples/dashboards/demos/your-first-dashboard/demo.html
  ts/Dashboard/README.md
  ts/Dashboards/Dashboard.ts
  ts/Dashboards/EditMode/Fullscreen.ts
  ts/Dashboards/Globals.ts
  ts/Dashboards/Layout/GUIElement.ts
Labels: Db

#18405 db/update-store-chart
  samples/dashboards/demos/datagrid-sync/demo.js
  ts/Extensions/DashboardPlugins/HighchartsComponent.ts
Labels: Db
