Repository highcharts/highcharts, pull requests merged in 2023-04, with the labels that each got.

#18752 db/cursor-visibility-sync
  samples/cypress/dashboards/chart-series-visibility/demo.css
  samples/cypress/dashboards/chart-series-visibility/demo.details
  samples/cypress/dashboards/chart-series-visibility/demo.html
  samples/cypress/dashboards/chart-series-visibility/demo.js
  test/cypress/integration/Dashboards/sync/series-visibility.cy.js
  ts/Extensions/DashboardPlugins/HighchartsSyncHandlers.ts
Labels: Db

#18761 db/doclets-pluginHandler
  tools/gulptasks/dashboards/api-docs.json
  ts/Dashboards/PluginHandler.ts
Labels: Db

#18774 db/compare-library-pr
  .circleci/config.yml
  tools/gulptasks/pr-size-table.js
Labels: Db

#18780 db/nested-layouts-serialization
  test/typescript-karma/Dashboards/Layout/tests.js
  ts/Dashboards/Layout/Cell.ts
  ts/Dashboards/Layout/Layout.ts
  ts/Dashboards/Layout/Row.ts
Labels: Db

#18777 bugfix/18741-dragging-negative-stacked-bar
  samples/unit-tests/dragdrop/dynamic/demo.js
  ts/Extensions/DraggablePoints.ts
Labels: Changelog: Bugfix

#18721 bugfix/18074-dragdrop-mappoint
  samples/maps/series/draggable-mappoint/demo.css
  samples/maps/series/draggable-mappoint/demo.details
  samples/maps/series/draggable-mappoint/demo.html
  samples/maps/series/draggable-mappoint/demo.js
  samples/unit-tests/dragdrop/mappoint/demo.css
  samples/unit-tests/dragdrop/mappoint/demo.details
  samples/unit-tests/dragdrop/mappoint/demo.html
  samples/unit-tests/dragdrop/mappoint/demo.js
  ts/Extensions/DraggablePoints.ts
  ts/Series/Heatmap/HeatmapSeries.ts
  ts/Series/Map/MapSeries.ts
  ts/Series/MapLine/MapLineSeries.ts
Labels: Product: Highcharts Maps, Changelog: Bugfix

#18723 Db/synchandler doclets
  tools/gulptasks/dashboards/api-docs.json
  ts/Dashboards/Components/Sync/Emitter.ts
  ts/Dashboards/Components/Sync/Handler.ts
Labels: Db

#18811 db/dataCursor-dataGrid
  samples/dashboards/cypress/component-datagrid/demo.html
  samples/dashboards/cypress/component-datagrid/demo.mjs
  test/cypress/integration/Dashboards/Components/DataGridComponent.cy.js
Labels: Db

#18434 feature/new-series-geoheatmap
  docs/maps/geoheatmap-series.md
  docs/sidebars.js
  samples/data/geoheatmap-aerosol-dataset.json
  samples/data/geoheatmap-cities-dataset.json
  samples/data/geoheatmap-leaf-dataset.json
  samples/maps/demo/geoheatmap-equalearth/demo.css
  samples/maps/demo/geoheatmap-equalearth/demo.details
  samples/maps/demo/geoheatmap-equalearth/demo.html
  samples/maps/demo/geoheatmap-equalearth/demo.js
  samples/maps/demo/geoheatmap-europe/demo.css
  samples/maps/demo/geoheatmap-europe/demo.details
  samples/maps/demo/geoheatmap-europe/demo.html
  samples/maps/demo/geoheatmap-europe/demo.js
  samples/maps/demo/geoheatmap-orthographic/demo.css
  samples/maps/demo/geoheatmap-orthographic/demo.details
  samples/maps/demo/geoheatmap-orthographic/demo.html
  samples/maps/demo/geoheatmap-orthographic/demo.js
  samples/maps/demo/geoheatmap-orthographic/readme.md
  samples/unit-tests/coloraxis/series-types/demo.html
  samples/unit-tests/coloraxis/series-types/demo.js
  samples/unit-tests/maps/geoheatmap/demo.css
  samples/unit-tests/maps/geoheatmap/demo.details
  samples/unit-tests/maps/geoheatmap/demo.html
  samples/unit-tests/maps/geoheatmap/demo.js
  studies/maps/geoheatmap/demo.details
  studies/maps/geoheatmap/demo.html
  test/karma-files.json
  ts/Series/GeoHeatmap/GeoHeatmapPoint.ts
  ts/Series/GeoHeatmap/GeoHeatmapPointOptions.ts
  ts/Series/GeoHeatmap/GeoHeatmapSeries.ts
  ts/Series/GeoHeatmap/GeoHeatmapSeriesOptions.ts
  ts/Series/Map/MapPointOptions.d.ts
  ts/Series/Map/MapSeries.ts
  ts/masters/modules/geoheatmap.src.ts
Labels: Product: Highcharts Maps, Flow: In progress

#18824 Unified the iconsURLPrefix.
  ts/Dashboards/EditMode/EditGlobals.ts
  ts/Dashboards/EditMode/EditMode.ts
  ts/Dashboards/EditMode/EditRenderer.ts
  ts/Dashboards/EditMode/Sidebar.ts
  ts/Dashboards/Globals.ts
Labels: Db

#18833 Db/onchange for toggles
  samples/dashboards/demos/minimal/demo.js
  ts/Dashboards/EditMode/AccordeonMenu.ts
  ts/Dashboards/EditMode/EditRenderer.ts
  ts/Extensions/DashboardPlugins/HighchartsComponent.ts
Labels: Db

#18834 Created doclets for accoreon class.
  tools/gulptasks/dashboards/api-docs.json
  ts/Dashboards/EditMode/AccordeonMenu.ts
  ts/Dashboards/EditMode/EditRenderer.ts
Labels: Db

#18844 Implemented serialization of json chart options.
  ts/Dashboards/EditMode/AccordeonMenu.ts
Labels: Db

#18846 Improved styles of the accordeon button.
  css/dashboards/gui.css
  ts/Dashboards/EditMode/AccordeonMenu.ts
  ts/Dashboards/EditMode/EditGlobals.ts
Labels: Db

#18612 bugfix/18303-point-visibility-drillup
  samples/unit-tests/drilldown/pie/demo.js
  ts/Extensions/Drilldown.ts
Labels: Product: Highcharts

#18851 Deleted old sidebar.
  ts/Dashboards/EditMode/EditMode.ts
  ts/Dashboards/EditMode/Sidebar.ts
Labels: Db

#18803 Db/ci visual order
  .circleci/config.yml
  samples/cypress/dashboards/chart-series-visibility/demo.js
Labels: Db

#18850 db/fix-context-menu-buttons
  css/dashboards/gui.css
  ts/Dashboards/EditMode/ConfirmationPopup.ts
  ts/Dashboards/EditMode/EditContextMenu.ts
  ts/Dashboards/EditMode/EditRenderer.ts
  ts/Dashboards/EditMode/Menu/MenuItem.ts
  ts/Dashboards/EditMode/Toolbar/CellEditToolbar.ts
Labels: Db

#18796 db/removed-exporting-layout
  samples/dashboards/demos/layout/demo.js
Labels: Db

#18784 db/datagrid-new-api-options
  samples/data-grid/basic/cells-formatting/demo.css
  samples/data-grid/basic/cells-formatting/demo.html
  samples/data-grid/basic/cells-formatting/demo.js
  samples/data-grid/basic/simple/demo.css
  samples/data-grid/basic/simple/demo.js
  test/cypress/integration/DataGrid/cell-header-format.cy.js
  ts/DataGrid/DataGrid.ts
  ts/DataGrid/DataGridOptions.d.ts
Labels: Db

#18875 db/dataPool-connector-names
  test/typescript-karma/Data/DataPool.test.js
  ts/Data/DataPool.ts
Labels: Db

#18773 bugfix/18753-area-chart-legend-marker
  samples/highcharts/series/legend-symbol/demo.css
  samples/highcharts/series/legend-symbol/demo.details
  samples/highcharts/series/legend-symbol/demo.html
  samples/highcharts/series/legend-symbol/demo.js
  ts/Core/Axis/Color/ColorAxis.ts
  ts/Core/Legend/LegendSymbol.ts
  ts/Core/Series/Series.ts
  ts/Core/Series/SeriesDefaults.ts
  ts/Core/Series/SeriesOptions.d.ts
  ts/Series/Area/AreaSeries.ts
  ts/Series/AreaSpline/AreaSplineSeries.ts
  ts/Series/Bellcurve/BellcurveSeries.ts
  ts/Series/Column/ColumnSeries.ts
  ts/Series/FlowMap/FlowMapSeries.ts
  ts/Series/Heatmap/HeatmapSeries.ts
  ts/Series/Line/LineSeries.ts
  ts/Series/Map/MapSeries.ts
  ts/Series/MapLine/MapLineSeries.ts
  ts/Series/MapPoint/MapPointSeries.ts
  ts/Series/Pie/PieSeries.ts
  ts/Series/Polygon/PolygonSeries.ts
  ts/Series/SolidGauge/SolidGaugeSeries.ts
  ts/Series/Timeline/TimelineSeries.ts
  ts/Series/Timeline/TimelineSeriesDefaults.ts
  ts/Series/Treemap/TreemapSeries.ts
  ts/Series/Venn/VennSeries.ts
Labels: Product: Highcharts, Changelog: Bugfix

#18819 Db/Sidebar refactor
  css/dashboards/gui.css
  gfx/dashboard-icons/close.svg
  gfx/dashboard-icons/settings.svg
  samples/cypress/dashboards/dashboard-layout/demo.mjs
  samples/cypress/dashboards/layout-resize/demo.mjs
  samples/dashboards/demos/climate/demo.js
  test/cypress/integration/Dashboards/component-add.cy.js
  test/cypress/integration/Dashboards/edit-component.cy.js
  test/cypress/support/index.js
  tools/gulptasks/dashboards/api-docs.json
  ts/Dashboards/Components/Component.ts
  ts/Dashboards/Components/EditableOptions.ts
  ts/Dashboards/Components/HTMLComponent.ts
  ts/Dashboards/EditMode/AccordionMenu.ts
  ts/Dashboards/EditMode/ConfirmationPopup.ts
  ts/Dashboards/EditMode/EditContextMenu.ts
  ts/Dashboards/EditMode/EditGlobals.ts
  ts/Dashboards/EditMode/EditMode.ts
  ts/Dashboards/EditMode/EditRenderer.ts
  ts/Dashboards/EditMode/Menu/MenuItem.ts
  ts/Dashboards/EditMode/Sidebar.ts
  ts/Dashboards/EditMode/SidebarPopup.ts
  ts/Dashboards/EditMode/Toolbar/CellEditToolbar.ts
  ts/Dashboards/Globals.ts
  ts/Extensions/DashboardPlugins/HighchartsComponent.ts
Labels: Db
