Repository highcharts/highcharts, pull requests merged in 2024-06, with the labels that each got.

#21193 bugfix/ 11794-bigger-linewidth-for-boost
  ts/Core/Renderer/HTML/AST.ts
  ts/Core/Renderer/SVG/SVGAttributes.d.ts
  ts/Extensions/Boost/BoostChart.ts
  ts/Extensions/Boost/BoostSeries.ts
Labels: Product: Highcharts, Changelog: Bugfix

#21195 bugfix/20877-ordinal-panning
  samples/unit-tests/axis/extremes/demo.js
  ts/Core/Axis/OrdinalAxis.ts
  ts/Core/Pointer.ts
Labels: Product: Highcharts Stock, Changelog: Bugfix

#21100 dash/20756-edit-mode-change-event
  css/dashboards/dashboards.css
  docs/dashboards/edit-mode.md
  samples/dashboards/cypress/edit-mode-options/demo.html
  samples/dashboards/cypress/edit-mode-options/demo.mjs
  samples/dashboards/edit-mode/events/demo.css
  samples/dashboards/edit-mode/events/demo.details
  samples/dashboards/edit-mode/events/demo.html
  samples/dashboards/edit-mode/events/demo.js
  test/cypress/dashboards/integration/Components/events.cy.js
  test/cypress/dashboards/integration/EditMode/sidebar.cy.js
  test/cypress/support/index.js
  ts/Dashboards/Actions/DragDrop.ts
  ts/Dashboards/EditMode/AccordionMenu.ts
  ts/Dashboards/EditMode/ConfirmationPopup.ts
  ts/Dashboards/EditMode/EditGlobals.ts
  ts/Dashboards/EditMode/SidebarPopup.ts
  ts/Dashboards/EditMode/Toolbar/CellEditToolbar.ts
  ts/Dashboards/EditMode/Toolbar/RowEditToolbar.ts
Labels: Changelog: Feature, Product: Highcharts Dashboards

#21259 More forgiving turboThreshold
  samples/dashboards/studies/sun-horizon/demo.js
  samples/gantt/gantt/bigdata/demo.js
  samples/highcharts/boost/heatmap/demo.js
  samples/highcharts/boost/line-series-heavy-dynamic/demo.js
  samples/highcharts/boost/line-series-heavy-stock/demo.js
  samples/highcharts/boost/line-series-heavy/demo.js
  samples/highcharts/chartchooser/categorical-comparison-treemap-monochrome/demo.js
  samples/highcharts/chartchooser/categorical-comparison-treemap/demo.js
  samples/highcharts/demo/heatmap-canvas/demo.js
  samples/highcharts/series-networkgraph/forces/demo.js
  samples/maps/demo/lightning/demo.js
  samples/stock/members/series-update/demo.js
  ts/Core/Series/Point.ts
  ts/Core/Series/Series.ts
  ts/Core/Series/SeriesDefaults.ts
Labels: Changelog: Bugfix

#21196 demo/moving-sparkline-chart
  samples/highcharts/demo/sparkline/demo.details
Labels: Product: Highcharts, Changelog: Feature

#21219 bugfix/19944-event-target-documentmousemove
  ts/Core/Pointer.ts
Labels: Product: Highcharts, Changelog: Bugfix

#21272 docs/21228-missing-pane-array-declarations
  package-lock.json
  ts/Extensions/Pane/PaneDefaults.ts
Labels: Product: Docs, Product: TypeScript

#21247 bugfix/21064-stock-tools-active-class
  ts/Extensions/Annotations/NavigationBindings.ts
  ts/Stock/StockTools/StockToolsGui.ts
Labels: Product: Highcharts Stock, Changelog: Bugfix

#21108 moving-demos-to-trees-and-networks
  samples/highcharts/demo/organization-chart/demo.details
  samples/highcharts/demo/organization-hanging/demo.details
  samples/highcharts/demo/sankey-diagram/demo.details
  samples/highcharts/demo/sunburst/demo.details
  samples/highcharts/demo/treegraph-boxes/demo.details
  samples/highcharts/demo/treegraph-chart/demo.details
  samples/highcharts/demo/treegraph-inverted/demo.details
Labels: Product: Highcharts

#21246 dash/datagrid2-td-resizing-scrolling
  css/datagrid/datagrid2.css
  samples/data-grid/basic/data-grid-2-benchmark/demo.js
  samples/data-grid/basic/data-grid-2-fixed-distribution/demo.css
  samples/data-grid/basic/data-grid-2-fixed-distribution/demo.html
  samples/data-grid/basic/data-grid-2-fixed-distribution/demo.js
  samples/data-grid/basic/data-grid-2/demo.js
  ts/DataGrid/DataGrid2/Actions/ColumnsResizer.ts
  ts/DataGrid/DataGrid2/Actions/RowsVirtualizer.ts
  ts/DataGrid/DataGrid2/DataGrid.ts
  ts/DataGrid/DataGrid2/DataGridCell.ts
  ts/DataGrid/DataGrid2/DataGridColumn.ts
  ts/DataGrid/DataGrid2/DataGridDefaultOptions.ts
  ts/DataGrid/DataGrid2/DataGridOptions.d.ts
  ts/DataGrid/DataGrid2/DataGridRow.ts
  ts/DataGrid/DataGrid2/DataGridTable.ts
  ts/DataGrid/DataGrid2/DataGridTableHead.ts
  ts/DataGrid/DataGrid2/Utils.ts
Labels: Type: Enhancement, Product: Highcharts Dashboards

#21153 bugfix/16915-minPadding-navigator-ignored
  samples/unit-tests/navigator/navigator/demo.js
  ts/Stock/Navigator/Navigator.ts
Labels: Product: Highcharts Stock, Changelog: Bugfix

#21114 demo/pnf-series-move-to-demo
  samples/highcharts/studies/pointandfigure/demo.details
  samples/highcharts/studies/pointandfigure/demo.html
  samples/stock/demo/pointandfigure/demo.css
  samples/stock/demo/pointandfigure/demo.details
  samples/stock/demo/pointandfigure/demo.html
  samples/stock/demo/pointandfigure/demo.js
Labels: Product: Highcharts Stock

#21135 demo/neural-network-demo
  samples/highcharts/demo/neural-network/demo.css
  samples/highcharts/demo/neural-network/demo.details
  samples/highcharts/demo/neural-network/demo.html
  samples/highcharts/demo/neural-network/demo.js
  samples/highcharts/demo/neural-network/readme.md
Labels: Product: Highcharts

#21311 bugfix/21176-boost-multiple-axes-point-flickers
  samples/unit-tests/boost/general/demo.js
  ts/Extensions/Boost/BoostChart.ts
Labels: Product: Highcharts, Changelog: Bugfix

#21122 demo/add-renko-to-demos
  samples/stock/demo/renko/demo.css
  samples/stock/demo/renko/demo.details
  samples/stock/demo/renko/demo.html
  samples/stock/demo/renko/demo.js
Labels: Product: Highcharts Stock

#21304 bugfix/20494-reset-responsive-config
  samples/unit-tests/responsive/responsive/demo.js
  ts/Core/Responsive.ts
Labels: Product: Highcharts, Changelog: Bugfix

#21278 bugfix/21245-boxplot-multiple-series-position
  samples/unit-tests/series-boxplot/boxplot/demo.js
  ts/Series/BoxPlot/BoxPlotSeries.ts
Labels: Product: Highcharts, Changelog: Bugfix

#21212 bugfix/20969-tooltip-not-destroyed
  ts/Core/Pointer.ts
Labels: Product: Highcharts, Changelog: Bugfix

#21250 bugfix/20435-points-events-update-regression
  samples/unit-tests/series/update/demo.js
  ts/Core/Series/Point.ts
Labels: Product: Highcharts, Changelog: Bugfix

#21321 bugfix/21124-special-char-breaks-format
  samples/unit-tests/utilities/format/demo.js
  ts/Core/Templating.ts
Labels: Product: Highcharts, Changelog: Bugfix

#21264 bugfix/21177-packedBubble-setData-when-hidden
  ts/Series/PackedBubble/PackedBubblePoint.ts
Labels: Product: Highcharts, Changelog: Bugfix

#21094 Demo/bar force
  samples/highcharts/demo/bar-force/demo.css
  samples/highcharts/demo/bar-force/demo.details
  samples/highcharts/demo/bar-force/demo.html
  samples/highcharts/demo/bar-force/demo.js
  samples/highcharts/demo/variwide/demo.css
Labels: Product: Highcharts

#21330 dash/labels-missing-sidebar
  css/dashboards/dashboards.css
  samples/dashboards/cypress/edit-mode-options/demo.mjs
  test/cypress/dashboards/integration/EditMode/sidebar.cy.js
Labels: Product: Highcharts Dashboards

#21323 dash/editableOptions-simplify
  ts/Dashboards/Components/Component.ts
  ts/Dashboards/Components/HighchartsComponent/HighchartsComponentDefaults.ts
  ts/Dashboards/Components/KPIComponent/KPIComponentDefaults.ts
Labels: Changelog: Bugfix, Product: Highcharts Dashboards

#21342 Bugfix/21341 svg label update height
  samples/unit-tests/svgrenderer/label/demo.js
  ts/Core/Renderer/SVG/SVGLabel.ts
Labels: Product: Highcharts, Changelog: Bugfix

#21334 bugfix/stacklabels-inverted-chart
  samples/unit-tests/series/stacking/demo.js
  ts/Core/Axis/Stacking/StackItem.ts
Labels: Product: Highcharts, Changelog: Bugfix

#21363 dash/datagrid2-benchmark-upgrade
  samples/data-grid/v2/benchmark/demo.css
  samples/data-grid/v2/benchmark/demo.html
  samples/data-grid/v2/benchmark/demo.js
Labels: Product: Highcharts Dashboards

#21369 dash/datagrid2-code-cleanup-upgrades
  css/datagrid/datagrid2.css
  samples/data-grid/v2/benchmark/demo.css
  samples/data-grid/v2/benchmark/demo.html
  samples/data-grid/v2/benchmark/demo.js
  samples/data-grid/v2/column-options/demo.css
  samples/data-grid/v2/column-options/demo.html
  samples/data-grid/v2/column-options/demo.js
  samples/data-grid/v2/column-resizing-disabled/demo.css
  samples/data-grid/v2/column-resizing-disabled/demo.html
  samples/data-grid/v2/column-resizing-disabled/demo.js
  samples/data-grid/v2/destroy-datagrid/demo.js
  samples/data-grid/v2/fixed-distribution/demo.js
  samples/data-grid/v2/no-data/demo.js
  samples/data-grid/v2/scroll-to-row/demo.js
  samples/data-grid/v2/strict-row-heights/demo.js
  tools/gulptasks/dashboards/scripts-dts/datagrid.src.d.ts
  ts/DataGrid/DataGrid2/Actions/ColumnsResizer.ts
  ts/DataGrid/DataGrid2/Actions/RowsVirtualizer.ts
  ts/DataGrid/DataGrid2/DataGrid.ts
  ts/DataGrid/DataGrid2/DataGridCell.ts
  ts/DataGrid/DataGrid2/DataGridColumn.ts
  ts/DataGrid/DataGrid2/DataGridDefaultOptions.ts
  ts/DataGrid/DataGrid2/DataGridOptions.d.ts
  ts/DataGrid/DataGrid2/DataGridRow.ts
  ts/DataGrid/DataGrid2/DataGridTable.ts
  ts/DataGrid/DataGrid2/DataGridTableHead.ts
  ts/DataGrid/DataGrid2/Globals.ts
  ts/DataGrid/DataGrid2/Utils.ts
  ts/masters-datagrid/datagrid.src.ts
Labels: Type: Enhancement, Product: Highcharts Dashboards

#21340 feature/stock-components-benchmark
  test/ts-node-unit-tests/benchmarks/Stock/Stock-Annotations-update.bench.ts
  test/ts-node-unit-tests/benchmarks/Stock/Stock-Navigator-update.bench.ts
  test/ts-node-unit-tests/benchmarks/Stock/Stock-Range-Selector-update.bench.ts
  test/ts-node-unit-tests/benchmarks/Stock/Stock-Tools-update.bench.ts
  test/ts-node-unit-tests/benchmarks/Stock/Stock-update.bench.ts
Labels: Product: Highcharts Stock

#21386 bugfix/21302-ts-tooltip-constructor
  ts/Core/Tooltip.ts
Labels: Product: Highcharts, Changelog: Bugfix

#21270 bugfix/20525-boost-markers-toggling-on-series-hide
  samples/unit-tests/boost/setvisible/demo.js
  ts/Extensions/Boost/BoostSeries.ts
Labels: Product: Highcharts, Changelog: Bugfix

#21387 dash/settings-row
  test/cypress/dashboards/integration/EditMode/dragdrop.cy.js
  test/cypress/dashboards/integration/options-lang.cy.js
  ts/Dashboards/EditMode/Toolbar/RowEditToolbar.ts
Labels: Changelog: Feature, Product: Highcharts Dashboards

#21261 bugfix/21098-ie11-compatibility-issues
  ts/Core/MSPointer.ts
  ts/Core/Renderer/HTML/AST.ts
  ts/Core/Renderer/SVG/SVGRenderer.ts
  ts/masters-es5/highcharts.src.ts
  ts/masters-es5/polyfills.ts
Labels: Product: Highcharts, Changelog: Bugfix

#21406 Renamed onEditModeToggle to toggleEditMode.
  ts/Dashboards/EditMode/EditContextMenu.ts
  ts/Dashboards/EditMode/EditMode.ts
Labels: Changelog: Feature, Product: Highcharts Dashboards
