Repository highcharts/highcharts, pull requests merged in 2024-04, with the labels that each got.

#20923 bugfix/20710-legend-movement-bubble-coloraxis
  samples/unit-tests/bubble-legend/layout/demo.js
  ts/Core/Axis/Color/ColorAxis.ts
  ts/Series/Bubble/BubbleLegendComposition.ts
Labels: Product: Highcharts, Changelog: Bugfix

#20918 bugfix/20809-panning-to-extremes
  samples/unit-tests/chart/panning/demo.js
  ts/Core/Axis/NavigatorAxisComposition.ts
  ts/Core/Axis/OrdinalAxis.ts
Labels: Product: Highcharts Stock, Changelog: Bugfix

#20926 bugfix/all-maps-credits
  samples/maps/demo/all-maps/demo.js
  test/karma-conf.js
Labels: Product: Docs, Product: Highcharts Maps

#20905 Bugfix/dragging control point annotation
  samples/unit-tests/stock-tools/stock-annotation-dragging/demo.css
  samples/unit-tests/stock-tools/stock-annotation-dragging/demo.details
  samples/unit-tests/stock-tools/stock-annotation-dragging/demo.html
  samples/unit-tests/stock-tools/stock-annotation-dragging/demo.js
  ts/Core/Axis/OrdinalAxis.ts
Labels: Product: Highcharts Stock, Changelog: Bugfix

#20924 dash/bugfix-duplicated-component-id
  test/typescript-karma/Dashboards/Component/highcharts.js
  ts/Dashboards/Actions/Bindings.ts
Labels: Changelog: Bugfix, Product: Highcharts Dashboards

#20950 bugfix/drilldown-regression
  ts/Core/Axis/Color/ColorAxis.ts
Labels: Product: Highcharts

#20910 dash/custom-component-connector
  docs/dashboards/custom-component.md
  samples/dashboards/components/custom-component-data-connector/demo.css
  samples/dashboards/components/custom-component-data-connector/demo.details
  samples/dashboards/components/custom-component-data-connector/demo.html
  samples/dashboards/components/custom-component-data-connector/demo.js
Labels: Product: Highcharts Dashboards

#20949 dash/climate-improvements
  samples/dashboards/demo/climate/demo.css
  samples/dashboards/demo/climate/demo.js
Labels: Product: Highcharts Dashboards

#20614 bugfix/20529-rangeselector-option
  samples/unit-tests/rangeselector/chart-option-comparison/demo.css
  samples/unit-tests/rangeselector/chart-option-comparison/demo.details
  samples/unit-tests/rangeselector/chart-option-comparison/demo.html
  samples/unit-tests/rangeselector/chart-option-comparison/demo.js
  ts/Stock/RangeSelector/RangeSelector.ts
Labels: Product: Highcharts, Changelog: Bugfix

#20966 bugfix/20965 label align animation
  ts/Core/Renderer/SVG/SVGElement.ts
  ts/Extensions/Exporting/Exporting.ts
  ts/Stock/RangeSelector/RangeSelector.ts
Labels: Changelog: Bugfix

#20952 Added stepDistance parameter to geodesic
  samples/maps/demo/projection-explorer/demo.js
  ts/Maps/Projection.ts
Labels: Type: Enhancement, Product: Highcharts Maps

#20953 dash/highlight-sync-affected-series
  docs/dashboards/highcharts-component.md
  docs/dashboards/synchronize-components.md
  samples/dashboards/sync/highcharts-highlight-affected-series/demo.css
  samples/dashboards/sync/highcharts-highlight-affected-series/demo.details
  samples/dashboards/sync/highcharts-highlight-affected-series/demo.html
  samples/dashboards/sync/highcharts-highlight-affected-series/demo.js
  test/cypress/dashboards/integration/Components/Highcharts/HighchartsComponent.cy.js
  ts/Dashboards/Components/HighchartsComponent/HighchartsComponentOptions.ts
  ts/Dashboards/Components/HighchartsComponent/HighchartsSyncs/HighchartsHighlightSync.ts
Labels: Changelog: Feature, Product: Highcharts Dashboards

#20946 bugfix/a11y-series-description
  samples/unit-tests/accessibility/descriptions-added/demo.html
  samples/unit-tests/accessibility/descriptions-added/demo.js
  ts/Accessibility/Components/SeriesComponent/SeriesComponent.ts
Labels: Product: Highcharts, Changelog: Bugfix, a11y

#20976 bugfix/20936-boosted-navigator-inverted-charts
  samples/unit-tests/boost/general/demo.js
  ts/Extensions/Boost/BoostChart.ts
Labels: Product: Highcharts Stock, Changelog: Bugfix

#20959 bugfix/20451-symbolwidth-height-coloraxis
  samples/unit-tests/coloraxis/coloraxis-padding/demo.js
  ts/Core/Axis/Color/ColorAxis.ts
Labels: Product: Highcharts, Changelog: Bugfix

#20994 bugfix/20560-arearange-hover-destroy
  samples/unit-tests/chart/destroy/demo.js
  ts/Core/Series/Point.ts
Labels: Product: Highcharts, Changelog: Bugfix

#20772 Dash/election demo
  samples/dashboards/demo/election/demo.css
  samples/dashboards/demo/election/demo.details
  samples/dashboards/demo/election/demo.html
  samples/dashboards/demo/election/demo.js
  samples/dashboards/demo/election/test-notes.md
  samples/data/us-1976-2020-president.csv
  samples/data/us-electorial_votes.csv
  samples/graphics/dashboards/election/biden.jpg
  samples/graphics/dashboards/election/clinton.jpg
  samples/graphics/dashboards/election/mccain.jpg
  samples/graphics/dashboards/election/obama.jpg
  samples/graphics/dashboards/election/romney.jpg
  samples/graphics/dashboards/election/trump.jpg
Labels: Product: Highcharts Dashboards

#21036 dash/20944-values-sidebar
  samples/dashboards/cypress/edit-mode-options/demo.mjs
  test/cypress/dashboards/integration/EditMode/dragdrop.cy.js
  ts/Dashboards/Components/HighchartsComponent/HighchartsComponent.ts
Labels: Changelog: Bugfix, Product: Highcharts Dashboards

#21033 bugfix/20405-drag-node-follow
  samples/unit-tests/series-networkgraph/networkgraph/demo.js
  ts/Series/Networkgraph/ReingoldFruchtermanLayout.ts
Labels: Product: Highcharts, Changelog: Bugfix

#20989 bugfix/20876-drillupall-event-performance
  samples/unit-tests/drilldown/drillup/demo.js
  ts/Extensions/Drilldown/Drilldown.ts
Labels: Product: Highcharts, Changelog: Bugfix

#20993 bugfix/20998-axis-left-dataLabels-overflow
  samples/unit-tests/datalabels/xy/demo.js
  ts/Core/Series/DataLabel.ts
Labels: Product: Highcharts, Changelog: Bugfix

#20991 Bugfix/20922 skipped dg tests
  samples/unit-tests/series/datagrouping/demo.js
  ts/Extensions/DataGrouping/DataGroupingSeriesComposition.ts
Labels: Product: Highcharts Stock

#20962 bugfix/20816-templating-date-format
  samples/unit-tests/tooltip/pointformat/demo.js
  ts/Core/Templating.ts
Labels: Product: Highcharts, Changelog: Bugfix

#21009 dash/sync-groups
  docs/dashboards/synchronize-components.md
  samples/dashboards/sync/groups/demo.css
  samples/dashboards/sync/groups/demo.details
  samples/dashboards/sync/groups/demo.html
  samples/dashboards/sync/groups/demo.js
  test/cypress/dashboards/integration/sync/sync-on-added-connector.cy.js
  test/cypress/dashboards/integration/sync/sync.cy.js
  ts/Dashboards/Board.ts
  ts/Dashboards/Components/DataGridComponent/DataGridSyncs/DataGridExtremesSync.ts
  ts/Dashboards/Components/DataGridComponent/DataGridSyncs/DataGridHighlightSync.ts
  ts/Dashboards/Components/DataGridComponent/DataGridSyncs/DataGridVisibilitySync.ts
  ts/Dashboards/Components/HighchartsComponent/HighchartsSyncs/HighchartsExtremesSync.ts
  ts/Dashboards/Components/HighchartsComponent/HighchartsSyncs/HighchartsHighlightSync.ts
  ts/Dashboards/Components/HighchartsComponent/HighchartsSyncs/HighchartsVisibilitySync.ts
  ts/Dashboards/Components/KPIComponent/KPISyncs/KPIExtremesSync.ts
  ts/Dashboards/Components/NavigatorComponent/NavigatorSyncs/NavigatorCrossfilterSync.ts
  ts/Dashboards/Components/NavigatorComponent/NavigatorSyncs/NavigatorExtremesSync.ts
  ts/Dashboards/Components/Sync/Sync.ts
  ts/Data/DataCursor.ts
Labels: Changelog: Feature, Product: Highcharts Dashboards

#21056 bugfix/20877-mobile-touch-panning
  ts/Core/Chart/Chart.ts
Labels: Product: Highcharts Stock, Changelog: Bugfix

#21048 docs/207150-incorrect-demo-height
  docs/stock/stock-tools.md
Labels: Product: Docs

#21011 feature/navigator-handles-radius
  samples/stock/navigator/handles-border-radius/demo.css
  samples/stock/navigator/handles-border-radius/demo.details
  samples/stock/navigator/handles-border-radius/demo.html
  samples/stock/navigator/handles-border-radius/demo.js
  ts/Stock/Navigator/NavigatorDefaults.ts
  ts/Stock/Navigator/NavigatorOptions.d.ts
  ts/Stock/Navigator/NavigatorSymbols.ts
Labels: Product: Highcharts Stock, Changelog: Feature

#21063 Fixed #20988, wrong annotations references in options.
  ts/Extensions/Annotations/EventEmitter.ts
Labels: Changelog: Bugfix

#21010 feature/cumulative-start-option
  samples/stock/plotoptions/series-cumulativestart/demo.css
  samples/stock/plotoptions/series-cumulativestart/demo.details
  samples/stock/plotoptions/series-cumulativestart/demo.html
  samples/stock/plotoptions/series-cumulativestart/demo.js
  samples/unit-tests/series/cumulative/demo.js
  ts/Series/DataModifyComposition.ts
Labels: Product: Highcharts Stock, Changelog: Feature

#20985 bugfix/20804-radialaxis-setoptions
  samples/unit-tests/series-solidgauge/solidgauge/demo.js
  test/karma-setup.js
  ts/Core/Axis/RadialAxis.ts
  ts/Core/Axis/RadialAxisDefaults.ts
  ts/Core/Axis/RadialAxisOptions.d.ts
  ts/Core/Axis/SolidGaugeAxis.ts
  ts/Core/Defaults.ts
  ts/masters/highcharts-more.src.ts
Labels: Product: Highcharts, Changelog: Bugfix

#21077 docs/20391-exclude-dragdrop-networkgraph
  ts/Series/Networkgraph/NetworkgraphSeriesDefaults.ts
Labels: Product: Docs

#21073 bugfix/21050-missing-a11y-module-in-caption-text-demo
  samples/highcharts/caption/text/demo.html
Labels: Product: Docs, a11y

#21046 bugfix/20886-map-drilldown-mouse-tracking
  samples/unit-tests/maps/drilldown/demo.js
  ts/Extensions/Drilldown/Drilldown.ts
Labels: Product: Highcharts Maps, Changelog: Bugfix
