Repository highcharts/highcharts, pull requests merged in 2025-08, with the labels that each got.

#23356 dash/getOptions-grid
  samples/dashboards/cypress/component-grid-resize/demo.css
  samples/dashboards/cypress/component-grid-resize/demo.html
  samples/dashboards/cypress/component-grid-resize/demo.mjs
  test/cypress/grid/integration/resize.cy.js
  ts/Dashboards/Components/DataGridComponent/DataGridComponent.ts
  ts/Grid/Core/Grid.ts
Labels: Changelog: Bugfix, Product: Highcharts Dashboards

#23158 enhancement/export-inline-webfonts
  docs/export-module/export-module-overview.md
  samples/highcharts/exporting/offline-download-webfonts/demo.css
  samples/highcharts/exporting/offline-download-webfonts/demo.details
  samples/highcharts/exporting/offline-download-webfonts/demo.html
  samples/highcharts/exporting/offline-download-webfonts/demo.js
  samples/highcharts/exporting/offline-download-webfonts/test-notes.md
  samples/unit-tests/exporting/exportchart/demo.js
  ts/Extensions/Exporting/Exporting.ts
Labels: Product: Highcharts, Changelog: Feature

#23226 bugfix/23062-connectorWidth-update
  samples/unit-tests/axis/labels/demo.js
  ts/Series/Pie/PieDataLabel.ts
Labels: Product: Highcharts, Changelog: Bugfix

#23187 docs/23084-lang-locale
  docs/chart-concepts/templating.md
  ts/Core/Defaults.ts
Labels: Product: Docs

#23297 bugfix/23296
  ts/Core/Axis/PlotLineOrBand/PlotLineOrBand.ts
Labels: Product: Highcharts, Changelog: Bugfix

#23324 bugfix/22489-scrollableplotarea-update
  samples/unit-tests/scrollable-plotarea/dynamics/demo.js
  ts/Extensions/ScrollablePlotArea.ts
Labels: Changelog: Bugfix

#23320 bugfix/22586-waterfall-big
  samples/unit-tests/series-waterfall/waterfall/demo.js
  ts/Series/Waterfall/WaterfallSeries.ts
Labels: Changelog: Bugfix

#23348 bugfix/22943-gantt-styled-labels
  samples/unit-tests/gantt/grid-axis/demo.css
  samples/unit-tests/gantt/grid-axis/demo.js
  ts/Core/Renderer/HTML/HTMLElement.ts
Labels: Product: Highcharts, Changelog: Bugfix

#23369 bugfix/23151-polar-interaction
  samples/unit-tests/polar/polar-zoom/demo.js
  ts/Extensions/Pane/PaneComposition.ts
Labels: Product: Highcharts, Changelog: Bugfix

#23388 Fixed #23329; a11y markers visible after range toggling.
  ts/Accessibility/Components/SeriesComponent/ForcedMarkers.ts
Labels: Product: Highcharts Stock, Changelog: Bugfix, a11y

#23317 Bugfix: Fix partial hidden markers under axis in boost. #9799
  samples/highcharts/boost/line-markers/demo.js
  ts/Extensions/Boost/BoostSeries.ts
  ts/Extensions/Boost/BoostTargetObject.d.ts
  ts/Extensions/Boost/WGLRenderer.ts
  ts/Extensions/Boost/WGLShader.ts
  ts/Extensions/BoostCanvas.ts
Labels: Changelog: Bugfix

#23358 bugfix/23335-boosted-heatmap-scrollbar
  samples/unit-tests/boost/heatmap-styled-mode/demo.html
  samples/unit-tests/boost/heatmap-styled-mode/demo.js
  ts/Core/Axis/ScrollbarAxis.ts
Labels: Product: Highcharts, Changelog: Bugfix

#23413 dash/election-demo-dark-mode
  samples/dashboards/demo/election/demo.css
Labels: Product: Highcharts Dashboards

#23408 dash/unique-validator
  docs/grid/cell-editing.md
  samples/grid-pro/basic/cell-editing/demo.js
  samples/grid-pro/cypress/cell-editing/demo.js
  test/cypress/grid/integration/grid-pro/validation.cy.js
  test/cypress/support/index.js
  ts/Grid/Pro/ColumnTypes/Validator.ts
Labels: Changelog: Feature, Product: Highcharts Grid, Grid Pro

#23386 dash/validation-demo
  samples/grid-pro/demo/cell-editing/demo.html
  samples/grid-pro/demo/validation/demo.css
  samples/grid-pro/demo/validation/demo.details
  samples/grid-pro/demo/validation/demo.html
  samples/grid-pro/demo/validation/demo.js
Labels: Product: Highcharts Grid

#23415 Fixed #22807, SVGRenderer.fontMetrics throw exception with number input.
  samples/unit-tests/svgrenderer/text/demo.js
  ts/Core/Renderer/SVG/SVGRenderer.ts
Labels: Product: Highcharts, Changelog: Bugfix

#23428 dash/theming-demo-light-mode
  samples/grid-lite/demo/grid-theming/demo.css
Labels: Product: Highcharts Dashboards

#23272 bugfix/23208-non-cartesian-inverted
  ts/Extensions/NonCartesianSeriesZoom/NonCartesianSeriesZoom.ts
  ts/Series/XRange/XRangePoint.ts
Labels: Product: Highcharts, Changelog: Bugfix

#23384 bugfix/22907-misplaced-tooltip-anchor
  ts/Core/Renderer/SVG/SVGLabel.ts
Labels: Product: Highcharts, Changelog: Bugfix

#23435 Fixed #23432, could not drill down to added treemap nodes
  samples/unit-tests/series-treemap/update/demo.js
  ts/Series/Treemap/TreemapSeries.ts
Labels: Product: Highcharts, Changelog: Bugfix

#23406 enhancement/histogram-bellseries
  docs/chart-and-series-types/bell-curve-series.md
  docs/chart-and-series-types/histogram-series.md
  samples/highcharts/demo/bellcurve/demo.details
  samples/highcharts/demo/bellcurve/demo.html
  samples/highcharts/demo/bellcurve/demo.js
  samples/highcharts/demo/bellcurve/readme.md
  samples/highcharts/demo/histogram/demo.details
  samples/highcharts/demo/histogram/demo.html
  samples/highcharts/demo/histogram/demo.js
  samples/highcharts/demo/histogram/readme.md
  samples/unit-tests/coloraxis/series-types/demo.js
  samples/unit-tests/series-histogram/histogram/demo.js
  samples/unit-tests/styled-mode/series-types/demo.js
  ts/Core/Series/Series.ts
  ts/Series/Bellcurve/BellcurveSeries.ts
  ts/Series/Bellcurve/BellcurveSeriesOptions.d.ts
  ts/Series/Histogram/HistogramSeries.ts
  ts/Series/Histogram/HistogramSeriesOptions.d.ts
Labels: Changelog: Feature

#23156 bugfix/22821-labels-missing
  samples/unit-tests/axis/labels/demo.js
  ts/Core/Axis/Axis.ts
Labels: Product: Highcharts, Changelog: Bugfix

#23455 dash/bugfix-redundant-JSON-connector-data-default-option
  ts/Data/Connectors/JSONConnector.ts
  ts/Data/Converters/JSONConverter.ts
Labels: Changelog: Bugfix, Product: Highcharts Dashboards

#23481 Fixed #23480, error when casting series type from variwide
  css/highcharts.css
  samples/unit-tests/series-variwide/variwide/demo.js
  ts/Series/Variwide/VariwideComposition.ts
Labels: Product: Highcharts, Changelog: Bugfix

#23299 bugfix/23252-exportdata-thousandsep
  samples/unit-tests/export-data/basics/demo.js
  ts/Extensions/ExportData/ExportData.ts
Labels: Product: Highcharts, Changelog: Bugfix

#23357 bugfix/22950/markers-issue-boost
  samples/unit-tests/boost/general/demo.js
  ts/Extensions/Boost/BoostSeries.ts
Labels: Product: Highcharts, Changelog: Bugfix

#23489 Border radius on subsequent arcs
  samples/highcharts/demo/gauge-speedometer/demo.js
  samples/highcharts/demo/polar-radial-bar/demo.js
  ts/Core/Axis/RadialAxis.ts
  ts/Extensions/BorderRadius.ts
  ts/Series/PolarComposition.ts
Labels: Changelog: Feature

#23470 dash/v4-deprecated-items-remove
  docs/grid/cell-renderers.md
  samples/dashboards/cypress/duplicated-ids/demo.mjs
  samples/dashboards/demo/cloud-monitoring/demo.js
  samples/dashboards/demo/live-weather/demo.js
  samples/dashboards/studies/sun-horizon/demo.js
  samples/grid-pro/basic/exporting-json/demo.js
  samples/grid-pro/cypress/exporting-json/demo.js
  test/cypress/dashboards/integration/json-serialization.cy.js
  test/typescript-dts/dashboards/dashboards.ts
  test/typescript-dts/grid/grid-lite.ts
  test/typescript-karma/Dashboards/Grid/grid.test.js
  ts/Dashboards/Actions/Bindings.ts
  ts/Dashboards/Board.ts
  ts/Dashboards/Components/Component.ts
  ts/Dashboards/Components/DataGridComponent/DataGridComponent.ts
  ts/Dashboards/Components/HTMLComponent/HTMLComponent.ts
  ts/Dashboards/Components/HighchartsComponent/HighchartsComponent.ts
  ts/Dashboards/Components/HighchartsComponent/HighchartsComponentOptions.ts
  ts/Dashboards/Components/KPIComponent/KPIComponent.ts
  ts/Dashboards/Components/NavigatorComponent/NavigatorComponent.ts
  ts/Dashboards/Components/NavigatorComponent/NavigatorComponentOptions.ts
  ts/Dashboards/EditMode/EditMode.ts
  ts/Dashboards/EditMode/SidebarPopup.ts
  ts/Dashboards/Layout/Cell.ts
  ts/Grid/Core/Grid.ts
  ts/Grid/Core/Table/Table.ts
  ts/Grid/Pro/CellEditing/CellEditingComposition.ts
  ts/Grid/Pro/Dash3Compatibility.ts
  ts/Grid/Pro/GridEvents.ts
Labels: Product: Highcharts Dashboards, Product: Highcharts Grid

#23494 Fixed #23396, added border radius to solid gauge series.
  ts/Series/SolidGauge/SolidGaugeSeriesDefaults.ts
  ts/Series/SolidGauge/SolidGaugeSeriesOptions.d.ts
Labels: Product: Highcharts, Product: Docs
